// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: bridge/v1/administrator.proto

package bridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdministratorService_CreateBridge_FullMethodName = "/bridge.v1.AdministratorService/CreateBridge"
	AdministratorService_ListBridges_FullMethodName  = "/bridge.v1.AdministratorService/ListBridges"
	AdministratorService_DeleteBridge_FullMethodName = "/bridge.v1.AdministratorService/DeleteBridge"
)

// AdministratorServiceClient is the client API for AdministratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdministratorService manages bridge lifecycle in a Kubernetes cluster.
type AdministratorServiceClient interface {
	// CreateBridge provisions a new bridge in the source deployment's namespace,
	// swapping the application container for the bridge proxy.
	CreateBridge(ctx context.Context, in *CreateBridgeRequest, opts ...grpc.CallOption) (*CreateBridgeResponse, error)
	// ListBridges returns all active bridges for a device across all namespaces.
	ListBridges(ctx context.Context, in *ListBridgesRequest, opts ...grpc.CallOption) (*ListBridgesResponse, error)
	// DeleteBridge tears down a specific bridge and its associated resources.
	DeleteBridge(ctx context.Context, in *DeleteBridgeRequest, opts ...grpc.CallOption) (*DeleteBridgeResponse, error)
}

type administratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdministratorServiceClient(cc grpc.ClientConnInterface) AdministratorServiceClient {
	return &administratorServiceClient{cc}
}

func (c *administratorServiceClient) CreateBridge(ctx context.Context, in *CreateBridgeRequest, opts ...grpc.CallOption) (*CreateBridgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBridgeResponse)
	err := c.cc.Invoke(ctx, AdministratorService_CreateBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *administratorServiceClient) ListBridges(ctx context.Context, in *ListBridgesRequest, opts ...grpc.CallOption) (*ListBridgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBridgesResponse)
	err := c.cc.Invoke(ctx, AdministratorService_ListBridges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *administratorServiceClient) DeleteBridge(ctx context.Context, in *DeleteBridgeRequest, opts ...grpc.CallOption) (*DeleteBridgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBridgeResponse)
	err := c.cc.Invoke(ctx, AdministratorService_DeleteBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdministratorServiceServer is the server API for AdministratorService service.
// All implementations must embed UnimplementedAdministratorServiceServer
// for forward compatibility.
//
// AdministratorService manages bridge lifecycle in a Kubernetes cluster.
type AdministratorServiceServer interface {
	// CreateBridge provisions a new bridge in the source deployment's namespace,
	// swapping the application container for the bridge proxy.
	CreateBridge(context.Context, *CreateBridgeRequest) (*CreateBridgeResponse, error)
	// ListBridges returns all active bridges for a device across all namespaces.
	ListBridges(context.Context, *ListBridgesRequest) (*ListBridgesResponse, error)
	// DeleteBridge tears down a specific bridge and its associated resources.
	DeleteBridge(context.Context, *DeleteBridgeRequest) (*DeleteBridgeResponse, error)
	mustEmbedUnimplementedAdministratorServiceServer()
}

// UnimplementedAdministratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdministratorServiceServer struct{}

func (UnimplementedAdministratorServiceServer) CreateBridge(context.Context, *CreateBridgeRequest) (*CreateBridgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBridge not implemented")
}
func (UnimplementedAdministratorServiceServer) ListBridges(context.Context, *ListBridgesRequest) (*ListBridgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBridges not implemented")
}
func (UnimplementedAdministratorServiceServer) DeleteBridge(context.Context, *DeleteBridgeRequest) (*DeleteBridgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBridge not implemented")
}
func (UnimplementedAdministratorServiceServer) mustEmbedUnimplementedAdministratorServiceServer() {}
func (UnimplementedAdministratorServiceServer) testEmbeddedByValue()                              {}

// UnsafeAdministratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdministratorServiceServer will
// result in compilation errors.
type UnsafeAdministratorServiceServer interface {
	mustEmbedUnimplementedAdministratorServiceServer()
}

func RegisterAdministratorServiceServer(s grpc.ServiceRegistrar, srv AdministratorServiceServer) {
	// If the following call panics, it indicates UnimplementedAdministratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdministratorService_ServiceDesc, srv)
}

func _AdministratorService_CreateBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdministratorServiceServer).CreateBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdministratorService_CreateBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdministratorServiceServer).CreateBridge(ctx, req.(*CreateBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdministratorService_ListBridges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBridgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdministratorServiceServer).ListBridges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdministratorService_ListBridges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdministratorServiceServer).ListBridges(ctx, req.(*ListBridgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdministratorService_DeleteBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdministratorServiceServer).DeleteBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdministratorService_DeleteBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdministratorServiceServer).DeleteBridge(ctx, req.(*DeleteBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdministratorService_ServiceDesc is the grpc.ServiceDesc for AdministratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdministratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.v1.AdministratorService",
	HandlerType: (*AdministratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBridge",
			Handler:    _AdministratorService_CreateBridge_Handler,
		},
		{
			MethodName: "ListBridges",
			Handler:    _AdministratorService_ListBridges_Handler,
		},
		{
			MethodName: "DeleteBridge",
			Handler:    _AdministratorService_DeleteBridge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge/v1/administrator.proto",
}
