// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge/v1/administrator.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateBridgeRequest is sent by the bridge CLI to the Administrator to provision a new bridge.
type CreateBridgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The KSUID identifying the developer's device (from ~/.bridge/device-id.txt).
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,proto3" json:"device_id,omitempty"`
	// The name of the source Deployment to clone. If empty, the Administrator creates
	// a simple Deployment with just the bridge proxy container.
	SourceDeployment string `protobuf:"bytes,2,opt,name=source_deployment,proto3" json:"source_deployment,omitempty"`
	// The namespace of the source Deployment. Required if source_deployment is set.
	SourceNamespace string `protobuf:"bytes,3,opt,name=source_namespace,proto3" json:"source_namespace,omitempty"`
	// If true, tear down and recreate an existing bridge for the same deployment
	// without returning an ALREADY_EXISTS error.
	Force         bool `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBridgeRequest) Reset() {
	*x = CreateBridgeRequest{}
	mi := &file_bridge_v1_administrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBridgeRequest) ProtoMessage() {}

func (x *CreateBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_administrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBridgeRequest.ProtoReflect.Descriptor instead.
func (*CreateBridgeRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_administrator_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBridgeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CreateBridgeRequest) GetSourceDeployment() string {
	if x != nil {
		return x.SourceDeployment
	}
	return ""
}

func (x *CreateBridgeRequest) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *CreateBridgeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// CreateBridgeResponse is returned by the Administrator after a bridge is provisioned.
type CreateBridgeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace where the bridged pod was created (bridge-<device-id>).
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The name of the bridged pod.
	PodName string `protobuf:"bytes,2,opt,name=pod_name,proto3" json:"pod_name,omitempty"`
	// The port on the bridged pod where the bridge proxy server is listening.
	Port int32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// The name of the Deployment that owns the bridged pod.
	DeploymentName string `protobuf:"bytes,4,opt,name=deployment_name,proto3" json:"deployment_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBridgeResponse) Reset() {
	*x = CreateBridgeResponse{}
	mi := &file_bridge_v1_administrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBridgeResponse) ProtoMessage() {}

func (x *CreateBridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_administrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBridgeResponse.ProtoReflect.Descriptor instead.
func (*CreateBridgeResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_administrator_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBridgeResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateBridgeResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *CreateBridgeResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreateBridgeResponse) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

// ListBridgesRequest is sent to query active bridges.
type ListBridgesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The device ID to list bridges for. Required.
	DeviceId      string `protobuf:"bytes,1,opt,name=device_id,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBridgesRequest) Reset() {
	*x = ListBridgesRequest{}
	mi := &file_bridge_v1_administrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBridgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgesRequest) ProtoMessage() {}

func (x *ListBridgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_administrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgesRequest.ProtoReflect.Descriptor instead.
func (*ListBridgesRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_administrator_proto_rawDescGZIP(), []int{2}
}

func (x *ListBridgesRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// BridgeInfo describes an active bridge.
type BridgeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The device ID that owns this bridge.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,proto3" json:"device_id,omitempty"`
	// The source deployment this bridge was cloned from.
	SourceDeployment string `protobuf:"bytes,2,opt,name=source_deployment,proto3" json:"source_deployment,omitempty"`
	// The source namespace of the deployment.
	SourceNamespace string `protobuf:"bytes,3,opt,name=source_namespace,proto3" json:"source_namespace,omitempty"`
	// The namespace where the bridge is running.
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// When the bridge was created (RFC 3339).
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	// Current status of the bridge (e.g., "running", "pending", "error").
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeInfo) Reset() {
	*x = BridgeInfo{}
	mi := &file_bridge_v1_administrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeInfo) ProtoMessage() {}

func (x *BridgeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_administrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeInfo.ProtoReflect.Descriptor instead.
func (*BridgeInfo) Descriptor() ([]byte, []int) {
	return file_bridge_v1_administrator_proto_rawDescGZIP(), []int{3}
}

func (x *BridgeInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *BridgeInfo) GetSourceDeployment() string {
	if x != nil {
		return x.SourceDeployment
	}
	return ""
}

func (x *BridgeInfo) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *BridgeInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *BridgeInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BridgeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ListBridgesResponse contains all active bridges matching the filter.
type ListBridgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridges       []*BridgeInfo          `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBridgesResponse) Reset() {
	*x = ListBridgesResponse{}
	mi := &file_bridge_v1_administrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBridgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgesResponse) ProtoMessage() {}

func (x *ListBridgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_administrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgesResponse.ProtoReflect.Descriptor instead.
func (*ListBridgesResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_administrator_proto_rawDescGZIP(), []int{4}
}

func (x *ListBridgesResponse) GetBridges() []*BridgeInfo {
	if x != nil {
		return x.Bridges
	}
	return nil
}

// DeleteBridgeRequest identifies a bridge to tear down.
type DeleteBridgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The device ID that owns the bridge.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,proto3" json:"device_id,omitempty"`
	// The source deployment name to identify which bridge to delete.
	// If empty, deletes the entire device namespace and all bridges within it.
	SourceDeployment string `protobuf:"bytes,2,opt,name=source_deployment,proto3" json:"source_deployment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteBridgeRequest) Reset() {
	*x = DeleteBridgeRequest{}
	mi := &file_bridge_v1_administrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBridgeRequest) ProtoMessage() {}

func (x *DeleteBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_administrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBridgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteBridgeRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_administrator_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBridgeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeleteBridgeRequest) GetSourceDeployment() string {
	if x != nil {
		return x.SourceDeployment
	}
	return ""
}

// DeleteBridgeResponse is returned after a bridge is torn down.
type DeleteBridgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBridgeResponse) Reset() {
	*x = DeleteBridgeResponse{}
	mi := &file_bridge_v1_administrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBridgeResponse) ProtoMessage() {}

func (x *DeleteBridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_administrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBridgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteBridgeResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_administrator_proto_rawDescGZIP(), []int{6}
}

var File_bridge_v1_administrator_proto protoreflect.FileDescriptor

const file_bridge_v1_administrator_proto_rawDesc = "" +
	"\n" +
	"\x1dbridge/v1/administrator.proto\x12\tbridge.v1\"\xa3\x01\n" +
	"\x13CreateBridgeRequest\x12\x1c\n" +
	"\tdevice_id\x18\x01 \x01(\tR\tdevice_id\x12,\n" +
	"\x11source_deployment\x18\x02 \x01(\tR\x11source_deployment\x12*\n" +
	"\x10source_namespace\x18\x03 \x01(\tR\x10source_namespace\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\"\x8e\x01\n" +
	"\x14CreateBridgeResponse\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bpod_name\x18\x02 \x01(\tR\bpod_name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12(\n" +
	"\x0fdeployment_name\x18\x04 \x01(\tR\x0fdeployment_name\"2\n" +
	"\x12ListBridgesRequest\x12\x1c\n" +
	"\tdevice_id\x18\x01 \x01(\tR\tdevice_id\"\xda\x01\n" +
	"\n" +
	"BridgeInfo\x12\x1c\n" +
	"\tdevice_id\x18\x01 \x01(\tR\tdevice_id\x12,\n" +
	"\x11source_deployment\x18\x02 \x01(\tR\x11source_deployment\x12*\n" +
	"\x10source_namespace\x18\x03 \x01(\tR\x10source_namespace\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\n" +
	"created_at\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"F\n" +
	"\x13ListBridgesResponse\x12/\n" +
	"\abridges\x18\x01 \x03(\v2\x15.bridge.v1.BridgeInfoR\abridges\"a\n" +
	"\x13DeleteBridgeRequest\x12\x1c\n" +
	"\tdevice_id\x18\x01 \x01(\tR\tdevice_id\x12,\n" +
	"\x11source_deployment\x18\x02 \x01(\tR\x11source_deployment\"\x16\n" +
	"\x14DeleteBridgeResponse2\x86\x02\n" +
	"\x14AdministratorService\x12O\n" +
	"\fCreateBridge\x12\x1e.bridge.v1.CreateBridgeRequest\x1a\x1f.bridge.v1.CreateBridgeResponse\x12L\n" +
	"\vListBridges\x12\x1d.bridge.v1.ListBridgesRequest\x1a\x1e.bridge.v1.ListBridgesResponse\x12O\n" +
	"\fDeleteBridge\x12\x1e.bridge.v1.DeleteBridgeRequest\x1a\x1f.bridge.v1.DeleteBridgeResponseB\xa2\x01\n" +
	"\rcom.bridge.v1B\x12AdministratorProtoP\x01Z8github.com/vercel/bridge/api/go/bridge/v1;bridgev1\xa2\x02\x03BXX\xaa\x02\tBridge.V1\xca\x02\tBridge\\V1\xe2\x02\x15Bridge\\V1\\GPBMetadata\xea\x02\n" +
	"Bridge::V1b\x06proto3"

var (
	file_bridge_v1_administrator_proto_rawDescOnce sync.Once
	file_bridge_v1_administrator_proto_rawDescData []byte
)

func file_bridge_v1_administrator_proto_rawDescGZIP() []byte {
	file_bridge_v1_administrator_proto_rawDescOnce.Do(func() {
		file_bridge_v1_administrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_administrator_proto_rawDesc), len(file_bridge_v1_administrator_proto_rawDesc)))
	})
	return file_bridge_v1_administrator_proto_rawDescData
}

var file_bridge_v1_administrator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bridge_v1_administrator_proto_goTypes = []any{
	(*CreateBridgeRequest)(nil),  // 0: bridge.v1.CreateBridgeRequest
	(*CreateBridgeResponse)(nil), // 1: bridge.v1.CreateBridgeResponse
	(*ListBridgesRequest)(nil),   // 2: bridge.v1.ListBridgesRequest
	(*BridgeInfo)(nil),           // 3: bridge.v1.BridgeInfo
	(*ListBridgesResponse)(nil),  // 4: bridge.v1.ListBridgesResponse
	(*DeleteBridgeRequest)(nil),  // 5: bridge.v1.DeleteBridgeRequest
	(*DeleteBridgeResponse)(nil), // 6: bridge.v1.DeleteBridgeResponse
}
var file_bridge_v1_administrator_proto_depIdxs = []int32{
	3, // 0: bridge.v1.ListBridgesResponse.bridges:type_name -> bridge.v1.BridgeInfo
	0, // 1: bridge.v1.AdministratorService.CreateBridge:input_type -> bridge.v1.CreateBridgeRequest
	2, // 2: bridge.v1.AdministratorService.ListBridges:input_type -> bridge.v1.ListBridgesRequest
	5, // 3: bridge.v1.AdministratorService.DeleteBridge:input_type -> bridge.v1.DeleteBridgeRequest
	1, // 4: bridge.v1.AdministratorService.CreateBridge:output_type -> bridge.v1.CreateBridgeResponse
	4, // 5: bridge.v1.AdministratorService.ListBridges:output_type -> bridge.v1.ListBridgesResponse
	6, // 6: bridge.v1.AdministratorService.DeleteBridge:output_type -> bridge.v1.DeleteBridgeResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bridge_v1_administrator_proto_init() }
func file_bridge_v1_administrator_proto_init() {
	if File_bridge_v1_administrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_administrator_proto_rawDesc), len(file_bridge_v1_administrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_v1_administrator_proto_goTypes,
		DependencyIndexes: file_bridge_v1_administrator_proto_depIdxs,
		MessageInfos:      file_bridge_v1_administrator_proto_msgTypes,
	}.Build()
	File_bridge_v1_administrator_proto = out.File
	file_bridge_v1_administrator_proto_goTypes = nil
	file_bridge_v1_administrator_proto_depIdxs = nil
}
