// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge/v1/bridge.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Protocol int32

const (
	Message_PROTOCOL_UNSPECIFIED Message_Protocol = 0
	Message_PROTOCOL_TCP         Message_Protocol = 1
	Message_PROTOCOL_UDP         Message_Protocol = 2
)

// Enum value maps for Message_Protocol.
var (
	Message_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_UDP",
	}
	Message_Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_UDP":         2,
	}
)

func (x Message_Protocol) Enum() *Message_Protocol {
	p := new(Message_Protocol)
	*p = x
	return p
}

func (x Message_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_v1_bridge_proto_enumTypes[0].Descriptor()
}

func (Message_Protocol) Type() protoreflect.EnumType {
	return &file_bridge_v1_bridge_proto_enumTypes[0]
}

func (x Message_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Protocol.Descriptor instead.
func (Message_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{1, 0}
}

type ServerConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL for sandbox. This needs to be validated to be *.vercel.run.
	SandboxUrl string `protobuf:"bytes,1,opt,name=sandbox_url,proto3" json:"sandbox_url,omitempty"`
	// The connection key generated by the sandbox for tunnel pairing.
	ConnectionKey string `protobuf:"bytes,2,opt,name=connection_key,proto3" json:"connection_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConnection) Reset() {
	*x = ServerConnection{}
	mi := &file_bridge_v1_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConnection) ProtoMessage() {}

func (x *ServerConnection) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConnection.ProtoReflect.Descriptor instead.
func (*ServerConnection) Descriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConnection) GetSandboxUrl() string {
	if x != nil {
		return x.SandboxUrl
	}
	return ""
}

func (x *ServerConnection) GetConnectionKey() string {
	if x != nil {
		return x.ConnectionKey
	}
	return ""
}

// Message is the unit of communication through the tunnel.
// The first message MUST contain a Registration to identify the connection.
// Subsequent messages contain data to be relayed to the peer.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Registration is only sent on the first message to register with bridge.
	Registration *Message_Registration `protobuf:"bytes,1,opt,name=registration,proto3,oneof" json:"registration,omitempty"`
	// The address that is sending the message.
	Source *Message_Address `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// The intended target address on the destination.
	Dest *Message_Address `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`
	// The payload data being tunneled.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// Connection ID for multiplexing multiple connections over one tunnel.
	// Each unique source+dest pair represents a logical connection.
	ConnectionId string `protobuf:"bytes,5,opt,name=connection_id,proto3" json:"connection_id,omitempty"`
	// Set to true when the connection should be closed.
	Close bool `protobuf:"varint,6,opt,name=close,proto3" json:"close,omitempty"`
	// Error message if something went wrong.
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// DNS query resolution request, sent from intercept to dispatcher via the tunnel.
	DnsRequest *ResolveDNSQueryRequest `protobuf:"bytes,8,opt,name=dns_request,proto3,oneof" json:"dns_request,omitempty"`
	// DNS query resolution response, sent from dispatcher back to intercept via the tunnel.
	DnsResponse   *ResolveDNSQueryResponse `protobuf:"bytes,9,opt,name=dns_response,proto3,oneof" json:"dns_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_bridge_v1_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRegistration() *Message_Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *Message) GetSource() *Message_Address {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Message) GetDest() *Message_Address {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Message) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *Message) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Message) GetDnsRequest() *ResolveDNSQueryRequest {
	if x != nil {
		return x.DnsRequest
	}
	return nil
}

func (x *Message) GetDnsResponse() *ResolveDNSQueryResponse {
	if x != nil {
		return x.DnsResponse
	}
	return nil
}

// ResolveDNSQueryRequest is sent by the intercept client through the tunnel
// to ask the dispatcher to resolve a hostname.
type ResolveDNSQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID to correlate this request with its response.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,proto3" json:"request_id,omitempty"`
	// The hostname to resolve (e.g., "api.example.com").
	Hostname      string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDNSQueryRequest) Reset() {
	*x = ResolveDNSQueryRequest{}
	mi := &file_bridge_v1_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDNSQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDNSQueryRequest) ProtoMessage() {}

func (x *ResolveDNSQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDNSQueryRequest.ProtoReflect.Descriptor instead.
func (*ResolveDNSQueryRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveDNSQueryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResolveDNSQueryRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// ResolveDNSQueryResponse is sent by the dispatcher back through the tunnel
// with the resolved IP addresses for a DNS query.
type ResolveDNSQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request_id from the corresponding ResolveDNSQueryRequest.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,proto3" json:"request_id,omitempty"`
	// The resolved IPv4 addresses.
	Addresses []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Error message if resolution failed.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDNSQueryResponse) Reset() {
	*x = ResolveDNSQueryResponse{}
	mi := &file_bridge_v1_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDNSQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDNSQueryResponse) ProtoMessage() {}

func (x *ResolveDNSQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDNSQueryResponse.ProtoReflect.Descriptor instead.
func (*ResolveDNSQueryResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveDNSQueryResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResolveDNSQueryResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ResolveDNSQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Message_Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Address) Reset() {
	*x = Message_Address{}
	mi := &file_bridge_v1_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Address) ProtoMessage() {}

func (x *Message_Address) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Address.ProtoReflect.Descriptor instead.
func (*Message_Address) Descriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Message_Address) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Message_Address) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Message_Registration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, this is a server (Vercel proxy function).
	// If false, this is a client (local tunnel CLI).
	IsServer bool `protobuf:"varint,1,opt,name=is_server,proto3" json:"is_server,omitempty"`
	// The protocol used for the connection (TCP or UDP).
	Protocol Message_Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=bridge.v1.Message_Protocol" json:"protocol,omitempty"`
	// The URL of the proxy function that bridge should connect to.
	// Only set by clients (is_server=false). Tunneld will open a
	// Connect stream to this URL to establish the server-side connection.
	FunctionUrl string `protobuf:"bytes,3,opt,name=function_url,proto3" json:"function_url,omitempty"`
	// The Vercel deployment protection bypass secret (optional).
	ProtectionBypassSecret string `protobuf:"bytes,4,opt,name=protection_bypass_secret,proto3" json:"protection_bypass_secret,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Message_Registration) Reset() {
	*x = Message_Registration{}
	mi := &file_bridge_v1_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Registration) ProtoMessage() {}

func (x *Message_Registration) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Registration.ProtoReflect.Descriptor instead.
func (*Message_Registration) Descriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Message_Registration) GetIsServer() bool {
	if x != nil {
		return x.IsServer
	}
	return false
}

func (x *Message_Registration) GetProtocol() Message_Protocol {
	if x != nil {
		return x.Protocol
	}
	return Message_PROTOCOL_UNSPECIFIED
}

func (x *Message_Registration) GetFunctionUrl() string {
	if x != nil {
		return x.FunctionUrl
	}
	return ""
}

func (x *Message_Registration) GetProtectionBypassSecret() string {
	if x != nil {
		return x.ProtectionBypassSecret
	}
	return ""
}

var File_bridge_v1_bridge_proto protoreflect.FileDescriptor

const file_bridge_v1_bridge_proto_rawDesc = "" +
	"\n" +
	"\x16bridge/v1/bridge.proto\x12\tbridge.v1\"\\\n" +
	"\x10ServerConnection\x12 \n" +
	"\vsandbox_url\x18\x01 \x01(\tR\vsandbox_url\x12&\n" +
	"\x0econnection_key\x18\x02 \x01(\tR\x0econnection_key\"\xa7\x06\n" +
	"\aMessage\x12H\n" +
	"\fregistration\x18\x01 \x01(\v2\x1f.bridge.v1.Message.RegistrationH\x00R\fregistration\x88\x01\x01\x122\n" +
	"\x06source\x18\x02 \x01(\v2\x1a.bridge.v1.Message.AddressR\x06source\x12.\n" +
	"\x04dest\x18\x03 \x01(\v2\x1a.bridge.v1.Message.AddressR\x04dest\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12$\n" +
	"\rconnection_id\x18\x05 \x01(\tR\rconnection_id\x12\x14\n" +
	"\x05close\x18\x06 \x01(\bR\x05close\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12H\n" +
	"\vdns_request\x18\b \x01(\v2!.bridge.v1.ResolveDNSQueryRequestH\x01R\vdns_request\x88\x01\x01\x12K\n" +
	"\fdns_response\x18\t \x01(\v2\".bridge.v1.ResolveDNSQueryResponseH\x02R\fdns_response\x88\x01\x01\x1a-\n" +
	"\aAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x1a\xc5\x01\n" +
	"\fRegistration\x12\x1c\n" +
	"\tis_server\x18\x01 \x01(\bR\tis_server\x127\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x1b.bridge.v1.Message.ProtocolR\bprotocol\x12\"\n" +
	"\ffunction_url\x18\x03 \x01(\tR\ffunction_url\x12:\n" +
	"\x18protection_bypass_secret\x18\x04 \x01(\tR\x18protection_bypass_secret\"H\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x02B\x0f\n" +
	"\r_registrationB\x0e\n" +
	"\f_dns_requestB\x0f\n" +
	"\r_dns_response\"T\n" +
	"\x16ResolveDNSQueryRequest\x12\x1e\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\n" +
	"request_id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"m\n" +
	"\x17ResolveDNSQueryResponse\x12\x1e\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\n" +
	"request_id\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB\x9b\x01\n" +
	"\rcom.bridge.v1B\vBridgeProtoP\x01Z8github.com/vercel-eddie/bridge/api/go/bridge/v1;bridgev1\xa2\x02\x03BXX\xaa\x02\tBridge.V1\xca\x02\tBridge\\V1\xe2\x02\x15Bridge\\V1\\GPBMetadata\xea\x02\n" +
	"Bridge::V1b\x06proto3"

var (
	file_bridge_v1_bridge_proto_rawDescOnce sync.Once
	file_bridge_v1_bridge_proto_rawDescData []byte
)

func file_bridge_v1_bridge_proto_rawDescGZIP() []byte {
	file_bridge_v1_bridge_proto_rawDescOnce.Do(func() {
		file_bridge_v1_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_bridge_proto_rawDesc), len(file_bridge_v1_bridge_proto_rawDesc)))
	})
	return file_bridge_v1_bridge_proto_rawDescData
}

var file_bridge_v1_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_v1_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bridge_v1_bridge_proto_goTypes = []any{
	(Message_Protocol)(0),           // 0: bridge.v1.Message.Protocol
	(*ServerConnection)(nil),        // 1: bridge.v1.ServerConnection
	(*Message)(nil),                 // 2: bridge.v1.Message
	(*ResolveDNSQueryRequest)(nil),  // 3: bridge.v1.ResolveDNSQueryRequest
	(*ResolveDNSQueryResponse)(nil), // 4: bridge.v1.ResolveDNSQueryResponse
	(*Message_Address)(nil),         // 5: bridge.v1.Message.Address
	(*Message_Registration)(nil),    // 6: bridge.v1.Message.Registration
}
var file_bridge_v1_bridge_proto_depIdxs = []int32{
	6, // 0: bridge.v1.Message.registration:type_name -> bridge.v1.Message.Registration
	5, // 1: bridge.v1.Message.source:type_name -> bridge.v1.Message.Address
	5, // 2: bridge.v1.Message.dest:type_name -> bridge.v1.Message.Address
	3, // 3: bridge.v1.Message.dns_request:type_name -> bridge.v1.ResolveDNSQueryRequest
	4, // 4: bridge.v1.Message.dns_response:type_name -> bridge.v1.ResolveDNSQueryResponse
	0, // 5: bridge.v1.Message.Registration.protocol:type_name -> bridge.v1.Message.Protocol
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_bridge_v1_bridge_proto_init() }
func file_bridge_v1_bridge_proto_init() {
	if File_bridge_v1_bridge_proto != nil {
		return
	}
	file_bridge_v1_bridge_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_bridge_proto_rawDesc), len(file_bridge_v1_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_v1_bridge_proto_goTypes,
		DependencyIndexes: file_bridge_v1_bridge_proto_depIdxs,
		EnumInfos:         file_bridge_v1_bridge_proto_enumTypes,
		MessageInfos:      file_bridge_v1_bridge_proto_msgTypes,
	}.Build()
	File_bridge_v1_bridge_proto = out.File
	file_bridge_v1_bridge_proto_goTypes = nil
	file_bridge_v1_bridge_proto_depIdxs = nil
}
