// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge/v1/command.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// buf:lint:ignore ENUM_VALUE_PREFIX
// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
type CommandResultOutcome_Enum int32

const (
	CommandResultOutcome_unspecified CommandResultOutcome_Enum = 0
	CommandResultOutcome_success     CommandResultOutcome_Enum = 1
	CommandResultOutcome_error       CommandResultOutcome_Enum = 2
)

// Enum value maps for CommandResultOutcome_Enum.
var (
	CommandResultOutcome_Enum_name = map[int32]string{
		0: "unspecified",
		1: "success",
		2: "error",
	}
	CommandResultOutcome_Enum_value = map[string]int32{
		"unspecified": 0,
		"success":     1,
		"error":       2,
	}
)

func (x CommandResultOutcome_Enum) Enum() *CommandResultOutcome_Enum {
	p := new(CommandResultOutcome_Enum)
	*p = x
	return p
}

func (x CommandResultOutcome_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandResultOutcome_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_v1_command_proto_enumTypes[0].Descriptor()
}

func (CommandResultOutcome_Enum) Type() protoreflect.EnumType {
	return &file_bridge_v1_command_proto_enumTypes[0]
}

func (x CommandResultOutcome_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandResultOutcome_Enum.Descriptor instead.
func (CommandResultOutcome_Enum) EnumDescriptor() ([]byte, []int) {
	return file_bridge_v1_command_proto_rawDescGZIP(), []int{0, 0}
}

// CommandResultOutcome wraps the outcome enum so values serialize as
// "success" and "error" without a package prefix.
type CommandResultOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResultOutcome) Reset() {
	*x = CommandResultOutcome{}
	mi := &file_bridge_v1_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResultOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResultOutcome) ProtoMessage() {}

func (x *CommandResultOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResultOutcome.ProtoReflect.Descriptor instead.
func (*CommandResultOutcome) Descriptor() ([]byte, []int) {
	return file_bridge_v1_command_proto_rawDescGZIP(), []int{0}
}

// CommandResult is the envelope for all JSON-mode command output.
// On success, response contains the command-specific payload.
// On failure, error contains the error message.
type CommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the command succeeded or failed.
	Outcome CommandResultOutcome_Enum `protobuf:"varint,1,opt,name=outcome,proto3,enum=bridge.v1.CommandResultOutcome_Enum" json:"outcome,omitempty"`
	// Error message. Absent on success.
	Error *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// Command-specific response payload. Absent on error.
	Response      *structpb.Value `protobuf:"bytes,3,opt,name=response,proto3,oneof" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_bridge_v1_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_bridge_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResult) GetOutcome() CommandResultOutcome_Enum {
	if x != nil {
		return x.Outcome
	}
	return CommandResultOutcome_unspecified
}

func (x *CommandResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *CommandResult) GetResponse() *structpb.Value {
	if x != nil {
		return x.Response
	}
	return nil
}

// CreateCommandPayload represents the flags for the "create" command.
// Used both as the CEL evaluation context and as the flag values to apply.
type CreateCommandPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Positional argument: name of the target workload (defaults to a Deployment).
	WorkloadName string `protobuf:"bytes,1,opt,name=workload_name,proto3" json:"workload_name,omitempty"`
	// --namespace / -n: target namespace of the source deployment.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// --server-facade: server facade specs (JSON string or file path). Repeated.
	ServerFacades []string `protobuf:"bytes,3,rep,name=server_facades,proto3" json:"server_facades,omitempty"`
	// --source / -s: path to Kubernetes manifests (folder, glob, or YAML file).
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// --listen / -l: port the app listens on.
	Listen int32 `protobuf:"varint,5,opt,name=listen,proto3" json:"listen,omitempty"`
	// --connect / -c: start the devcontainer and exec into it after creation.
	Connect bool `protobuf:"varint,6,opt,name=connect,proto3" json:"connect,omitempty"`
	// --devcontainer-config / -f: path to a base devcontainer.json to extend.
	DevcontainerConfig string `protobuf:"bytes,7,opt,name=devcontainer_config,proto3" json:"devcontainer_config,omitempty"`
	// --devcontainer-up-args: additional arguments passed to devcontainer up.
	DevcontainerUpArgs string `protobuf:"bytes,8,opt,name=devcontainer_up_args,proto3" json:"devcontainer_up_args,omitempty"`
	// --name: bridge name (defaults to workload_name).
	Name          string `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommandPayload) Reset() {
	*x = CreateCommandPayload{}
	mi := &file_bridge_v1_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandPayload) ProtoMessage() {}

func (x *CreateCommandPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandPayload.ProtoReflect.Descriptor instead.
func (*CreateCommandPayload) Descriptor() ([]byte, []int) {
	return file_bridge_v1_command_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommandPayload) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *CreateCommandPayload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateCommandPayload) GetServerFacades() []string {
	if x != nil {
		return x.ServerFacades
	}
	return nil
}

func (x *CreateCommandPayload) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateCommandPayload) GetListen() int32 {
	if x != nil {
		return x.Listen
	}
	return 0
}

func (x *CreateCommandPayload) GetConnect() bool {
	if x != nil {
		return x.Connect
	}
	return false
}

func (x *CreateCommandPayload) GetDevcontainerConfig() string {
	if x != nil {
		return x.DevcontainerConfig
	}
	return ""
}

func (x *CreateCommandPayload) GetDevcontainerUpArgs() string {
	if x != nil {
		return x.DevcontainerUpArgs
	}
	return ""
}

func (x *CreateCommandPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreateCommandResponse is the structured output emitted by the "create"
// command when running in agent mode without --connect.
type CreateCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The container port the application listens on.
	AppPort int32 `protobuf:"varint,1,opt,name=app_port,proto3" json:"app_port,omitempty"`
	// The resolved host port mapped to the app port (may differ if the
	// requested port was already in use).
	HostAppPort int32 `protobuf:"varint,6,opt,name=host_app_port,proto3" json:"host_app_port,omitempty"`
	// Absolute path to the generated devcontainer.json.
	DevcontainerConfigPath string `protobuf:"bytes,2,opt,name=devcontainer_config_path,proto3" json:"devcontainer_config_path,omitempty"`
	// The bridge name.
	BridgeName string `protobuf:"bytes,3,opt,name=bridge_name,proto3" json:"bridge_name,omitempty"`
	// The source deployment name.
	SourceDeployment string `protobuf:"bytes,4,opt,name=source_deployment,proto3" json:"source_deployment,omitempty"`
	// Port mappings: key is the label (e.g. "app", "intercept"), value is the port number.
	Ports         map[string]int32 `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommandResponse) Reset() {
	*x = CreateCommandResponse{}
	mi := &file_bridge_v1_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandResponse) ProtoMessage() {}

func (x *CreateCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandResponse.ProtoReflect.Descriptor instead.
func (*CreateCommandResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_command_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCommandResponse) GetAppPort() int32 {
	if x != nil {
		return x.AppPort
	}
	return 0
}

func (x *CreateCommandResponse) GetHostAppPort() int32 {
	if x != nil {
		return x.HostAppPort
	}
	return 0
}

func (x *CreateCommandResponse) GetDevcontainerConfigPath() string {
	if x != nil {
		return x.DevcontainerConfigPath
	}
	return ""
}

func (x *CreateCommandResponse) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

func (x *CreateCommandResponse) GetSourceDeployment() string {
	if x != nil {
		return x.SourceDeployment
	}
	return ""
}

func (x *CreateCommandResponse) GetPorts() map[string]int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

// GetCommandResponseBridge describes a single bridge in the get command output.
type GetCommandResponseBridge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bridge name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The source deployment this bridge was cloned from.
	SourceDeployment string `protobuf:"bytes,2,opt,name=source_deployment,proto3" json:"source_deployment,omitempty"`
	// The source namespace of the deployment.
	SourceNamespace string `protobuf:"bytes,3,opt,name=source_namespace,proto3" json:"source_namespace,omitempty"`
	// The namespace where the bridge is running.
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// When the bridge was created (RFC 3339).
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	// Current status of the bridge.
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// The name of the bridge Deployment.
	DeploymentName string `protobuf:"bytes,7,opt,name=deployment_name,proto3" json:"deployment_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCommandResponseBridge) Reset() {
	*x = GetCommandResponseBridge{}
	mi := &file_bridge_v1_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandResponseBridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandResponseBridge) ProtoMessage() {}

func (x *GetCommandResponseBridge) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandResponseBridge.ProtoReflect.Descriptor instead.
func (*GetCommandResponseBridge) Descriptor() ([]byte, []int) {
	return file_bridge_v1_command_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommandResponseBridge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCommandResponseBridge) GetSourceDeployment() string {
	if x != nil {
		return x.SourceDeployment
	}
	return ""
}

func (x *GetCommandResponseBridge) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *GetCommandResponseBridge) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetCommandResponseBridge) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetCommandResponseBridge) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetCommandResponseBridge) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

// GetCommandResponse is the structured output emitted by the "get" command
// when running in JSON output mode.
type GetCommandResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Bridges       []*GetCommandResponseBridge `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandResponse) Reset() {
	*x = GetCommandResponse{}
	mi := &file_bridge_v1_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandResponse) ProtoMessage() {}

func (x *GetCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandResponse.ProtoReflect.Descriptor instead.
func (*GetCommandResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_command_proto_rawDescGZIP(), []int{5}
}

func (x *GetCommandResponse) GetBridges() []*GetCommandResponseBridge {
	if x != nil {
		return x.Bridges
	}
	return nil
}

// RemoveCommandResponse is the structured output emitted by the "remove"
// command when running in JSON output mode.
type RemoveCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Names of bridges that were successfully removed.
	Removed       []string `protobuf:"bytes,1,rep,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCommandResponse) Reset() {
	*x = RemoveCommandResponse{}
	mi := &file_bridge_v1_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCommandResponse) ProtoMessage() {}

func (x *RemoveCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCommandResponse.ProtoReflect.Descriptor instead.
func (*RemoveCommandResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_command_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveCommandResponse) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

var File_bridge_v1_command_proto protoreflect.FileDescriptor

const file_bridge_v1_command_proto_rawDesc = "" +
	"\n" +
	"\x17bridge/v1/command.proto\x12\tbridge.v1\x1a\x1cgoogle/protobuf/struct.proto\"G\n" +
	"\x14CommandResultOutcome\"/\n" +
	"\x04Enum\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\v\n" +
	"\asuccess\x10\x01\x12\t\n" +
	"\x05error\x10\x02\"\xba\x01\n" +
	"\rCommandResult\x12>\n" +
	"\aoutcome\x18\x01 \x01(\x0e2$.bridge.v1.CommandResultOutcome.EnumR\aoutcome\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x127\n" +
	"\bresponse\x18\x03 \x01(\v2\x16.google.protobuf.ValueH\x01R\bresponse\x88\x01\x01B\b\n" +
	"\x06_errorB\v\n" +
	"\t_response\"\xc6\x02\n" +
	"\x14CreateCommandPayload\x12$\n" +
	"\rworkload_name\x18\x01 \x01(\tR\rworkload_name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12&\n" +
	"\x0eserver_facades\x18\x03 \x03(\tR\x0eserver_facades\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06listen\x18\x05 \x01(\x05R\x06listen\x12\x18\n" +
	"\aconnect\x18\x06 \x01(\bR\aconnect\x120\n" +
	"\x13devcontainer_config\x18\a \x01(\tR\x13devcontainer_config\x122\n" +
	"\x14devcontainer_up_args\x18\b \x01(\tR\x14devcontainer_up_args\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\"\xe2\x02\n" +
	"\x15CreateCommandResponse\x12\x1a\n" +
	"\bapp_port\x18\x01 \x01(\x05R\bapp_port\x12$\n" +
	"\rhost_app_port\x18\x06 \x01(\x05R\rhost_app_port\x12:\n" +
	"\x18devcontainer_config_path\x18\x02 \x01(\tR\x18devcontainer_config_path\x12 \n" +
	"\vbridge_name\x18\x03 \x01(\tR\vbridge_name\x12,\n" +
	"\x11source_deployment\x18\x04 \x01(\tR\x11source_deployment\x12A\n" +
	"\x05ports\x18\x05 \x03(\v2+.bridge.v1.CreateCommandResponse.PortsEntryR\x05ports\x1a8\n" +
	"\n" +
	"PortsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x88\x02\n" +
	"\x18GetCommandResponseBridge\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x11source_deployment\x18\x02 \x01(\tR\x11source_deployment\x12*\n" +
	"\x10source_namespace\x18\x03 \x01(\tR\x10source_namespace\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\n" +
	"created_at\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12(\n" +
	"\x0fdeployment_name\x18\a \x01(\tR\x0fdeployment_name\"S\n" +
	"\x12GetCommandResponse\x12=\n" +
	"\abridges\x18\x01 \x03(\v2#.bridge.v1.GetCommandResponseBridgeR\abridges\"1\n" +
	"\x15RemoveCommandResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x03(\tR\aremovedB\x96\x01\n" +
	"\rcom.bridge.v1B\fCommandProtoP\x01Z2github.com/vercel/bridge/api/go/bridge/v1;bridgev1\xa2\x02\x03BXX\xaa\x02\tBridge.V1\xca\x02\tBridge\\V1\xe2\x02\x15Bridge\\V1\\GPBMetadata\xea\x02\n" +
	"Bridge::V1b\x06proto3"

var (
	file_bridge_v1_command_proto_rawDescOnce sync.Once
	file_bridge_v1_command_proto_rawDescData []byte
)

func file_bridge_v1_command_proto_rawDescGZIP() []byte {
	file_bridge_v1_command_proto_rawDescOnce.Do(func() {
		file_bridge_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_command_proto_rawDesc), len(file_bridge_v1_command_proto_rawDesc)))
	})
	return file_bridge_v1_command_proto_rawDescData
}

var file_bridge_v1_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bridge_v1_command_proto_goTypes = []any{
	(CommandResultOutcome_Enum)(0),   // 0: bridge.v1.CommandResultOutcome.Enum
	(*CommandResultOutcome)(nil),     // 1: bridge.v1.CommandResultOutcome
	(*CommandResult)(nil),            // 2: bridge.v1.CommandResult
	(*CreateCommandPayload)(nil),     // 3: bridge.v1.CreateCommandPayload
	(*CreateCommandResponse)(nil),    // 4: bridge.v1.CreateCommandResponse
	(*GetCommandResponseBridge)(nil), // 5: bridge.v1.GetCommandResponseBridge
	(*GetCommandResponse)(nil),       // 6: bridge.v1.GetCommandResponse
	(*RemoveCommandResponse)(nil),    // 7: bridge.v1.RemoveCommandResponse
	nil,                              // 8: bridge.v1.CreateCommandResponse.PortsEntry
	(*structpb.Value)(nil),           // 9: google.protobuf.Value
}
var file_bridge_v1_command_proto_depIdxs = []int32{
	0, // 0: bridge.v1.CommandResult.outcome:type_name -> bridge.v1.CommandResultOutcome.Enum
	9, // 1: bridge.v1.CommandResult.response:type_name -> google.protobuf.Value
	8, // 2: bridge.v1.CreateCommandResponse.ports:type_name -> bridge.v1.CreateCommandResponse.PortsEntry
	5, // 3: bridge.v1.GetCommandResponse.bridges:type_name -> bridge.v1.GetCommandResponseBridge
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bridge_v1_command_proto_init() }
func file_bridge_v1_command_proto_init() {
	if File_bridge_v1_command_proto != nil {
		return
	}
	file_bridge_v1_command_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_command_proto_rawDesc), len(file_bridge_v1_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_v1_command_proto_goTypes,
		DependencyIndexes: file_bridge_v1_command_proto_depIdxs,
		EnumInfos:         file_bridge_v1_command_proto_enumTypes,
		MessageInfos:      file_bridge_v1_command_proto_msgTypes,
	}.Build()
	File_bridge_v1_command_proto = out.File
	file_bridge_v1_command_proto_goTypes = nil
	file_bridge_v1_command_proto_depIdxs = nil
}
