// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge/v1/filesystem.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileType matches POSIX file type bits.
type FileType int32

const (
	FileType_FILE_TYPE_UNSPECIFIED FileType = 0
	FileType_FILE_TYPE_REGULAR     FileType = 1
	FileType_FILE_TYPE_DIR         FileType = 2
	FileType_FILE_TYPE_SYMLINK     FileType = 3
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE_TYPE_UNSPECIFIED",
		1: "FILE_TYPE_REGULAR",
		2: "FILE_TYPE_DIR",
		3: "FILE_TYPE_SYMLINK",
	}
	FileType_value = map[string]int32{
		"FILE_TYPE_UNSPECIFIED": 0,
		"FILE_TYPE_REGULAR":     1,
		"FILE_TYPE_DIR":         2,
		"FILE_TYPE_SYMLINK":     3,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_v1_filesystem_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_bridge_v1_filesystem_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{0}
}

// FileAttr describes a single inode.
type FileAttr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// POSIX mode (permission bits + type). Only the low 12 bits are meaningful
	// for permissions; the type is reported separately via the type field.
	Mode uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// File size in bytes (0 for non-regular files).
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Modification time as Unix seconds.
	ModTime int64 `protobuf:"varint,3,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	// File type.
	Type          FileType `protobuf:"varint,4,opt,name=type,proto3,enum=bridge.v1.FileType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAttr) Reset() {
	*x = FileAttr{}
	mi := &file_bridge_v1_filesystem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttr) ProtoMessage() {}

func (x *FileAttr) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_filesystem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttr.ProtoReflect.Descriptor instead.
func (*FileAttr) Descriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{0}
}

func (x *FileAttr) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileAttr) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileAttr) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *FileAttr) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_bridge_v1_filesystem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_filesystem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{1}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *FileAttr              `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_bridge_v1_filesystem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_filesystem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{2}
}

func (x *StatResponse) GetAttr() *FileAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type ReadDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirRequest) Reset() {
	*x = ReadDirRequest{}
	mi := &file_bridge_v1_filesystem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirRequest) ProtoMessage() {}

func (x *ReadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_filesystem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirRequest.ProtoReflect.Descriptor instead.
func (*ReadDirRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{3}
}

func (x *ReadDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FileType               `protobuf:"varint,2,opt,name=type,proto3,enum=bridge.v1.FileType" json:"type,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_bridge_v1_filesystem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_filesystem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{4}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *DirEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ReadDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirResponse) Reset() {
	*x = ReadDirResponse{}
	mi := &file_bridge_v1_filesystem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirResponse) ProtoMessage() {}

func (x *ReadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_filesystem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirResponse.ProtoReflect.Descriptor instead.
func (*ReadDirResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{5}
}

func (x *ReadDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Byte offset to start reading at.
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Maximum number of bytes to read. Server may return fewer at EOF.
	Size          int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_bridge_v1_filesystem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_filesystem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ReadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// True when offset+len(data) reaches the end of the file.
	Eof           bool `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_bridge_v1_filesystem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_filesystem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{7}
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadFileResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type ReadLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLinkRequest) Reset() {
	*x = ReadLinkRequest{}
	mi := &file_bridge_v1_filesystem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLinkRequest) ProtoMessage() {}

func (x *ReadLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_filesystem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLinkRequest.ProtoReflect.Descriptor instead.
func (*ReadLinkRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{8}
}

func (x *ReadLinkRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLinkResponse) Reset() {
	*x = ReadLinkResponse{}
	mi := &file_bridge_v1_filesystem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLinkResponse) ProtoMessage() {}

func (x *ReadLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_filesystem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLinkResponse.ProtoReflect.Descriptor instead.
func (*ReadLinkResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_filesystem_proto_rawDescGZIP(), []int{9}
}

func (x *ReadLinkResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_bridge_v1_filesystem_proto protoreflect.FileDescriptor

const file_bridge_v1_filesystem_proto_rawDesc = "" +
	"\n" +
	"\x1abridge/v1/filesystem.proto\x12\tbridge.v1\"v\n" +
	"\bFileAttr\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x03 \x01(\x03R\amodTime\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.bridge.v1.FileTypeR\x04type\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"7\n" +
	"\fStatResponse\x12'\n" +
	"\x04attr\x18\x01 \x01(\v2\x13.bridge.v1.FileAttrR\x04attr\"$\n" +
	"\x0eReadDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"[\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.bridge.v1.FileTypeR\x04type\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"@\n" +
	"\x0fReadDirResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.bridge.v1.DirEntryR\aentries\"Q\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"8\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"%\n" +
	"\x0fReadLinkRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"*\n" +
	"\x10ReadLinkResponse\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target*f\n" +
	"\bFileType\x12\x19\n" +
	"\x15FILE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FILE_TYPE_REGULAR\x10\x01\x12\x11\n" +
	"\rFILE_TYPE_DIR\x10\x02\x12\x15\n" +
	"\x11FILE_TYPE_SYMLINK\x10\x032\x9e\x02\n" +
	"\x17BridgeFileSystemService\x127\n" +
	"\x04Stat\x12\x16.bridge.v1.StatRequest\x1a\x17.bridge.v1.StatResponse\x12@\n" +
	"\aReadDir\x12\x19.bridge.v1.ReadDirRequest\x1a\x1a.bridge.v1.ReadDirResponse\x12C\n" +
	"\bReadFile\x12\x1a.bridge.v1.ReadFileRequest\x1a\x1b.bridge.v1.ReadFileResponse\x12C\n" +
	"\bReadLink\x12\x1a.bridge.v1.ReadLinkRequest\x1a\x1b.bridge.v1.ReadLinkResponseB\x99\x01\n" +
	"\rcom.bridge.v1B\x0fFilesystemProtoP\x01Z2github.com/vercel/bridge/api/go/bridge/v1;bridgev1\xa2\x02\x03BXX\xaa\x02\tBridge.V1\xca\x02\tBridge\\V1\xe2\x02\x15Bridge\\V1\\GPBMetadata\xea\x02\n" +
	"Bridge::V1b\x06proto3"

var (
	file_bridge_v1_filesystem_proto_rawDescOnce sync.Once
	file_bridge_v1_filesystem_proto_rawDescData []byte
)

func file_bridge_v1_filesystem_proto_rawDescGZIP() []byte {
	file_bridge_v1_filesystem_proto_rawDescOnce.Do(func() {
		file_bridge_v1_filesystem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_filesystem_proto_rawDesc), len(file_bridge_v1_filesystem_proto_rawDesc)))
	})
	return file_bridge_v1_filesystem_proto_rawDescData
}

var file_bridge_v1_filesystem_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_v1_filesystem_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bridge_v1_filesystem_proto_goTypes = []any{
	(FileType)(0),            // 0: bridge.v1.FileType
	(*FileAttr)(nil),         // 1: bridge.v1.FileAttr
	(*StatRequest)(nil),      // 2: bridge.v1.StatRequest
	(*StatResponse)(nil),     // 3: bridge.v1.StatResponse
	(*ReadDirRequest)(nil),   // 4: bridge.v1.ReadDirRequest
	(*DirEntry)(nil),         // 5: bridge.v1.DirEntry
	(*ReadDirResponse)(nil),  // 6: bridge.v1.ReadDirResponse
	(*ReadFileRequest)(nil),  // 7: bridge.v1.ReadFileRequest
	(*ReadFileResponse)(nil), // 8: bridge.v1.ReadFileResponse
	(*ReadLinkRequest)(nil),  // 9: bridge.v1.ReadLinkRequest
	(*ReadLinkResponse)(nil), // 10: bridge.v1.ReadLinkResponse
}
var file_bridge_v1_filesystem_proto_depIdxs = []int32{
	0,  // 0: bridge.v1.FileAttr.type:type_name -> bridge.v1.FileType
	1,  // 1: bridge.v1.StatResponse.attr:type_name -> bridge.v1.FileAttr
	0,  // 2: bridge.v1.DirEntry.type:type_name -> bridge.v1.FileType
	5,  // 3: bridge.v1.ReadDirResponse.entries:type_name -> bridge.v1.DirEntry
	2,  // 4: bridge.v1.BridgeFileSystemService.Stat:input_type -> bridge.v1.StatRequest
	4,  // 5: bridge.v1.BridgeFileSystemService.ReadDir:input_type -> bridge.v1.ReadDirRequest
	7,  // 6: bridge.v1.BridgeFileSystemService.ReadFile:input_type -> bridge.v1.ReadFileRequest
	9,  // 7: bridge.v1.BridgeFileSystemService.ReadLink:input_type -> bridge.v1.ReadLinkRequest
	3,  // 8: bridge.v1.BridgeFileSystemService.Stat:output_type -> bridge.v1.StatResponse
	6,  // 9: bridge.v1.BridgeFileSystemService.ReadDir:output_type -> bridge.v1.ReadDirResponse
	8,  // 10: bridge.v1.BridgeFileSystemService.ReadFile:output_type -> bridge.v1.ReadFileResponse
	10, // 11: bridge.v1.BridgeFileSystemService.ReadLink:output_type -> bridge.v1.ReadLinkResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_bridge_v1_filesystem_proto_init() }
func file_bridge_v1_filesystem_proto_init() {
	if File_bridge_v1_filesystem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_filesystem_proto_rawDesc), len(file_bridge_v1_filesystem_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_v1_filesystem_proto_goTypes,
		DependencyIndexes: file_bridge_v1_filesystem_proto_depIdxs,
		EnumInfos:         file_bridge_v1_filesystem_proto_enumTypes,
		MessageInfos:      file_bridge_v1_filesystem_proto_msgTypes,
	}.Build()
	File_bridge_v1_filesystem_proto = out.File
	file_bridge_v1_filesystem_proto_goTypes = nil
	file_bridge_v1_filesystem_proto_depIdxs = nil
}
