// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: bridge/v1/filesystem.proto

package bridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BridgeFileSystemService_Stat_FullMethodName     = "/bridge.v1.BridgeFileSystemService/Stat"
	BridgeFileSystemService_ReadDir_FullMethodName  = "/bridge.v1.BridgeFileSystemService/ReadDir"
	BridgeFileSystemService_ReadFile_FullMethodName = "/bridge.v1.BridgeFileSystemService/ReadFile"
	BridgeFileSystemService_ReadLink_FullMethodName = "/bridge.v1.BridgeFileSystemService/ReadLink"
)

// BridgeFileSystemServiceClient is the client API for BridgeFileSystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BridgeFileSystemService serves a read-only view of allowed paths on the
// bridge proxy pod so the local devcontainer can FUSE-mount them. Operations
// are stateless: each RPC takes an absolute path and the server enforces an
// allowlist of mount roots configured at startup.
type BridgeFileSystemServiceClient interface {
	// Stat returns metadata for a single path.
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// ReadDir lists entries in a directory.
	ReadDir(ctx context.Context, in *ReadDirRequest, opts ...grpc.CallOption) (*ReadDirResponse, error)
	// ReadFile reads a byte range of a regular file. Clients chunk large reads
	// by issuing multiple requests with successive offsets.
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	// ReadLink returns the target of a symbolic link.
	ReadLink(ctx context.Context, in *ReadLinkRequest, opts ...grpc.CallOption) (*ReadLinkResponse, error)
}

type bridgeFileSystemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeFileSystemServiceClient(cc grpc.ClientConnInterface) BridgeFileSystemServiceClient {
	return &bridgeFileSystemServiceClient{cc}
}

func (c *bridgeFileSystemServiceClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, BridgeFileSystemService_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeFileSystemServiceClient) ReadDir(ctx context.Context, in *ReadDirRequest, opts ...grpc.CallOption) (*ReadDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadDirResponse)
	err := c.cc.Invoke(ctx, BridgeFileSystemService_ReadDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeFileSystemServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, BridgeFileSystemService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeFileSystemServiceClient) ReadLink(ctx context.Context, in *ReadLinkRequest, opts ...grpc.CallOption) (*ReadLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadLinkResponse)
	err := c.cc.Invoke(ctx, BridgeFileSystemService_ReadLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeFileSystemServiceServer is the server API for BridgeFileSystemService service.
// All implementations must embed UnimplementedBridgeFileSystemServiceServer
// for forward compatibility.
//
// BridgeFileSystemService serves a read-only view of allowed paths on the
// bridge proxy pod so the local devcontainer can FUSE-mount them. Operations
// are stateless: each RPC takes an absolute path and the server enforces an
// allowlist of mount roots configured at startup.
type BridgeFileSystemServiceServer interface {
	// Stat returns metadata for a single path.
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	// ReadDir lists entries in a directory.
	ReadDir(context.Context, *ReadDirRequest) (*ReadDirResponse, error)
	// ReadFile reads a byte range of a regular file. Clients chunk large reads
	// by issuing multiple requests with successive offsets.
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	// ReadLink returns the target of a symbolic link.
	ReadLink(context.Context, *ReadLinkRequest) (*ReadLinkResponse, error)
	mustEmbedUnimplementedBridgeFileSystemServiceServer()
}

// UnimplementedBridgeFileSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBridgeFileSystemServiceServer struct{}

func (UnimplementedBridgeFileSystemServiceServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedBridgeFileSystemServiceServer) ReadDir(context.Context, *ReadDirRequest) (*ReadDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadDir not implemented")
}
func (UnimplementedBridgeFileSystemServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedBridgeFileSystemServiceServer) ReadLink(context.Context, *ReadLinkRequest) (*ReadLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadLink not implemented")
}
func (UnimplementedBridgeFileSystemServiceServer) mustEmbedUnimplementedBridgeFileSystemServiceServer() {
}
func (UnimplementedBridgeFileSystemServiceServer) testEmbeddedByValue() {}

// UnsafeBridgeFileSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeFileSystemServiceServer will
// result in compilation errors.
type UnsafeBridgeFileSystemServiceServer interface {
	mustEmbedUnimplementedBridgeFileSystemServiceServer()
}

func RegisterBridgeFileSystemServiceServer(s grpc.ServiceRegistrar, srv BridgeFileSystemServiceServer) {
	// If the following call panics, it indicates UnimplementedBridgeFileSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BridgeFileSystemService_ServiceDesc, srv)
}

func _BridgeFileSystemService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeFileSystemServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeFileSystemService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeFileSystemServiceServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeFileSystemService_ReadDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeFileSystemServiceServer).ReadDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeFileSystemService_ReadDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeFileSystemServiceServer).ReadDir(ctx, req.(*ReadDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeFileSystemService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeFileSystemServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeFileSystemService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeFileSystemServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeFileSystemService_ReadLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeFileSystemServiceServer).ReadLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeFileSystemService_ReadLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeFileSystemServiceServer).ReadLink(ctx, req.(*ReadLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BridgeFileSystemService_ServiceDesc is the grpc.ServiceDesc for BridgeFileSystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgeFileSystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.v1.BridgeFileSystemService",
	HandlerType: (*BridgeFileSystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _BridgeFileSystemService_Stat_Handler,
		},
		{
			MethodName: "ReadDir",
			Handler:    _BridgeFileSystemService_ReadDir_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _BridgeFileSystemService_ReadFile_Handler,
		},
		{
			MethodName: "ReadLink",
			Handler:    _BridgeFileSystemService_ReadLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge/v1/filesystem.proto",
}
