// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: bridge/v1/interceptor.proto

package bridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterceptorService_GetStatus_FullMethodName = "/bridge.v1.InterceptorService/GetStatus"
)

// InterceptorServiceClient is the client API for InterceptorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InterceptorService runs inside the devcontainer and reports the current
// state of the local intercept process — initialization, tunnel health, and
// live results of the source deployment's probes against the developer's
// local app.
type InterceptorServiceClient interface {
	// GetStatus returns the current state of the intercept process. Safe to
	// call repeatedly; the response is built from cached probe results and
	// does not trigger fresh probe runs.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type interceptorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterceptorServiceClient(cc grpc.ClientConnInterface) InterceptorServiceClient {
	return &interceptorServiceClient{cc}
}

func (c *interceptorServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, InterceptorService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterceptorServiceServer is the server API for InterceptorService service.
// All implementations must embed UnimplementedInterceptorServiceServer
// for forward compatibility.
//
// InterceptorService runs inside the devcontainer and reports the current
// state of the local intercept process — initialization, tunnel health, and
// live results of the source deployment's probes against the developer's
// local app.
type InterceptorServiceServer interface {
	// GetStatus returns the current state of the intercept process. Safe to
	// call repeatedly; the response is built from cached probe results and
	// does not trigger fresh probe runs.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	mustEmbedUnimplementedInterceptorServiceServer()
}

// UnimplementedInterceptorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterceptorServiceServer struct{}

func (UnimplementedInterceptorServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedInterceptorServiceServer) mustEmbedUnimplementedInterceptorServiceServer() {}
func (UnimplementedInterceptorServiceServer) testEmbeddedByValue()                            {}

// UnsafeInterceptorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterceptorServiceServer will
// result in compilation errors.
type UnsafeInterceptorServiceServer interface {
	mustEmbedUnimplementedInterceptorServiceServer()
}

func RegisterInterceptorServiceServer(s grpc.ServiceRegistrar, srv InterceptorServiceServer) {
	// If the following call panics, it indicates UnimplementedInterceptorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterceptorService_ServiceDesc, srv)
}

func _InterceptorService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptorServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptorService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptorServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterceptorService_ServiceDesc is the grpc.ServiceDesc for InterceptorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterceptorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.v1.InterceptorService",
	HandlerType: (*InterceptorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _InterceptorService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge/v1/interceptor.proto",
}
