// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge/v1/interceptor.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeHealth int32

const (
	ProbeHealth_PROBE_HEALTH_UNSPECIFIED ProbeHealth = 0
	// Probe has not yet run a check.
	ProbeHealth_PROBE_HEALTH_PENDING ProbeHealth = 1
	// Last check passed and the configured success_threshold has been met.
	ProbeHealth_PROBE_HEALTH_HEALTHY ProbeHealth = 2
	// Probe has been failing — failure_threshold consecutive failures.
	ProbeHealth_PROBE_HEALTH_UNHEALTHY ProbeHealth = 3
)

// Enum value maps for ProbeHealth.
var (
	ProbeHealth_name = map[int32]string{
		0: "PROBE_HEALTH_UNSPECIFIED",
		1: "PROBE_HEALTH_PENDING",
		2: "PROBE_HEALTH_HEALTHY",
		3: "PROBE_HEALTH_UNHEALTHY",
	}
	ProbeHealth_value = map[string]int32{
		"PROBE_HEALTH_UNSPECIFIED": 0,
		"PROBE_HEALTH_PENDING":     1,
		"PROBE_HEALTH_HEALTHY":     2,
		"PROBE_HEALTH_UNHEALTHY":   3,
	}
)

func (x ProbeHealth) Enum() *ProbeHealth {
	p := new(ProbeHealth)
	*p = x
	return p
}

func (x ProbeHealth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeHealth) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_v1_interceptor_proto_enumTypes[0].Descriptor()
}

func (ProbeHealth) Type() protoreflect.EnumType {
	return &file_bridge_v1_interceptor_proto_enumTypes[0]
}

func (x ProbeHealth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeHealth.Descriptor instead.
func (ProbeHealth) EnumDescriptor() ([]byte, []int) {
	return file_bridge_v1_interceptor_proto_rawDescGZIP(), []int{0}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_bridge_v1_interceptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_interceptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_interceptor_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True once the intercept has finished setup (DNS, iptables, tunnel) and
	// is forwarding traffic. Independent of the app's own health.
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Liveness probe result against the local app. Unset if no liveness
	// probe was configured on the source.
	Liveness *ProbeStatus `protobuf:"bytes,2,opt,name=liveness,proto3" json:"liveness,omitempty"`
	// Readiness probe result against the local app. Unset if no readiness
	// probe was configured on the source.
	Readiness *ProbeStatus `protobuf:"bytes,3,opt,name=readiness,proto3" json:"readiness,omitempty"`
	// Startup probe result against the local app. Unset if no startup
	// probe was configured on the source.
	Startup       *ProbeStatus `protobuf:"bytes,4,opt,name=startup,proto3" json:"startup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_bridge_v1_interceptor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_interceptor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_interceptor_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *GetStatusResponse) GetLiveness() *ProbeStatus {
	if x != nil {
		return x.Liveness
	}
	return nil
}

func (x *GetStatusResponse) GetReadiness() *ProbeStatus {
	if x != nil {
		return x.Readiness
	}
	return nil
}

func (x *GetStatusResponse) GetStartup() *ProbeStatus {
	if x != nil {
		return x.Startup
	}
	return nil
}

// ProbeStatus reflects the current health view from a single configured
// probe — what the source deployment's probe would have reported if it had
// been run against the developer's local app.
type ProbeStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProbeHealth summarises the latest result.
	Health ProbeHealth `protobuf:"varint,1,opt,name=health,proto3,enum=bridge.v1.ProbeHealth" json:"health,omitempty"`
	// Human-readable last result (e.g. "HTTP 200", "connection refused",
	// "exit status 1"). Empty before the first check completes.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Unix seconds of the most recent check. Zero before the first check.
	LastCheckUnixSeconds int64 `protobuf:"varint,3,opt,name=last_check_unix_seconds,proto3" json:"last_check_unix_seconds,omitempty"`
	// Consecutive successful checks since the last failure (or startup).
	ConsecutiveSuccesses int32 `protobuf:"varint,4,opt,name=consecutive_successes,proto3" json:"consecutive_successes,omitempty"`
	// Consecutive failed checks since the last success (or startup).
	ConsecutiveFailures int32 `protobuf:"varint,5,opt,name=consecutive_failures,proto3" json:"consecutive_failures,omitempty"`
	// Total checks executed since intercept startup.
	TotalChecks   int64 `protobuf:"varint,6,opt,name=total_checks,proto3" json:"total_checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeStatus) Reset() {
	*x = ProbeStatus{}
	mi := &file_bridge_v1_interceptor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeStatus) ProtoMessage() {}

func (x *ProbeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_interceptor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeStatus.ProtoReflect.Descriptor instead.
func (*ProbeStatus) Descriptor() ([]byte, []int) {
	return file_bridge_v1_interceptor_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeStatus) GetHealth() ProbeHealth {
	if x != nil {
		return x.Health
	}
	return ProbeHealth_PROBE_HEALTH_UNSPECIFIED
}

func (x *ProbeStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProbeStatus) GetLastCheckUnixSeconds() int64 {
	if x != nil {
		return x.LastCheckUnixSeconds
	}
	return 0
}

func (x *ProbeStatus) GetConsecutiveSuccesses() int32 {
	if x != nil {
		return x.ConsecutiveSuccesses
	}
	return 0
}

func (x *ProbeStatus) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *ProbeStatus) GetTotalChecks() int64 {
	if x != nil {
		return x.TotalChecks
	}
	return 0
}

type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_bridge_v1_interceptor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_interceptor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_interceptor_proto_rawDescGZIP(), []int{3}
}

// ProbeResponse reports the outcome of a synchronous run of each
// configured probe. Each field is unset when the corresponding probe is
// not configured on the source deployment.
type ProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liveness      *ProbeCheckResult      `protobuf:"bytes,1,opt,name=liveness,proto3" json:"liveness,omitempty"`
	Readiness     *ProbeCheckResult      `protobuf:"bytes,2,opt,name=readiness,proto3" json:"readiness,omitempty"`
	Startup       *ProbeCheckResult      `protobuf:"bytes,3,opt,name=startup,proto3" json:"startup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_bridge_v1_interceptor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_interceptor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_interceptor_proto_rawDescGZIP(), []int{4}
}

func (x *ProbeResponse) GetLiveness() *ProbeCheckResult {
	if x != nil {
		return x.Liveness
	}
	return nil
}

func (x *ProbeResponse) GetReadiness() *ProbeCheckResult {
	if x != nil {
		return x.Readiness
	}
	return nil
}

func (x *ProbeResponse) GetStartup() *ProbeCheckResult {
	if x != nil {
		return x.Startup
	}
	return nil
}

// ProbeCheckResult is the outcome of one synchronous probe check.
type ProbeCheckResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if this single check passed (HTTP 2xx/3xx, TCP open, gRPC
	// SERVING, or Exec exit 0).
	Passed bool `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	// Error message when passed=false. Empty on success.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Unix seconds when this check completed.
	CheckedAtUnixSeconds int64 `protobuf:"varint,3,opt,name=checked_at_unix_seconds,proto3" json:"checked_at_unix_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProbeCheckResult) Reset() {
	*x = ProbeCheckResult{}
	mi := &file_bridge_v1_interceptor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeCheckResult) ProtoMessage() {}

func (x *ProbeCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_interceptor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeCheckResult.ProtoReflect.Descriptor instead.
func (*ProbeCheckResult) Descriptor() ([]byte, []int) {
	return file_bridge_v1_interceptor_proto_rawDescGZIP(), []int{5}
}

func (x *ProbeCheckResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ProbeCheckResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProbeCheckResult) GetCheckedAtUnixSeconds() int64 {
	if x != nil {
		return x.CheckedAtUnixSeconds
	}
	return 0
}

var File_bridge_v1_interceptor_proto protoreflect.FileDescriptor

const file_bridge_v1_interceptor_proto_rawDesc = "" +
	"\n" +
	"\x1bbridge/v1/interceptor.proto\x12\tbridge.v1\"\x12\n" +
	"\x10GetStatusRequest\"\xc5\x01\n" +
	"\x11GetStatusResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x122\n" +
	"\bliveness\x18\x02 \x01(\v2\x16.bridge.v1.ProbeStatusR\bliveness\x124\n" +
	"\treadiness\x18\x03 \x01(\v2\x16.bridge.v1.ProbeStatusR\treadiness\x120\n" +
	"\astartup\x18\x04 \x01(\v2\x16.bridge.v1.ProbeStatusR\astartup\"\x9f\x02\n" +
	"\vProbeStatus\x12.\n" +
	"\x06health\x18\x01 \x01(\x0e2\x16.bridge.v1.ProbeHealthR\x06health\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\x17last_check_unix_seconds\x18\x03 \x01(\x03R\x17last_check_unix_seconds\x124\n" +
	"\x15consecutive_successes\x18\x04 \x01(\x05R\x15consecutive_successes\x122\n" +
	"\x14consecutive_failures\x18\x05 \x01(\x05R\x14consecutive_failures\x12\"\n" +
	"\ftotal_checks\x18\x06 \x01(\x03R\ftotal_checks\"\x0e\n" +
	"\fProbeRequest\"\xba\x01\n" +
	"\rProbeResponse\x127\n" +
	"\bliveness\x18\x01 \x01(\v2\x1b.bridge.v1.ProbeCheckResultR\bliveness\x129\n" +
	"\treadiness\x18\x02 \x01(\v2\x1b.bridge.v1.ProbeCheckResultR\treadiness\x125\n" +
	"\astartup\x18\x03 \x01(\v2\x1b.bridge.v1.ProbeCheckResultR\astartup\"z\n" +
	"\x10ProbeCheckResult\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x128\n" +
	"\x17checked_at_unix_seconds\x18\x03 \x01(\x03R\x17checked_at_unix_seconds*{\n" +
	"\vProbeHealth\x12\x1c\n" +
	"\x18PROBE_HEALTH_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROBE_HEALTH_PENDING\x10\x01\x12\x18\n" +
	"\x14PROBE_HEALTH_HEALTHY\x10\x02\x12\x1a\n" +
	"\x16PROBE_HEALTH_UNHEALTHY\x10\x032\x98\x01\n" +
	"\x12InterceptorService\x12F\n" +
	"\tGetStatus\x12\x1b.bridge.v1.GetStatusRequest\x1a\x1c.bridge.v1.GetStatusResponse\x12:\n" +
	"\x05Probe\x12\x17.bridge.v1.ProbeRequest\x1a\x18.bridge.v1.ProbeResponseB\x9a\x01\n" +
	"\rcom.bridge.v1B\x10InterceptorProtoP\x01Z2github.com/vercel/bridge/api/go/bridge/v1;bridgev1\xa2\x02\x03BXX\xaa\x02\tBridge.V1\xca\x02\tBridge\\V1\xe2\x02\x15Bridge\\V1\\GPBMetadata\xea\x02\n" +
	"Bridge::V1b\x06proto3"

var (
	file_bridge_v1_interceptor_proto_rawDescOnce sync.Once
	file_bridge_v1_interceptor_proto_rawDescData []byte
)

func file_bridge_v1_interceptor_proto_rawDescGZIP() []byte {
	file_bridge_v1_interceptor_proto_rawDescOnce.Do(func() {
		file_bridge_v1_interceptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_interceptor_proto_rawDesc), len(file_bridge_v1_interceptor_proto_rawDesc)))
	})
	return file_bridge_v1_interceptor_proto_rawDescData
}

var file_bridge_v1_interceptor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_v1_interceptor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bridge_v1_interceptor_proto_goTypes = []any{
	(ProbeHealth)(0),          // 0: bridge.v1.ProbeHealth
	(*GetStatusRequest)(nil),  // 1: bridge.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 2: bridge.v1.GetStatusResponse
	(*ProbeStatus)(nil),       // 3: bridge.v1.ProbeStatus
	(*ProbeRequest)(nil),      // 4: bridge.v1.ProbeRequest
	(*ProbeResponse)(nil),     // 5: bridge.v1.ProbeResponse
	(*ProbeCheckResult)(nil),  // 6: bridge.v1.ProbeCheckResult
}
var file_bridge_v1_interceptor_proto_depIdxs = []int32{
	3, // 0: bridge.v1.GetStatusResponse.liveness:type_name -> bridge.v1.ProbeStatus
	3, // 1: bridge.v1.GetStatusResponse.readiness:type_name -> bridge.v1.ProbeStatus
	3, // 2: bridge.v1.GetStatusResponse.startup:type_name -> bridge.v1.ProbeStatus
	0, // 3: bridge.v1.ProbeStatus.health:type_name -> bridge.v1.ProbeHealth
	6, // 4: bridge.v1.ProbeResponse.liveness:type_name -> bridge.v1.ProbeCheckResult
	6, // 5: bridge.v1.ProbeResponse.readiness:type_name -> bridge.v1.ProbeCheckResult
	6, // 6: bridge.v1.ProbeResponse.startup:type_name -> bridge.v1.ProbeCheckResult
	1, // 7: bridge.v1.InterceptorService.GetStatus:input_type -> bridge.v1.GetStatusRequest
	4, // 8: bridge.v1.InterceptorService.Probe:input_type -> bridge.v1.ProbeRequest
	2, // 9: bridge.v1.InterceptorService.GetStatus:output_type -> bridge.v1.GetStatusResponse
	5, // 10: bridge.v1.InterceptorService.Probe:output_type -> bridge.v1.ProbeResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_bridge_v1_interceptor_proto_init() }
func file_bridge_v1_interceptor_proto_init() {
	if File_bridge_v1_interceptor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_interceptor_proto_rawDesc), len(file_bridge_v1_interceptor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_v1_interceptor_proto_goTypes,
		DependencyIndexes: file_bridge_v1_interceptor_proto_depIdxs,
		EnumInfos:         file_bridge_v1_interceptor_proto_enumTypes,
		MessageInfos:      file_bridge_v1_interceptor_proto_msgTypes,
	}.Build()
	File_bridge_v1_interceptor_proto = out.File
	file_bridge_v1_interceptor_proto_goTypes = nil
	file_bridge_v1_interceptor_proto_depIdxs = nil
}
