// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge/v1/proxy.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelProtocol int32

const (
	TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED TunnelProtocol = 0
	TunnelProtocol_TUNNEL_PROTOCOL_TCP         TunnelProtocol = 1
	TunnelProtocol_TUNNEL_PROTOCOL_UDP         TunnelProtocol = 2
)

// Enum value maps for TunnelProtocol.
var (
	TunnelProtocol_name = map[int32]string{
		0: "TUNNEL_PROTOCOL_UNSPECIFIED",
		1: "TUNNEL_PROTOCOL_TCP",
		2: "TUNNEL_PROTOCOL_UDP",
	}
	TunnelProtocol_value = map[string]int32{
		"TUNNEL_PROTOCOL_UNSPECIFIED": 0,
		"TUNNEL_PROTOCOL_TCP":         1,
		"TUNNEL_PROTOCOL_UDP":         2,
	}
)

func (x TunnelProtocol) Enum() *TunnelProtocol {
	p := new(TunnelProtocol)
	*p = x
	return p
}

func (x TunnelProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_v1_proxy_proto_enumTypes[0].Descriptor()
}

func (TunnelProtocol) Type() protoreflect.EnumType {
	return &file_bridge_v1_proxy_proto_enumTypes[0]
}

func (x TunnelProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelProtocol.Descriptor instead.
func (TunnelProtocol) EnumDescriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{0}
}

type ProxyResolveDNSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResolveDNSRequest) Reset() {
	*x = ProxyResolveDNSRequest{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResolveDNSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResolveDNSRequest) ProtoMessage() {}

func (x *ProxyResolveDNSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResolveDNSRequest.ProtoReflect.Descriptor instead.
func (*ProxyResolveDNSRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyResolveDNSRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ProxyResolveDNSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResolveDNSResponse) Reset() {
	*x = ProxyResolveDNSResponse{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResolveDNSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResolveDNSResponse) ProtoMessage() {}

func (x *ProxyResolveDNSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResolveDNSResponse.ProtoReflect.Descriptor instead.
func (*ProxyResolveDNSResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyResolveDNSResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ProxyResolveDNSResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TunnelAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelAddress) Reset() {
	*x = TunnelAddress{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelAddress) ProtoMessage() {}

func (x *TunnelAddress) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelAddress.ProtoReflect.Descriptor instead.
func (*TunnelAddress) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *TunnelAddress) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *TunnelAddress) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TunnelNetworkMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The address that is sending the message.
	Source *TunnelAddress `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// The intended target address on the destination.
	Dest *TunnelAddress `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	// Connection ID for multiplexing multiple connections over one stream.
	ConnectionId string `protobuf:"bytes,3,opt,name=connection_id,proto3" json:"connection_id,omitempty"`
	// The payload data being tunneled.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// The protocol used for the connection (TCP or UDP).
	Protocol TunnelProtocol `protobuf:"varint,5,opt,name=protocol,proto3,enum=bridge.v1.TunnelProtocol" json:"protocol,omitempty"`
	// Error message if something went wrong.
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelNetworkMessage) Reset() {
	*x = TunnelNetworkMessage{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelNetworkMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelNetworkMessage) ProtoMessage() {}

func (x *TunnelNetworkMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelNetworkMessage.ProtoReflect.Descriptor instead.
func (*TunnelNetworkMessage) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *TunnelNetworkMessage) GetSource() *TunnelAddress {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TunnelNetworkMessage) GetDest() *TunnelAddress {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *TunnelNetworkMessage) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *TunnelNetworkMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TunnelNetworkMessage) GetProtocol() TunnelProtocol {
	if x != nil {
		return x.Protocol
	}
	return TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED
}

func (x *TunnelNetworkMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_bridge_v1_proxy_proto protoreflect.FileDescriptor

const file_bridge_v1_proxy_proto_rawDesc = "" +
	"\n" +
	"\x15bridge/v1/proxy.proto\x12\tbridge.v1\"4\n" +
	"\x16ProxyResolveDNSRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"M\n" +
	"\x17ProxyResolveDNSResponse\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"3\n" +
	"\rTunnelAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\xfd\x01\n" +
	"\x14TunnelNetworkMessage\x120\n" +
	"\x06source\x18\x01 \x01(\v2\x18.bridge.v1.TunnelAddressR\x06source\x12,\n" +
	"\x04dest\x18\x02 \x01(\v2\x18.bridge.v1.TunnelAddressR\x04dest\x12$\n" +
	"\rconnection_id\x18\x03 \x01(\tR\rconnection_id\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x125\n" +
	"\bprotocol\x18\x05 \x01(\x0e2\x19.bridge.v1.TunnelProtocolR\bprotocol\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error*c\n" +
	"\x0eTunnelProtocol\x12\x1f\n" +
	"\x1bTUNNEL_PROTOCOL_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TUNNEL_PROTOCOL_TCP\x10\x01\x12\x17\n" +
	"\x13TUNNEL_PROTOCOL_UDP\x10\x022\xc5\x01\n" +
	"\x12BridgeProxyService\x12X\n" +
	"\x0fResolveDNSQuery\x12!.bridge.v1.ProxyResolveDNSRequest\x1a\".bridge.v1.ProxyResolveDNSResponse\x12U\n" +
	"\rTunnelNetwork\x12\x1f.bridge.v1.TunnelNetworkMessage\x1a\x1f.bridge.v1.TunnelNetworkMessage(\x010\x01B\x9a\x01\n" +
	"\rcom.bridge.v1B\n" +
	"ProxyProtoP\x01Z8github.com/vercel/bridge/api/go/bridge/v1;bridgev1\xa2\x02\x03BXX\xaa\x02\tBridge.V1\xca\x02\tBridge\\V1\xe2\x02\x15Bridge\\V1\\GPBMetadata\xea\x02\n" +
	"Bridge::V1b\x06proto3"

var (
	file_bridge_v1_proxy_proto_rawDescOnce sync.Once
	file_bridge_v1_proxy_proto_rawDescData []byte
)

func file_bridge_v1_proxy_proto_rawDescGZIP() []byte {
	file_bridge_v1_proxy_proto_rawDescOnce.Do(func() {
		file_bridge_v1_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_proxy_proto_rawDesc), len(file_bridge_v1_proxy_proto_rawDesc)))
	})
	return file_bridge_v1_proxy_proto_rawDescData
}

var file_bridge_v1_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_v1_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bridge_v1_proxy_proto_goTypes = []any{
	(TunnelProtocol)(0),             // 0: bridge.v1.TunnelProtocol
	(*ProxyResolveDNSRequest)(nil),  // 1: bridge.v1.ProxyResolveDNSRequest
	(*ProxyResolveDNSResponse)(nil), // 2: bridge.v1.ProxyResolveDNSResponse
	(*TunnelAddress)(nil),           // 3: bridge.v1.TunnelAddress
	(*TunnelNetworkMessage)(nil),    // 4: bridge.v1.TunnelNetworkMessage
}
var file_bridge_v1_proxy_proto_depIdxs = []int32{
	3, // 0: bridge.v1.TunnelNetworkMessage.source:type_name -> bridge.v1.TunnelAddress
	3, // 1: bridge.v1.TunnelNetworkMessage.dest:type_name -> bridge.v1.TunnelAddress
	0, // 2: bridge.v1.TunnelNetworkMessage.protocol:type_name -> bridge.v1.TunnelProtocol
	1, // 3: bridge.v1.BridgeProxyService.ResolveDNSQuery:input_type -> bridge.v1.ProxyResolveDNSRequest
	4, // 4: bridge.v1.BridgeProxyService.TunnelNetwork:input_type -> bridge.v1.TunnelNetworkMessage
	2, // 5: bridge.v1.BridgeProxyService.ResolveDNSQuery:output_type -> bridge.v1.ProxyResolveDNSResponse
	4, // 6: bridge.v1.BridgeProxyService.TunnelNetwork:output_type -> bridge.v1.TunnelNetworkMessage
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bridge_v1_proxy_proto_init() }
func file_bridge_v1_proxy_proto_init() {
	if File_bridge_v1_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_proxy_proto_rawDesc), len(file_bridge_v1_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_v1_proxy_proto_goTypes,
		DependencyIndexes: file_bridge_v1_proxy_proto_depIdxs,
		EnumInfos:         file_bridge_v1_proxy_proto_enumTypes,
		MessageInfos:      file_bridge_v1_proxy_proto_msgTypes,
	}.Build()
	File_bridge_v1_proxy_proto = out.File
	file_bridge_v1_proxy_proto_goTypes = nil
	file_bridge_v1_proxy_proto_depIdxs = nil
}
