// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: bridge/v1/proxy.proto

package bridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BridgeProxyService_ResolveDNSQuery_FullMethodName = "/bridge.v1.BridgeProxyService/ResolveDNSQuery"
	BridgeProxyService_TunnelNetwork_FullMethodName   = "/bridge.v1.BridgeProxyService/TunnelNetwork"
	BridgeProxyService_GetMetadata_FullMethodName     = "/bridge.v1.BridgeProxyService/GetMetadata"
)

// BridgeProxyServiceClient is the client API for BridgeProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BridgeProxyService runs in-cluster and provides DNS resolution and network
// tunneling to the local bridge intercept client over gRPC.
type BridgeProxyServiceClient interface {
	// ResolveDNSQuery resolves a hostname using the in-cluster DNS (CoreDNS).
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ResolveDNSQuery(ctx context.Context, in *ProxyResolveDNSRequest, opts ...grpc.CallOption) (*ProxyResolveDNSResponse, error)
	// TunnelNetwork tunnels TCP/UDP traffic to an upstream service over a
	// bidirectional stream. Every message carries source/dest addresses and a
	// connection ID so both sides share the same addressing semantics as the
	// WebSocket Message in bridge.proto.
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	TunnelNetwork(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelNetworkMessage, TunnelNetworkMessage], error)
	// GetMetadata returns metadata about the bridge proxy, including environment
	// variables from the pod that can be forwarded to the devcontainer.
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
}

type bridgeProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeProxyServiceClient(cc grpc.ClientConnInterface) BridgeProxyServiceClient {
	return &bridgeProxyServiceClient{cc}
}

func (c *bridgeProxyServiceClient) ResolveDNSQuery(ctx context.Context, in *ProxyResolveDNSRequest, opts ...grpc.CallOption) (*ProxyResolveDNSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyResolveDNSResponse)
	err := c.cc.Invoke(ctx, BridgeProxyService_ResolveDNSQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeProxyServiceClient) TunnelNetwork(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelNetworkMessage, TunnelNetworkMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BridgeProxyService_ServiceDesc.Streams[0], BridgeProxyService_TunnelNetwork_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelNetworkMessage, TunnelNetworkMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BridgeProxyService_TunnelNetworkClient = grpc.BidiStreamingClient[TunnelNetworkMessage, TunnelNetworkMessage]

func (c *bridgeProxyServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, BridgeProxyService_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeProxyServiceServer is the server API for BridgeProxyService service.
// All implementations must embed UnimplementedBridgeProxyServiceServer
// for forward compatibility.
//
// BridgeProxyService runs in-cluster and provides DNS resolution and network
// tunneling to the local bridge intercept client over gRPC.
type BridgeProxyServiceServer interface {
	// ResolveDNSQuery resolves a hostname using the in-cluster DNS (CoreDNS).
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ResolveDNSQuery(context.Context, *ProxyResolveDNSRequest) (*ProxyResolveDNSResponse, error)
	// TunnelNetwork tunnels TCP/UDP traffic to an upstream service over a
	// bidirectional stream. Every message carries source/dest addresses and a
	// connection ID so both sides share the same addressing semantics as the
	// WebSocket Message in bridge.proto.
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	TunnelNetwork(grpc.BidiStreamingServer[TunnelNetworkMessage, TunnelNetworkMessage]) error
	// GetMetadata returns metadata about the bridge proxy, including environment
	// variables from the pod that can be forwarded to the devcontainer.
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	mustEmbedUnimplementedBridgeProxyServiceServer()
}

// UnimplementedBridgeProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBridgeProxyServiceServer struct{}

func (UnimplementedBridgeProxyServiceServer) ResolveDNSQuery(context.Context, *ProxyResolveDNSRequest) (*ProxyResolveDNSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveDNSQuery not implemented")
}
func (UnimplementedBridgeProxyServiceServer) TunnelNetwork(grpc.BidiStreamingServer[TunnelNetworkMessage, TunnelNetworkMessage]) error {
	return status.Error(codes.Unimplemented, "method TunnelNetwork not implemented")
}
func (UnimplementedBridgeProxyServiceServer) GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedBridgeProxyServiceServer) mustEmbedUnimplementedBridgeProxyServiceServer() {}
func (UnimplementedBridgeProxyServiceServer) testEmbeddedByValue()                            {}

// UnsafeBridgeProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeProxyServiceServer will
// result in compilation errors.
type UnsafeBridgeProxyServiceServer interface {
	mustEmbedUnimplementedBridgeProxyServiceServer()
}

func RegisterBridgeProxyServiceServer(s grpc.ServiceRegistrar, srv BridgeProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedBridgeProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BridgeProxyService_ServiceDesc, srv)
}

func _BridgeProxyService_ResolveDNSQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyResolveDNSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeProxyServiceServer).ResolveDNSQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeProxyService_ResolveDNSQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeProxyServiceServer).ResolveDNSQuery(ctx, req.(*ProxyResolveDNSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeProxyService_TunnelNetwork_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BridgeProxyServiceServer).TunnelNetwork(&grpc.GenericServerStream[TunnelNetworkMessage, TunnelNetworkMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BridgeProxyService_TunnelNetworkServer = grpc.BidiStreamingServer[TunnelNetworkMessage, TunnelNetworkMessage]

func _BridgeProxyService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeProxyServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeProxyService_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeProxyServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BridgeProxyService_ServiceDesc is the grpc.ServiceDesc for BridgeProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgeProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.v1.BridgeProxyService",
	HandlerType: (*BridgeProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveDNSQuery",
			Handler:    _BridgeProxyService_ResolveDNSQuery_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _BridgeProxyService_GetMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TunnelNetwork",
			Handler:       _BridgeProxyService_TunnelNetwork_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bridge/v1/proxy.proto",
}
