// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge/v1/proxy.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelProtocol int32

const (
	TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED TunnelProtocol = 0
	TunnelProtocol_TUNNEL_PROTOCOL_TCP         TunnelProtocol = 1
	TunnelProtocol_TUNNEL_PROTOCOL_UDP         TunnelProtocol = 2
)

// Enum value maps for TunnelProtocol.
var (
	TunnelProtocol_name = map[int32]string{
		0: "TUNNEL_PROTOCOL_UNSPECIFIED",
		1: "TUNNEL_PROTOCOL_TCP",
		2: "TUNNEL_PROTOCOL_UDP",
	}
	TunnelProtocol_value = map[string]int32{
		"TUNNEL_PROTOCOL_UNSPECIFIED": 0,
		"TUNNEL_PROTOCOL_TCP":         1,
		"TUNNEL_PROTOCOL_UDP":         2,
	}
)

func (x TunnelProtocol) Enum() *TunnelProtocol {
	p := new(TunnelProtocol)
	*p = x
	return p
}

func (x TunnelProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_v1_proxy_proto_enumTypes[0].Descriptor()
}

func (TunnelProtocol) Type() protoreflect.EnumType {
	return &file_bridge_v1_proxy_proto_enumTypes[0]
}

func (x TunnelProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelProtocol.Descriptor instead.
func (TunnelProtocol) EnumDescriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{0}
}

type ProxyResolveDNSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResolveDNSRequest) Reset() {
	*x = ProxyResolveDNSRequest{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResolveDNSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResolveDNSRequest) ProtoMessage() {}

func (x *ProxyResolveDNSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResolveDNSRequest.ProtoReflect.Descriptor instead.
func (*ProxyResolveDNSRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyResolveDNSRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ProxyResolveDNSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResolveDNSResponse) Reset() {
	*x = ProxyResolveDNSResponse{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResolveDNSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResolveDNSResponse) ProtoMessage() {}

func (x *ProxyResolveDNSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResolveDNSResponse.ProtoReflect.Descriptor instead.
func (*ProxyResolveDNSResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyResolveDNSResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ProxyResolveDNSResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TunnelAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelAddress) Reset() {
	*x = TunnelAddress{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelAddress) ProtoMessage() {}

func (x *TunnelAddress) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelAddress.ProtoReflect.Descriptor instead.
func (*TunnelAddress) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *TunnelAddress) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *TunnelAddress) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{3}
}

type GetMetadataResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EnvVars map[string]string      `protobuf:"bytes,1,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// PEM-encoded CA certificate for TLS interception of mocked services.
	// Mounted into the bridge proxy pod from a Kubernetes Secret.
	CaCert []byte `protobuf:"bytes,2,opt,name=ca_cert,proto3" json:"ca_cert,omitempty"`
	// PEM-encoded CA private key for minting per-host TLS certificates.
	// Mounted into the bridge proxy pod from a Kubernetes Secret.
	CaKey []byte `protobuf:"bytes,3,opt,name=ca_key,proto3" json:"ca_key,omitempty"`
	// Absolute paths the BridgeFileSystemService is allowed to serve. The
	// devcontainer FUSE-mounts each one at the same path on the local side.
	MountRoots []string `protobuf:"bytes,4,rep,name=mount_roots,proto3" json:"mount_roots,omitempty"`
	// The source container's primary application port (the first non-grpc port
	// declared on the original deployment). The interceptor uses this to
	// remap probe targets: if a probe's port matches source_app_port, the
	// interceptor checks --app-port locally instead. Zero if the source had
	// no app ports.
	SourceAppPort int32 `protobuf:"varint,5,opt,name=source_app_port,proto3" json:"source_app_port,omitempty"`
	// Liveness probe from the source deployment's application container, or
	// unset if the source had none.
	LivenessProbe *Probe `protobuf:"bytes,6,opt,name=liveness_probe,proto3" json:"liveness_probe,omitempty"`
	// Readiness probe from the source deployment's application container, or
	// unset if the source had none.
	ReadinessProbe *Probe `protobuf:"bytes,7,opt,name=readiness_probe,proto3" json:"readiness_probe,omitempty"`
	// Startup probe from the source deployment's application container, or
	// unset if the source had none.
	StartupProbe  *Probe `protobuf:"bytes,8,opt,name=startup_probe,proto3" json:"startup_probe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetadataResponse) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *GetMetadataResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *GetMetadataResponse) GetCaKey() []byte {
	if x != nil {
		return x.CaKey
	}
	return nil
}

func (x *GetMetadataResponse) GetMountRoots() []string {
	if x != nil {
		return x.MountRoots
	}
	return nil
}

func (x *GetMetadataResponse) GetSourceAppPort() int32 {
	if x != nil {
		return x.SourceAppPort
	}
	return 0
}

func (x *GetMetadataResponse) GetLivenessProbe() *Probe {
	if x != nil {
		return x.LivenessProbe
	}
	return nil
}

func (x *GetMetadataResponse) GetReadinessProbe() *Probe {
	if x != nil {
		return x.ReadinessProbe
	}
	return nil
}

func (x *GetMetadataResponse) GetStartupProbe() *Probe {
	if x != nil {
		return x.StartupProbe
	}
	return nil
}

// Probe mirrors a Kubernetes-style probe definition for a single check (HTTP
// GET, TCP open, gRPC health, or shell exec). Exactly one handler is set.
type Probe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Handler:
	//
	//	*Probe_HttpGet
	//	*Probe_TcpSocket
	//	*Probe_Grpc
	//	*Probe_Exec
	Handler isProbe_Handler `protobuf_oneof:"handler"`
	// Seconds to wait before the first check. Default 0.
	InitialDelaySeconds int32 `protobuf:"varint,10,opt,name=initial_delay_seconds,proto3" json:"initial_delay_seconds,omitempty"`
	// How often (in seconds) to perform the probe. Default 10.
	PeriodSeconds int32 `protobuf:"varint,11,opt,name=period_seconds,proto3" json:"period_seconds,omitempty"`
	// Seconds after which a single check is considered failed. Default 1.
	TimeoutSeconds int32 `protobuf:"varint,12,opt,name=timeout_seconds,proto3" json:"timeout_seconds,omitempty"`
	// Minimum consecutive successes for the probe to be considered healthy
	// after having been failing. Default 1.
	SuccessThreshold int32 `protobuf:"varint,13,opt,name=success_threshold,proto3" json:"success_threshold,omitempty"`
	// After this many consecutive failures the probe is considered failing.
	// Default 3.
	FailureThreshold int32 `protobuf:"varint,14,opt,name=failure_threshold,proto3" json:"failure_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Probe) Reset() {
	*x = Probe{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Probe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Probe) ProtoMessage() {}

func (x *Probe) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Probe.ProtoReflect.Descriptor instead.
func (*Probe) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *Probe) GetHandler() isProbe_Handler {
	if x != nil {
		return x.Handler
	}
	return nil
}

func (x *Probe) GetHttpGet() *HTTPGetAction {
	if x != nil {
		if x, ok := x.Handler.(*Probe_HttpGet); ok {
			return x.HttpGet
		}
	}
	return nil
}

func (x *Probe) GetTcpSocket() *TCPSocketAction {
	if x != nil {
		if x, ok := x.Handler.(*Probe_TcpSocket); ok {
			return x.TcpSocket
		}
	}
	return nil
}

func (x *Probe) GetGrpc() *GRPCAction {
	if x != nil {
		if x, ok := x.Handler.(*Probe_Grpc); ok {
			return x.Grpc
		}
	}
	return nil
}

func (x *Probe) GetExec() *ExecAction {
	if x != nil {
		if x, ok := x.Handler.(*Probe_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *Probe) GetInitialDelaySeconds() int32 {
	if x != nil {
		return x.InitialDelaySeconds
	}
	return 0
}

func (x *Probe) GetPeriodSeconds() int32 {
	if x != nil {
		return x.PeriodSeconds
	}
	return 0
}

func (x *Probe) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Probe) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

func (x *Probe) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

type isProbe_Handler interface {
	isProbe_Handler()
}

type Probe_HttpGet struct {
	HttpGet *HTTPGetAction `protobuf:"bytes,1,opt,name=http_get,proto3,oneof"`
}

type Probe_TcpSocket struct {
	TcpSocket *TCPSocketAction `protobuf:"bytes,2,opt,name=tcp_socket,proto3,oneof"`
}

type Probe_Grpc struct {
	Grpc *GRPCAction `protobuf:"bytes,3,opt,name=grpc,proto3,oneof"`
}

type Probe_Exec struct {
	Exec *ExecAction `protobuf:"bytes,4,opt,name=exec,proto3,oneof"`
}

func (*Probe_HttpGet) isProbe_Handler() {}

func (*Probe_TcpSocket) isProbe_Handler() {}

func (*Probe_Grpc) isProbe_Handler() {}

func (*Probe_Exec) isProbe_Handler() {}

// HTTPGetAction performs an HTTP GET against the local app.
type HTTPGetAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request path. Defaults to "/".
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Target port. The interceptor remaps this to --app-port if it matches
	// source_app_port.
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// "HTTP" or "HTTPS". Defaults to HTTP.
	Scheme string `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// Extra request headers.
	HttpHeaders   []*HTTPHeader `protobuf:"bytes,4,rep,name=http_headers,proto3" json:"http_headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPGetAction) Reset() {
	*x = HTTPGetAction{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPGetAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPGetAction) ProtoMessage() {}

func (x *HTTPGetAction) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPGetAction.ProtoReflect.Descriptor instead.
func (*HTTPGetAction) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *HTTPGetAction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPGetAction) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HTTPGetAction) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *HTTPGetAction) GetHttpHeaders() []*HTTPHeader {
	if x != nil {
		return x.HttpHeaders
	}
	return nil
}

type HTTPHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPHeader) Reset() {
	*x = HTTPHeader{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPHeader) ProtoMessage() {}

func (x *HTTPHeader) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPHeader.ProtoReflect.Descriptor instead.
func (*HTTPHeader) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *HTTPHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HTTPHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// TCPSocketAction opens a TCP connection.
type TCPSocketAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target port. The interceptor remaps this to --app-port if it matches
	// source_app_port.
	Port          int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPSocketAction) Reset() {
	*x = TCPSocketAction{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPSocketAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPSocketAction) ProtoMessage() {}

func (x *TCPSocketAction) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPSocketAction.ProtoReflect.Descriptor instead.
func (*TCPSocketAction) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *TCPSocketAction) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// GRPCAction calls the gRPC health service on the target.
type GRPCAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target port. The interceptor remaps this to --app-port if it matches
	// source_app_port.
	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// Optional service name to check (passed as `service` in the health
	// request). Empty checks the overall server health.
	Service       string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPCAction) Reset() {
	*x = GRPCAction{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCAction) ProtoMessage() {}

func (x *GRPCAction) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCAction.ProtoReflect.Descriptor instead.
func (*GRPCAction) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *GRPCAction) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GRPCAction) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// ExecAction runs a command inside the devcontainer; exit code 0 is healthy.
type ExecAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Argv. The first element is the program; the rest are arguments.
	Command       []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecAction) Reset() {
	*x = ExecAction{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecAction) ProtoMessage() {}

func (x *ExecAction) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecAction.ProtoReflect.Descriptor instead.
func (*ExecAction) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{10}
}

func (x *ExecAction) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type TunnelNetworkMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The address that is sending the message.
	Source *TunnelAddress `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// The intended target address on the destination.
	Dest *TunnelAddress `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	// Connection ID for multiplexing multiple connections over one stream.
	ConnectionId string `protobuf:"bytes,3,opt,name=connection_id,proto3" json:"connection_id,omitempty"`
	// The payload data being tunneled.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// The protocol used for the connection (TCP or UDP).
	Protocol TunnelProtocol `protobuf:"varint,5,opt,name=protocol,proto3,enum=bridge.v1.TunnelProtocol" json:"protocol,omitempty"`
	// Error message if something went wrong.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// The hostname associated with this connection, resolved by the intercept
	// DNS interceptor. Used by the server for mock matching and TLS cert minting.
	Hostname      string `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelNetworkMessage) Reset() {
	*x = TunnelNetworkMessage{}
	mi := &file_bridge_v1_proxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelNetworkMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelNetworkMessage) ProtoMessage() {}

func (x *TunnelNetworkMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_proxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelNetworkMessage.ProtoReflect.Descriptor instead.
func (*TunnelNetworkMessage) Descriptor() ([]byte, []int) {
	return file_bridge_v1_proxy_proto_rawDescGZIP(), []int{11}
}

func (x *TunnelNetworkMessage) GetSource() *TunnelAddress {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TunnelNetworkMessage) GetDest() *TunnelAddress {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *TunnelNetworkMessage) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *TunnelNetworkMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TunnelNetworkMessage) GetProtocol() TunnelProtocol {
	if x != nil {
		return x.Protocol
	}
	return TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED
}

func (x *TunnelNetworkMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TunnelNetworkMessage) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

var File_bridge_v1_proxy_proto protoreflect.FileDescriptor

const file_bridge_v1_proxy_proto_rawDesc = "" +
	"\n" +
	"\x15bridge/v1/proxy.proto\x12\tbridge.v1\"4\n" +
	"\x16ProxyResolveDNSRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"M\n" +
	"\x17ProxyResolveDNSResponse\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"3\n" +
	"\rTunnelAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\x14\n" +
	"\x12GetMetadataRequest\"\xc5\x03\n" +
	"\x13GetMetadataResponse\x12F\n" +
	"\benv_vars\x18\x01 \x03(\v2+.bridge.v1.GetMetadataResponse.EnvVarsEntryR\aenvVars\x12\x18\n" +
	"\aca_cert\x18\x02 \x01(\fR\aca_cert\x12\x16\n" +
	"\x06ca_key\x18\x03 \x01(\fR\x06ca_key\x12 \n" +
	"\vmount_roots\x18\x04 \x03(\tR\vmount_roots\x12(\n" +
	"\x0fsource_app_port\x18\x05 \x01(\x05R\x0fsource_app_port\x128\n" +
	"\x0eliveness_probe\x18\x06 \x01(\v2\x10.bridge.v1.ProbeR\x0eliveness_probe\x12:\n" +
	"\x0freadiness_probe\x18\a \x01(\v2\x10.bridge.v1.ProbeR\x0freadiness_probe\x126\n" +
	"\rstartup_probe\x18\b \x01(\v2\x10.bridge.v1.ProbeR\rstartup_probe\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x03\n" +
	"\x05Probe\x126\n" +
	"\bhttp_get\x18\x01 \x01(\v2\x18.bridge.v1.HTTPGetActionH\x00R\bhttp_get\x12<\n" +
	"\n" +
	"tcp_socket\x18\x02 \x01(\v2\x1a.bridge.v1.TCPSocketActionH\x00R\n" +
	"tcp_socket\x12+\n" +
	"\x04grpc\x18\x03 \x01(\v2\x15.bridge.v1.GRPCActionH\x00R\x04grpc\x12+\n" +
	"\x04exec\x18\x04 \x01(\v2\x15.bridge.v1.ExecActionH\x00R\x04exec\x124\n" +
	"\x15initial_delay_seconds\x18\n" +
	" \x01(\x05R\x15initial_delay_seconds\x12&\n" +
	"\x0eperiod_seconds\x18\v \x01(\x05R\x0eperiod_seconds\x12(\n" +
	"\x0ftimeout_seconds\x18\f \x01(\x05R\x0ftimeout_seconds\x12,\n" +
	"\x11success_threshold\x18\r \x01(\x05R\x11success_threshold\x12,\n" +
	"\x11failure_threshold\x18\x0e \x01(\x05R\x11failure_thresholdB\t\n" +
	"\ahandler\"\x8a\x01\n" +
	"\rHTTPGetAction\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x16\n" +
	"\x06scheme\x18\x03 \x01(\tR\x06scheme\x129\n" +
	"\fhttp_headers\x18\x04 \x03(\v2\x15.bridge.v1.HTTPHeaderR\fhttp_headers\"6\n" +
	"\n" +
	"HTTPHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"%\n" +
	"\x0fTCPSocketAction\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\":\n" +
	"\n" +
	"GRPCAction\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"&\n" +
	"\n" +
	"ExecAction\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\"\x99\x02\n" +
	"\x14TunnelNetworkMessage\x120\n" +
	"\x06source\x18\x01 \x01(\v2\x18.bridge.v1.TunnelAddressR\x06source\x12,\n" +
	"\x04dest\x18\x02 \x01(\v2\x18.bridge.v1.TunnelAddressR\x04dest\x12$\n" +
	"\rconnection_id\x18\x03 \x01(\tR\rconnection_id\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x125\n" +
	"\bprotocol\x18\x05 \x01(\x0e2\x19.bridge.v1.TunnelProtocolR\bprotocol\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1a\n" +
	"\bhostname\x18\a \x01(\tR\bhostname*c\n" +
	"\x0eTunnelProtocol\x12\x1f\n" +
	"\x1bTUNNEL_PROTOCOL_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TUNNEL_PROTOCOL_TCP\x10\x01\x12\x17\n" +
	"\x13TUNNEL_PROTOCOL_UDP\x10\x022\x93\x02\n" +
	"\x12BridgeProxyService\x12X\n" +
	"\x0fResolveDNSQuery\x12!.bridge.v1.ProxyResolveDNSRequest\x1a\".bridge.v1.ProxyResolveDNSResponse\x12U\n" +
	"\rTunnelNetwork\x12\x1f.bridge.v1.TunnelNetworkMessage\x1a\x1f.bridge.v1.TunnelNetworkMessage(\x010\x01\x12L\n" +
	"\vGetMetadata\x12\x1d.bridge.v1.GetMetadataRequest\x1a\x1e.bridge.v1.GetMetadataResponseB\x94\x01\n" +
	"\rcom.bridge.v1B\n" +
	"ProxyProtoP\x01Z2github.com/vercel/bridge/api/go/bridge/v1;bridgev1\xa2\x02\x03BXX\xaa\x02\tBridge.V1\xca\x02\tBridge\\V1\xe2\x02\x15Bridge\\V1\\GPBMetadata\xea\x02\n" +
	"Bridge::V1b\x06proto3"

var (
	file_bridge_v1_proxy_proto_rawDescOnce sync.Once
	file_bridge_v1_proxy_proto_rawDescData []byte
)

func file_bridge_v1_proxy_proto_rawDescGZIP() []byte {
	file_bridge_v1_proxy_proto_rawDescOnce.Do(func() {
		file_bridge_v1_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_proxy_proto_rawDesc), len(file_bridge_v1_proxy_proto_rawDesc)))
	})
	return file_bridge_v1_proxy_proto_rawDescData
}

var file_bridge_v1_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_v1_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_bridge_v1_proxy_proto_goTypes = []any{
	(TunnelProtocol)(0),             // 0: bridge.v1.TunnelProtocol
	(*ProxyResolveDNSRequest)(nil),  // 1: bridge.v1.ProxyResolveDNSRequest
	(*ProxyResolveDNSResponse)(nil), // 2: bridge.v1.ProxyResolveDNSResponse
	(*TunnelAddress)(nil),           // 3: bridge.v1.TunnelAddress
	(*GetMetadataRequest)(nil),      // 4: bridge.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil),     // 5: bridge.v1.GetMetadataResponse
	(*Probe)(nil),                   // 6: bridge.v1.Probe
	(*HTTPGetAction)(nil),           // 7: bridge.v1.HTTPGetAction
	(*HTTPHeader)(nil),              // 8: bridge.v1.HTTPHeader
	(*TCPSocketAction)(nil),         // 9: bridge.v1.TCPSocketAction
	(*GRPCAction)(nil),              // 10: bridge.v1.GRPCAction
	(*ExecAction)(nil),              // 11: bridge.v1.ExecAction
	(*TunnelNetworkMessage)(nil),    // 12: bridge.v1.TunnelNetworkMessage
	nil,                             // 13: bridge.v1.GetMetadataResponse.EnvVarsEntry
}
var file_bridge_v1_proxy_proto_depIdxs = []int32{
	13, // 0: bridge.v1.GetMetadataResponse.env_vars:type_name -> bridge.v1.GetMetadataResponse.EnvVarsEntry
	6,  // 1: bridge.v1.GetMetadataResponse.liveness_probe:type_name -> bridge.v1.Probe
	6,  // 2: bridge.v1.GetMetadataResponse.readiness_probe:type_name -> bridge.v1.Probe
	6,  // 3: bridge.v1.GetMetadataResponse.startup_probe:type_name -> bridge.v1.Probe
	7,  // 4: bridge.v1.Probe.http_get:type_name -> bridge.v1.HTTPGetAction
	9,  // 5: bridge.v1.Probe.tcp_socket:type_name -> bridge.v1.TCPSocketAction
	10, // 6: bridge.v1.Probe.grpc:type_name -> bridge.v1.GRPCAction
	11, // 7: bridge.v1.Probe.exec:type_name -> bridge.v1.ExecAction
	8,  // 8: bridge.v1.HTTPGetAction.http_headers:type_name -> bridge.v1.HTTPHeader
	3,  // 9: bridge.v1.TunnelNetworkMessage.source:type_name -> bridge.v1.TunnelAddress
	3,  // 10: bridge.v1.TunnelNetworkMessage.dest:type_name -> bridge.v1.TunnelAddress
	0,  // 11: bridge.v1.TunnelNetworkMessage.protocol:type_name -> bridge.v1.TunnelProtocol
	1,  // 12: bridge.v1.BridgeProxyService.ResolveDNSQuery:input_type -> bridge.v1.ProxyResolveDNSRequest
	12, // 13: bridge.v1.BridgeProxyService.TunnelNetwork:input_type -> bridge.v1.TunnelNetworkMessage
	4,  // 14: bridge.v1.BridgeProxyService.GetMetadata:input_type -> bridge.v1.GetMetadataRequest
	2,  // 15: bridge.v1.BridgeProxyService.ResolveDNSQuery:output_type -> bridge.v1.ProxyResolveDNSResponse
	12, // 16: bridge.v1.BridgeProxyService.TunnelNetwork:output_type -> bridge.v1.TunnelNetworkMessage
	5,  // 17: bridge.v1.BridgeProxyService.GetMetadata:output_type -> bridge.v1.GetMetadataResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_bridge_v1_proxy_proto_init() }
func file_bridge_v1_proxy_proto_init() {
	if File_bridge_v1_proxy_proto != nil {
		return
	}
	file_bridge_v1_proxy_proto_msgTypes[5].OneofWrappers = []any{
		(*Probe_HttpGet)(nil),
		(*Probe_TcpSocket)(nil),
		(*Probe_Grpc)(nil),
		(*Probe_Exec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_proxy_proto_rawDesc), len(file_bridge_v1_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_v1_proxy_proto_goTypes,
		DependencyIndexes: file_bridge_v1_proxy_proto_depIdxs,
		EnumInfos:         file_bridge_v1_proxy_proto_enumTypes,
		MessageInfos:      file_bridge_v1_proxy_proto_msgTypes,
	}.Build()
	File_bridge_v1_proxy_proto = out.File
	file_bridge_v1_proxy_proto_goTypes = nil
	file_bridge_v1_proxy_proto_depIdxs = nil
}
