// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge/v1/server_facade.proto

package bridgev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerFacade intercepts HTTP requests matching a hostname and routes them
// to actions based on CEL expressions.
type ServerFacade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hostname glob pattern this facade intercepts (e.g. "flags.vercel.com",
	// "*.google.com", "**.internal"). Used for routing and TLS cert minting.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Ordered list of routes. First match wins.
	Routes        []*ServerFacadeRoute `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFacade) Reset() {
	*x = ServerFacade{}
	mi := &file_bridge_v1_server_facade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFacade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFacade) ProtoMessage() {}

func (x *ServerFacade) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_server_facade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFacade.ProtoReflect.Descriptor instead.
func (*ServerFacade) Descriptor() ([]byte, []int) {
	return file_bridge_v1_server_facade_proto_rawDescGZIP(), []int{0}
}

func (x *ServerFacade) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServerFacade) GetRoutes() []*ServerFacadeRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

// ServerFacadeRoute pairs a route match with an action to take when matched.
type ServerFacadeRoute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Determines whether this route matches an incoming request.
	Match *ServerFacadeRouteMatch `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	// What to do when matched.
	Action        *ServerFacadeAction `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFacadeRoute) Reset() {
	*x = ServerFacadeRoute{}
	mi := &file_bridge_v1_server_facade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFacadeRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFacadeRoute) ProtoMessage() {}

func (x *ServerFacadeRoute) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_server_facade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFacadeRoute.ProtoReflect.Descriptor instead.
func (*ServerFacadeRoute) Descriptor() ([]byte, []int) {
	return file_bridge_v1_server_facade_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFacadeRoute) GetMatch() *ServerFacadeRouteMatch {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *ServerFacadeRoute) GetAction() *ServerFacadeAction {
	if x != nil {
		return x.Action
	}
	return nil
}

// ServerFacadeRouteMatch evaluates incoming HTTP requests.
type ServerFacadeRouteMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CEL expression evaluated against a ServerFacadeHttpRequest.
	// Must return a boolean.
	Cel           string `protobuf:"bytes,1,opt,name=cel,proto3" json:"cel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFacadeRouteMatch) Reset() {
	*x = ServerFacadeRouteMatch{}
	mi := &file_bridge_v1_server_facade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFacadeRouteMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFacadeRouteMatch) ProtoMessage() {}

func (x *ServerFacadeRouteMatch) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_server_facade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFacadeRouteMatch.ProtoReflect.Descriptor instead.
func (*ServerFacadeRouteMatch) Descriptor() ([]byte, []int) {
	return file_bridge_v1_server_facade_proto_rawDescGZIP(), []int{2}
}

func (x *ServerFacadeRouteMatch) GetCel() string {
	if x != nil {
		return x.Cel
	}
	return ""
}

// ServerFacadeAction defines what response to produce for a matched route.
type ServerFacadeAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Static HTTP response.
	HttpResponse  *ServerFacadeHttpResponse `protobuf:"bytes,1,opt,name=http_response,proto3" json:"http_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFacadeAction) Reset() {
	*x = ServerFacadeAction{}
	mi := &file_bridge_v1_server_facade_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFacadeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFacadeAction) ProtoMessage() {}

func (x *ServerFacadeAction) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_server_facade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFacadeAction.ProtoReflect.Descriptor instead.
func (*ServerFacadeAction) Descriptor() ([]byte, []int) {
	return file_bridge_v1_server_facade_proto_rawDescGZIP(), []int{3}
}

func (x *ServerFacadeAction) GetHttpResponse() *ServerFacadeHttpResponse {
	if x != nil {
		return x.HttpResponse
	}
	return nil
}

// ServerFacadeHttpResponse is a static HTTP response returned by a facade route.
type ServerFacadeHttpResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status code.
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Response body. Marshalled as JSON and sent as the response.
	Body *structpb.Value `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// Response headers.
	Headers       map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFacadeHttpResponse) Reset() {
	*x = ServerFacadeHttpResponse{}
	mi := &file_bridge_v1_server_facade_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFacadeHttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFacadeHttpResponse) ProtoMessage() {}

func (x *ServerFacadeHttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_server_facade_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFacadeHttpResponse.ProtoReflect.Descriptor instead.
func (*ServerFacadeHttpResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_server_facade_proto_rawDescGZIP(), []int{4}
}

func (x *ServerFacadeHttpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ServerFacadeHttpResponse) GetBody() *structpb.Value {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFacadeHttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// ServerFacadeHttpRequest is the request shape available in CEL expressions as `request`.
type ServerFacadeHttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Query         map[string]string      `protobuf:"bytes,5,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFacadeHttpRequest) Reset() {
	*x = ServerFacadeHttpRequest{}
	mi := &file_bridge_v1_server_facade_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFacadeHttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFacadeHttpRequest) ProtoMessage() {}

func (x *ServerFacadeHttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_server_facade_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFacadeHttpRequest.ProtoReflect.Descriptor instead.
func (*ServerFacadeHttpRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_server_facade_proto_rawDescGZIP(), []int{5}
}

func (x *ServerFacadeHttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ServerFacadeHttpRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServerFacadeHttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ServerFacadeHttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ServerFacadeHttpRequest) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ServerFacadeHttpRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_bridge_v1_server_facade_proto protoreflect.FileDescriptor

const file_bridge_v1_server_facade_proto_rawDesc = "" +
	"\n" +
	"\x1dbridge/v1/server_facade.proto\x12\tbridge.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"n\n" +
	"\fServerFacade\x12\x1e\n" +
	"\x04host\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04host\x12>\n" +
	"\x06routes\x18\x02 \x03(\v2\x1c.bridge.v1.ServerFacadeRouteB\b\xbaH\x05\x92\x01\x02\b\x01R\x06routes\"\x93\x01\n" +
	"\x11ServerFacadeRoute\x12?\n" +
	"\x05match\x18\x01 \x01(\v2!.bridge.v1.ServerFacadeRouteMatchB\x06\xbaH\x03\xc8\x01\x01R\x05match\x12=\n" +
	"\x06action\x18\x02 \x01(\v2\x1d.bridge.v1.ServerFacadeActionB\x06\xbaH\x03\xc8\x01\x01R\x06action\"6\n" +
	"\x16ServerFacadeRouteMatch\x12\x1c\n" +
	"\x03cel\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x03cel\"g\n" +
	"\x12ServerFacadeAction\x12Q\n" +
	"\rhttp_response\x18\x01 \x01(\v2#.bridge.v1.ServerFacadeHttpResponseB\x06\xbaH\x03\xc8\x01\x01R\rhttp_response\"\xf2\x01\n" +
	"\x18ServerFacadeHttpResponse\x12\"\n" +
	"\x06status\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xd7\x04(dR\x06status\x12*\n" +
	"\x04body\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x04body\x12J\n" +
	"\aheaders\x18\x03 \x03(\v20.bridge.v1.ServerFacadeHttpResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x02\n" +
	"\x17ServerFacadeHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12I\n" +
	"\aheaders\x18\x04 \x03(\v2/.bridge.v1.ServerFacadeHttpRequest.HeadersEntryR\aheaders\x12C\n" +
	"\x05query\x18\x05 \x03(\v2-.bridge.v1.ServerFacadeHttpRequest.QueryEntryR\x05query\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x9b\x01\n" +
	"\rcom.bridge.v1B\x11ServerFacadeProtoP\x01Z2github.com/vercel/bridge/api/go/bridge/v1;bridgev1\xa2\x02\x03BXX\xaa\x02\tBridge.V1\xca\x02\tBridge\\V1\xe2\x02\x15Bridge\\V1\\GPBMetadata\xea\x02\n" +
	"Bridge::V1b\x06proto3"

var (
	file_bridge_v1_server_facade_proto_rawDescOnce sync.Once
	file_bridge_v1_server_facade_proto_rawDescData []byte
)

func file_bridge_v1_server_facade_proto_rawDescGZIP() []byte {
	file_bridge_v1_server_facade_proto_rawDescOnce.Do(func() {
		file_bridge_v1_server_facade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_server_facade_proto_rawDesc), len(file_bridge_v1_server_facade_proto_rawDesc)))
	})
	return file_bridge_v1_server_facade_proto_rawDescData
}

var file_bridge_v1_server_facade_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bridge_v1_server_facade_proto_goTypes = []any{
	(*ServerFacade)(nil),             // 0: bridge.v1.ServerFacade
	(*ServerFacadeRoute)(nil),        // 1: bridge.v1.ServerFacadeRoute
	(*ServerFacadeRouteMatch)(nil),   // 2: bridge.v1.ServerFacadeRouteMatch
	(*ServerFacadeAction)(nil),       // 3: bridge.v1.ServerFacadeAction
	(*ServerFacadeHttpResponse)(nil), // 4: bridge.v1.ServerFacadeHttpResponse
	(*ServerFacadeHttpRequest)(nil),  // 5: bridge.v1.ServerFacadeHttpRequest
	nil,                              // 6: bridge.v1.ServerFacadeHttpResponse.HeadersEntry
	nil,                              // 7: bridge.v1.ServerFacadeHttpRequest.HeadersEntry
	nil,                              // 8: bridge.v1.ServerFacadeHttpRequest.QueryEntry
	(*structpb.Value)(nil),           // 9: google.protobuf.Value
}
var file_bridge_v1_server_facade_proto_depIdxs = []int32{
	1, // 0: bridge.v1.ServerFacade.routes:type_name -> bridge.v1.ServerFacadeRoute
	2, // 1: bridge.v1.ServerFacadeRoute.match:type_name -> bridge.v1.ServerFacadeRouteMatch
	3, // 2: bridge.v1.ServerFacadeRoute.action:type_name -> bridge.v1.ServerFacadeAction
	4, // 3: bridge.v1.ServerFacadeAction.http_response:type_name -> bridge.v1.ServerFacadeHttpResponse
	9, // 4: bridge.v1.ServerFacadeHttpResponse.body:type_name -> google.protobuf.Value
	6, // 5: bridge.v1.ServerFacadeHttpResponse.headers:type_name -> bridge.v1.ServerFacadeHttpResponse.HeadersEntry
	7, // 6: bridge.v1.ServerFacadeHttpRequest.headers:type_name -> bridge.v1.ServerFacadeHttpRequest.HeadersEntry
	8, // 7: bridge.v1.ServerFacadeHttpRequest.query:type_name -> bridge.v1.ServerFacadeHttpRequest.QueryEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_bridge_v1_server_facade_proto_init() }
func file_bridge_v1_server_facade_proto_init() {
	if File_bridge_v1_server_facade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_server_facade_proto_rawDesc), len(file_bridge_v1_server_facade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_v1_server_facade_proto_goTypes,
		DependencyIndexes: file_bridge_v1_server_facade_proto_depIdxs,
		MessageInfos:      file_bridge_v1_server_facade_proto_msgTypes,
	}.Build()
	File_bridge_v1_server_facade_proto = out.File
	file_bridge_v1_server_facade_proto_goTypes = nil
	file_bridge_v1_server_facade_proto_depIdxs = nil
}
