// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge/v1/session.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session represents a local bridge session stored on the developer's machine.
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the bridge (e.g. "my-api-abc123").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// When the session was created.
	TimeCreated *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_created,proto3" json:"time_created,omitempty"`
	// The absolute path to the generated devcontainer.json for this bridge.
	DevcontainerConfigPath string `protobuf:"bytes,3,opt,name=devcontainer_config_path,proto3" json:"devcontainer_config_path,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_bridge_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_bridge_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetTimeCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeCreated
	}
	return nil
}

func (x *Session) GetDevcontainerConfigPath() string {
	if x != nil {
		return x.DevcontainerConfigPath
	}
	return ""
}

var File_bridge_v1_session_proto protoreflect.FileDescriptor

const file_bridge_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x17bridge/v1/session.proto\x12\tbridge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x01\n" +
	"\aSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\ftime_created\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ftime_created\x12:\n" +
	"\x18devcontainer_config_path\x18\x03 \x01(\tR\x18devcontainer_config_pathB\x96\x01\n" +
	"\rcom.bridge.v1B\fSessionProtoP\x01Z2github.com/vercel/bridge/api/go/bridge/v1;bridgev1\xa2\x02\x03BXX\xaa\x02\tBridge.V1\xca\x02\tBridge\\V1\xe2\x02\x15Bridge\\V1\\GPBMetadata\xea\x02\n" +
	"Bridge::V1b\x06proto3"

var (
	file_bridge_v1_session_proto_rawDescOnce sync.Once
	file_bridge_v1_session_proto_rawDescData []byte
)

func file_bridge_v1_session_proto_rawDescGZIP() []byte {
	file_bridge_v1_session_proto_rawDescOnce.Do(func() {
		file_bridge_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_session_proto_rawDesc), len(file_bridge_v1_session_proto_rawDesc)))
	})
	return file_bridge_v1_session_proto_rawDescData
}

var file_bridge_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bridge_v1_session_proto_goTypes = []any{
	(*Session)(nil),               // 0: bridge.v1.Session
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_bridge_v1_session_proto_depIdxs = []int32{
	1, // 0: bridge.v1.Session.time_created:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bridge_v1_session_proto_init() }
func file_bridge_v1_session_proto_init() {
	if File_bridge_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_session_proto_rawDesc), len(file_bridge_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_v1_session_proto_goTypes,
		DependencyIndexes: file_bridge_v1_session_proto_depIdxs,
		MessageInfos:      file_bridge_v1_session_proto_msgTypes,
	}.Build()
	File_bridge_v1_session_proto = out.File
	file_bridge_v1_session_proto_goTypes = nil
	file_bridge_v1_session_proto_depIdxs = nil
}
