// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bridgev1mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUnsafeAdministratorServiceServer creates a new instance of UnsafeAdministratorServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeAdministratorServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeAdministratorServiceServer {
	mock := &UnsafeAdministratorServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnsafeAdministratorServiceServer is an autogenerated mock type for the UnsafeAdministratorServiceServer type
type UnsafeAdministratorServiceServer struct {
	mock.Mock
}

type UnsafeAdministratorServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeAdministratorServiceServer) EXPECT() *UnsafeAdministratorServiceServer_Expecter {
	return &UnsafeAdministratorServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedAdministratorServiceServer provides a mock function for the type UnsafeAdministratorServiceServer
func (_mock *UnsafeAdministratorServiceServer) mustEmbedUnimplementedAdministratorServiceServer() {
	_mock.Called()
	return
}

// UnsafeAdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedAdministratorServiceServer'
type UnsafeAdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedAdministratorServiceServer is a helper method to define mock.On call
func (_e *UnsafeAdministratorServiceServer_Expecter) mustEmbedUnimplementedAdministratorServiceServer() *UnsafeAdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call {
	return &UnsafeAdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedAdministratorServiceServer")}
}

func (_c *UnsafeAdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call) Run(run func()) *UnsafeAdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeAdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call) Return() *UnsafeAdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeAdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call) RunAndReturn(run func()) *UnsafeAdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call {
	_c.Run(run)
	return _c
}
