// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bridgev1mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vercel/bridge/api/go/bridge/v1"
)

// NewAdministratorServiceServer creates a new instance of AdministratorServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdministratorServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdministratorServiceServer {
	mock := &AdministratorServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AdministratorServiceServer is an autogenerated mock type for the AdministratorServiceServer type
type AdministratorServiceServer struct {
	mock.Mock
}

type AdministratorServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *AdministratorServiceServer) EXPECT() *AdministratorServiceServer_Expecter {
	return &AdministratorServiceServer_Expecter{mock: &_m.Mock}
}

// CreateBridge provides a mock function for the type AdministratorServiceServer
func (_mock *AdministratorServiceServer) CreateBridge(context1 context.Context, createBridgeRequest *bridgev1.CreateBridgeRequest) (*bridgev1.CreateBridgeResponse, error) {
	ret := _mock.Called(context1, createBridgeRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateBridge")
	}

	var r0 *bridgev1.CreateBridgeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bridgev1.CreateBridgeRequest) (*bridgev1.CreateBridgeResponse, error)); ok {
		return returnFunc(context1, createBridgeRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bridgev1.CreateBridgeRequest) *bridgev1.CreateBridgeResponse); ok {
		r0 = returnFunc(context1, createBridgeRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bridgev1.CreateBridgeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bridgev1.CreateBridgeRequest) error); ok {
		r1 = returnFunc(context1, createBridgeRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdministratorServiceServer_CreateBridge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBridge'
type AdministratorServiceServer_CreateBridge_Call struct {
	*mock.Call
}

// CreateBridge is a helper method to define mock.On call
//   - context1 context.Context
//   - createBridgeRequest *bridgev1.CreateBridgeRequest
func (_e *AdministratorServiceServer_Expecter) CreateBridge(context1 interface{}, createBridgeRequest interface{}) *AdministratorServiceServer_CreateBridge_Call {
	return &AdministratorServiceServer_CreateBridge_Call{Call: _e.mock.On("CreateBridge", context1, createBridgeRequest)}
}

func (_c *AdministratorServiceServer_CreateBridge_Call) Run(run func(context1 context.Context, createBridgeRequest *bridgev1.CreateBridgeRequest)) *AdministratorServiceServer_CreateBridge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bridgev1.CreateBridgeRequest
		if args[1] != nil {
			arg1 = args[1].(*bridgev1.CreateBridgeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AdministratorServiceServer_CreateBridge_Call) Return(createBridgeResponse *bridgev1.CreateBridgeResponse, err error) *AdministratorServiceServer_CreateBridge_Call {
	_c.Call.Return(createBridgeResponse, err)
	return _c
}

func (_c *AdministratorServiceServer_CreateBridge_Call) RunAndReturn(run func(context1 context.Context, createBridgeRequest *bridgev1.CreateBridgeRequest) (*bridgev1.CreateBridgeResponse, error)) *AdministratorServiceServer_CreateBridge_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBridge provides a mock function for the type AdministratorServiceServer
func (_mock *AdministratorServiceServer) DeleteBridge(context1 context.Context, deleteBridgeRequest *bridgev1.DeleteBridgeRequest) (*bridgev1.DeleteBridgeResponse, error) {
	ret := _mock.Called(context1, deleteBridgeRequest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBridge")
	}

	var r0 *bridgev1.DeleteBridgeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bridgev1.DeleteBridgeRequest) (*bridgev1.DeleteBridgeResponse, error)); ok {
		return returnFunc(context1, deleteBridgeRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bridgev1.DeleteBridgeRequest) *bridgev1.DeleteBridgeResponse); ok {
		r0 = returnFunc(context1, deleteBridgeRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bridgev1.DeleteBridgeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bridgev1.DeleteBridgeRequest) error); ok {
		r1 = returnFunc(context1, deleteBridgeRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdministratorServiceServer_DeleteBridge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBridge'
type AdministratorServiceServer_DeleteBridge_Call struct {
	*mock.Call
}

// DeleteBridge is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteBridgeRequest *bridgev1.DeleteBridgeRequest
func (_e *AdministratorServiceServer_Expecter) DeleteBridge(context1 interface{}, deleteBridgeRequest interface{}) *AdministratorServiceServer_DeleteBridge_Call {
	return &AdministratorServiceServer_DeleteBridge_Call{Call: _e.mock.On("DeleteBridge", context1, deleteBridgeRequest)}
}

func (_c *AdministratorServiceServer_DeleteBridge_Call) Run(run func(context1 context.Context, deleteBridgeRequest *bridgev1.DeleteBridgeRequest)) *AdministratorServiceServer_DeleteBridge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bridgev1.DeleteBridgeRequest
		if args[1] != nil {
			arg1 = args[1].(*bridgev1.DeleteBridgeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AdministratorServiceServer_DeleteBridge_Call) Return(deleteBridgeResponse *bridgev1.DeleteBridgeResponse, err error) *AdministratorServiceServer_DeleteBridge_Call {
	_c.Call.Return(deleteBridgeResponse, err)
	return _c
}

func (_c *AdministratorServiceServer_DeleteBridge_Call) RunAndReturn(run func(context1 context.Context, deleteBridgeRequest *bridgev1.DeleteBridgeRequest) (*bridgev1.DeleteBridgeResponse, error)) *AdministratorServiceServer_DeleteBridge_Call {
	_c.Call.Return(run)
	return _c
}

// ListBridges provides a mock function for the type AdministratorServiceServer
func (_mock *AdministratorServiceServer) ListBridges(context1 context.Context, listBridgesRequest *bridgev1.ListBridgesRequest) (*bridgev1.ListBridgesResponse, error) {
	ret := _mock.Called(context1, listBridgesRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListBridges")
	}

	var r0 *bridgev1.ListBridgesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bridgev1.ListBridgesRequest) (*bridgev1.ListBridgesResponse, error)); ok {
		return returnFunc(context1, listBridgesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bridgev1.ListBridgesRequest) *bridgev1.ListBridgesResponse); ok {
		r0 = returnFunc(context1, listBridgesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bridgev1.ListBridgesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bridgev1.ListBridgesRequest) error); ok {
		r1 = returnFunc(context1, listBridgesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdministratorServiceServer_ListBridges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBridges'
type AdministratorServiceServer_ListBridges_Call struct {
	*mock.Call
}

// ListBridges is a helper method to define mock.On call
//   - context1 context.Context
//   - listBridgesRequest *bridgev1.ListBridgesRequest
func (_e *AdministratorServiceServer_Expecter) ListBridges(context1 interface{}, listBridgesRequest interface{}) *AdministratorServiceServer_ListBridges_Call {
	return &AdministratorServiceServer_ListBridges_Call{Call: _e.mock.On("ListBridges", context1, listBridgesRequest)}
}

func (_c *AdministratorServiceServer_ListBridges_Call) Run(run func(context1 context.Context, listBridgesRequest *bridgev1.ListBridgesRequest)) *AdministratorServiceServer_ListBridges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bridgev1.ListBridgesRequest
		if args[1] != nil {
			arg1 = args[1].(*bridgev1.ListBridgesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AdministratorServiceServer_ListBridges_Call) Return(listBridgesResponse *bridgev1.ListBridgesResponse, err error) *AdministratorServiceServer_ListBridges_Call {
	_c.Call.Return(listBridgesResponse, err)
	return _c
}

func (_c *AdministratorServiceServer_ListBridges_Call) RunAndReturn(run func(context1 context.Context, listBridgesRequest *bridgev1.ListBridgesRequest) (*bridgev1.ListBridgesResponse, error)) *AdministratorServiceServer_ListBridges_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedAdministratorServiceServer provides a mock function for the type AdministratorServiceServer
func (_mock *AdministratorServiceServer) mustEmbedUnimplementedAdministratorServiceServer() {
	_mock.Called()
	return
}

// AdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedAdministratorServiceServer'
type AdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedAdministratorServiceServer is a helper method to define mock.On call
func (_e *AdministratorServiceServer_Expecter) mustEmbedUnimplementedAdministratorServiceServer() *AdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call {
	return &AdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedAdministratorServiceServer")}
}

func (_c *AdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call) Run(run func()) *AdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call) Return() *AdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call) RunAndReturn(run func()) *AdministratorServiceServer_mustEmbedUnimplementedAdministratorServiceServer_Call {
	_c.Run(run)
	return _c
}
