// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/administrator.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bridge/v1/administrator.proto.
 */
export declare const file_bridge_v1_administrator: GenFile;

/**
 * CreateBridgeRequest is sent by the bridge CLI to the Administrator to provision a new bridge.
 *
 * @generated from message bridge.v1.CreateBridgeRequest
 */
export declare type CreateBridgeRequest = Message<"bridge.v1.CreateBridgeRequest"> & {
  /**
   * The KSUID identifying the developer's device (from ~/.bridge/device-id.txt).
   *
   * @generated from field: string device_id = 1 [json_name = "device_id"];
   */
  deviceId: string;

  /**
   * The name of the source Deployment to clone. If empty, the Administrator creates
   * a simple Deployment with just the bridge proxy container.
   *
   * @generated from field: string source_deployment = 2 [json_name = "source_deployment"];
   */
  sourceDeployment: string;

  /**
   * The namespace of the source Deployment. Required if source_deployment is set.
   *
   * @generated from field: string source_namespace = 3 [json_name = "source_namespace"];
   */
  sourceNamespace: string;

  /**
   * If true, tear down and recreate an existing bridge for the same deployment
   * without returning an ALREADY_EXISTS error.
   *
   * @generated from field: bool force = 4;
   */
  force: boolean;

  /**
   * The container image for the bridge proxy pod. If empty, the server uses
   * its configured default.
   *
   * @generated from field: string proxy_image = 5 [json_name = "proxy_image"];
   */
  proxyImage: string;

  /**
   * A tar.gz archive of Kubernetes YAML files to use as the bridge source.
   * When set, source_deployment becomes optional (used to select which
   * Deployment in the archive to bridge when multiple exist).
   *
   * @generated from field: bytes source_manifests = 6 [json_name = "source_manifests"];
   */
  sourceManifests: Uint8Array;
};

/**
 * Describes the message bridge.v1.CreateBridgeRequest.
 * Use `create(CreateBridgeRequestSchema)` to create a new message.
 */
export declare const CreateBridgeRequestSchema: GenMessage<CreateBridgeRequest>;

/**
 * CreateBridgeResponse is returned by the Administrator after a bridge is provisioned.
 *
 * @generated from message bridge.v1.CreateBridgeResponse
 */
export declare type CreateBridgeResponse = Message<"bridge.v1.CreateBridgeResponse"> & {
  /**
   * The namespace where the bridge resources were created (same as the source namespace).
   *
   * @generated from field: string namespace = 1;
   */
  namespace: string;

  /**
   * The name of the bridged pod.
   *
   * @generated from field: string pod_name = 2 [json_name = "pod_name"];
   */
  podName: string;

  /**
   * The port on the bridged pod where the bridge proxy server is listening.
   *
   * @generated from field: int32 port = 3;
   */
  port: number;

  /**
   * The name of the Deployment that owns the bridged pod.
   *
   * @generated from field: string deployment_name = 4 [json_name = "deployment_name"];
   */
  deploymentName: string;

  /**
   * Environment variables resolved from the source deployment's pod spec.
   *
   * @generated from field: map<string, string> env_vars = 5;
   */
  envVars: { [key: string]: string };

  /**
   * Absolute mount paths from the source deployment's application container.
   *
   * @generated from field: repeated string volume_mount_paths = 6;
   */
  volumeMountPaths: string[];

  /**
   * Container ports from the source deployment's application container.
   *
   * @generated from field: repeated int32 app_ports = 7;
   */
  appPorts: number[];
};

/**
 * Describes the message bridge.v1.CreateBridgeResponse.
 * Use `create(CreateBridgeResponseSchema)` to create a new message.
 */
export declare const CreateBridgeResponseSchema: GenMessage<CreateBridgeResponse>;

/**
 * ListBridgesRequest is sent to query active bridges.
 *
 * @generated from message bridge.v1.ListBridgesRequest
 */
export declare type ListBridgesRequest = Message<"bridge.v1.ListBridgesRequest"> & {
  /**
   * The device ID to list bridges for. Required.
   *
   * @generated from field: string device_id = 1 [json_name = "device_id"];
   */
  deviceId: string;
};

/**
 * Describes the message bridge.v1.ListBridgesRequest.
 * Use `create(ListBridgesRequestSchema)` to create a new message.
 */
export declare const ListBridgesRequestSchema: GenMessage<ListBridgesRequest>;

/**
 * BridgeInfo describes an active bridge.
 *
 * @generated from message bridge.v1.BridgeInfo
 */
export declare type BridgeInfo = Message<"bridge.v1.BridgeInfo"> & {
  /**
   * The device ID that owns this bridge.
   *
   * @generated from field: string device_id = 1 [json_name = "device_id"];
   */
  deviceId: string;

  /**
   * The source deployment this bridge was cloned from.
   *
   * @generated from field: string source_deployment = 2 [json_name = "source_deployment"];
   */
  sourceDeployment: string;

  /**
   * The source namespace of the deployment.
   *
   * @generated from field: string source_namespace = 3 [json_name = "source_namespace"];
   */
  sourceNamespace: string;

  /**
   * The namespace where the bridge is running.
   *
   * @generated from field: string namespace = 4;
   */
  namespace: string;

  /**
   * When the bridge was created (RFC 3339).
   *
   * @generated from field: string created_at = 5 [json_name = "created_at"];
   */
  createdAt: string;

  /**
   * Current status of the bridge (e.g., "running", "pending", "error").
   *
   * @generated from field: string status = 6;
   */
  status: string;

  /**
   * The name of the bridge Deployment.
   *
   * @generated from field: string deployment_name = 7 [json_name = "deployment_name"];
   */
  deploymentName: string;
};

/**
 * Describes the message bridge.v1.BridgeInfo.
 * Use `create(BridgeInfoSchema)` to create a new message.
 */
export declare const BridgeInfoSchema: GenMessage<BridgeInfo>;

/**
 * ListBridgesResponse contains all active bridges matching the filter.
 *
 * @generated from message bridge.v1.ListBridgesResponse
 */
export declare type ListBridgesResponse = Message<"bridge.v1.ListBridgesResponse"> & {
  /**
   * @generated from field: repeated bridge.v1.BridgeInfo bridges = 1;
   */
  bridges: BridgeInfo[];
};

/**
 * Describes the message bridge.v1.ListBridgesResponse.
 * Use `create(ListBridgesResponseSchema)` to create a new message.
 */
export declare const ListBridgesResponseSchema: GenMessage<ListBridgesResponse>;

/**
 * DeleteBridgeRequest identifies a bridge to tear down.
 *
 * @generated from message bridge.v1.DeleteBridgeRequest
 */
export declare type DeleteBridgeRequest = Message<"bridge.v1.DeleteBridgeRequest"> & {
  /**
   * The device ID that owns the bridge.
   *
   * @generated from field: string device_id = 1 [json_name = "device_id"];
   */
  deviceId: string;

  /**
   * The name of the bridge to delete.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * The namespace containing the bridge resources.
   *
   * @generated from field: string namespace = 3;
   */
  namespace: string;
};

/**
 * Describes the message bridge.v1.DeleteBridgeRequest.
 * Use `create(DeleteBridgeRequestSchema)` to create a new message.
 */
export declare const DeleteBridgeRequestSchema: GenMessage<DeleteBridgeRequest>;

/**
 * DeleteBridgeResponse is returned after a bridge is torn down.
 *
 * @generated from message bridge.v1.DeleteBridgeResponse
 */
export declare type DeleteBridgeResponse = Message<"bridge.v1.DeleteBridgeResponse"> & {
};

/**
 * Describes the message bridge.v1.DeleteBridgeResponse.
 * Use `create(DeleteBridgeResponseSchema)` to create a new message.
 */
export declare const DeleteBridgeResponseSchema: GenMessage<DeleteBridgeResponse>;

/**
 * AdministratorService manages bridge lifecycle in a Kubernetes cluster.
 *
 * @generated from service bridge.v1.AdministratorService
 */
export declare const AdministratorService: GenService<{
  /**
   * CreateBridge provisions a new bridge in the source deployment's namespace,
   * swapping the application container for the bridge proxy.
   *
   * @generated from rpc bridge.v1.AdministratorService.CreateBridge
   */
  createBridge: {
    methodKind: "unary";
    input: typeof CreateBridgeRequestSchema;
    output: typeof CreateBridgeResponseSchema;
  },
  /**
   * ListBridges returns all active bridges for a device across all namespaces.
   *
   * @generated from rpc bridge.v1.AdministratorService.ListBridges
   */
  listBridges: {
    methodKind: "unary";
    input: typeof ListBridgesRequestSchema;
    output: typeof ListBridgesResponseSchema;
  },
  /**
   * DeleteBridge tears down a specific bridge and its associated resources.
   *
   * @generated from rpc bridge.v1.AdministratorService.DeleteBridge
   */
  deleteBridge: {
    methodKind: "unary";
    input: typeof DeleteBridgeRequestSchema;
    output: typeof DeleteBridgeResponseSchema;
  },
}>;

