// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/bridge.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bridge/v1/bridge.proto.
 */
export const file_bridge_v1_bridge = /*@__PURE__*/
  fileDesc("ChZicmlkZ2UvdjEvYnJpZGdlLnByb3RvEglicmlkZ2UudjEiXAoQU2VydmVyQ29ubmVjdGlvbhIgCgtzYW5kYm94X3VybBgBIAEoCVILc2FuZGJveF91cmwSJgoOY29ubmVjdGlvbl9rZXkYAiABKAlSDmNvbm5lY3Rpb25fa2V5IqsECgdNZXNzYWdlEjoKDHJlZ2lzdHJhdGlvbhgBIAEoCzIfLmJyaWRnZS52MS5NZXNzYWdlLlJlZ2lzdHJhdGlvbkgAiAEBEioKBnNvdXJjZRgCIAEoCzIaLmJyaWRnZS52MS5NZXNzYWdlLkFkZHJlc3MSKAoEZGVzdBgDIAEoCzIaLmJyaWRnZS52MS5NZXNzYWdlLkFkZHJlc3MSDAoEZGF0YRgEIAEoDBIkCg1jb25uZWN0aW9uX2lkGAUgASgJUg1jb25uZWN0aW9uX2lkEg0KBWNsb3NlGAYgASgIEg0KBWVycm9yGAcgASgJGiMKB0FkZHJlc3MSCgoCaXAYASABKAkSDAoEcG9ydBgCIAEoBRq7AQoMUmVnaXN0cmF0aW9uEhwKCWlzX3NlcnZlchgBIAEoCFIJaXNfc2VydmVyEi0KCHByb3RvY29sGAIgASgOMhsuYnJpZGdlLnYxLk1lc3NhZ2UuUHJvdG9jb2wSIgoMZnVuY3Rpb25fdXJsGAMgASgJUgxmdW5jdGlvbl91cmwSOgoYcHJvdGVjdGlvbl9ieXBhc3Nfc2VjcmV0GAQgASgJUhhwcm90ZWN0aW9uX2J5cGFzc19zZWNyZXQiSAoIUHJvdG9jb2wSGAoUUFJPVE9DT0xfVU5TUEVDSUZJRUQQABIQCgxQUk9UT0NPTF9UQ1AQARIQCgxQUk9UT0NPTF9VRFAQAkIPCg1fcmVnaXN0cmF0aW9uQpsBCg1jb20uYnJpZGdlLnYxQgtCcmlkZ2VQcm90b1ABWjhnaXRodWIuY29tL3ZlcmNlbC1lZGRpZS9icmlkZ2UvYXBpL2dvL2JyaWRnZS92MTticmlkZ2V2MaICA0JYWKoCCUJyaWRnZS5WMcoCCUJyaWRnZVxWMeICFUJyaWRnZVxWMVxHUEJNZXRhZGF0YeoCCkJyaWRnZTo6VjFiBnByb3RvMw");

/**
 * Describes the message bridge.v1.ServerConnection.
 * Use `create(ServerConnectionSchema)` to create a new message.
 */
export const ServerConnectionSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 0);

/**
 * Describes the message bridge.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 1);

/**
 * Describes the message bridge.v1.Message.Address.
 * Use `create(Message_AddressSchema)` to create a new message.
 */
export const Message_AddressSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 1, 0);

/**
 * Describes the message bridge.v1.Message.Registration.
 * Use `create(Message_RegistrationSchema)` to create a new message.
 */
export const Message_RegistrationSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 1, 1);

/**
 * Describes the enum bridge.v1.Message.Protocol.
 */
export const Message_ProtocolSchema = /*@__PURE__*/
  enumDesc(file_bridge_v1_bridge, 1, 0);

/**
 * @generated from enum bridge.v1.Message.Protocol
 */
export const Message_Protocol = /*@__PURE__*/
  tsEnum(Message_ProtocolSchema);

