// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file bridge/v1/bridge.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bridge/v1/bridge.proto.
 */
export const file_bridge_v1_bridge = /*@__PURE__*/
  fileDesc("ChZicmlkZ2UvdjEvYnJpZGdlLnByb3RvEglicmlkZ2UudjEioAIKB01lc3NhZ2USKgoGc291cmNlGAIgASgLMhouYnJpZGdlLnYxLk1lc3NhZ2UuQWRkcmVzcxIoCgRkZXN0GAMgASgLMhouYnJpZGdlLnYxLk1lc3NhZ2UuQWRkcmVzcxIMCgRkYXRhGAQgASgMEiQKDWNvbm5lY3Rpb25faWQYBSABKAlSDWNvbm5lY3Rpb25faWQSDQoFY2xvc2UYBiABKAgSDQoFZXJyb3IYByABKAkaIwoHQWRkcmVzcxIKCgJpcBgBIAEoCRIMCgRwb3J0GAIgASgFIkgKCFByb3RvY29sEhgKFFBST1RPQ09MX1VOU1BFQ0lGSUVEEAASEAoMUFJPVE9DT0xfVENQEAESEAoMUFJPVE9DT0xfVURQEAJClQEKDWNvbS5icmlkZ2UudjFCC0JyaWRnZVByb3RvUAFaMmdpdGh1Yi5jb20vdmVyY2VsL2JyaWRnZS9hcGkvZ28vYnJpZGdlL3YxO2JyaWRnZXYxogIDQlhYqgIJQnJpZGdlLlYxygIJQnJpZGdlXFYx4gIVQnJpZGdlXFYxXEdQQk1ldGFkYXRh6gIKQnJpZGdlOjpWMWIGcHJvdG8z");

/**
 * Describes the message bridge.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 0);

/**
 * Describes the message bridge.v1.Message.Address.
 * Use `create(Message_AddressSchema)` to create a new message.
 */
export const Message_AddressSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 0, 0);

/**
 * Describes the enum bridge.v1.Message.Protocol.
 */
export const Message_ProtocolSchema = /*@__PURE__*/
  enumDesc(file_bridge_v1_bridge, 0, 0);

/**
 * @generated from enum bridge.v1.Message.Protocol
 */
export const Message_Protocol = /*@__PURE__*/
  tsEnum(Message_ProtocolSchema);

