// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file bridge/v1/bridge.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file bridge/v1/bridge.proto.
 */
export declare const file_bridge_v1_bridge: GenFile;

/**
 * Message is the unit of communication through the bridge tunnel.
 *
 * @generated from message bridge.v1.Message
 */
export declare type Message = Message$1<"bridge.v1.Message"> & {
  /**
   * The address that is sending the message.
   *
   * @generated from field: bridge.v1.Message.Address source = 2;
   */
  source?: Message_Address | undefined;

  /**
   * The intended target address on the destination.
   *
   * @generated from field: bridge.v1.Message.Address dest = 3;
   */
  dest?: Message_Address | undefined;

  /**
   * The payload data being tunneled.
   *
   * @generated from field: bytes data = 4;
   */
  data: Uint8Array;

  /**
   * Connection ID for multiplexing multiple connections over one tunnel.
   *
   * @generated from field: string connection_id = 5 [json_name = "connection_id"];
   */
  connectionId: string;

  /**
   * Set to true when the connection should be closed.
   *
   * @generated from field: bool close = 6;
   */
  close: boolean;

  /**
   * Error message if something went wrong.
   *
   * @generated from field: string error = 7;
   */
  error: string;
};

/**
 * Describes the message bridge.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * @generated from message bridge.v1.Message.Address
 */
export declare type Message_Address = Message$1<"bridge.v1.Message.Address"> & {
  /**
   * @generated from field: string ip = 1;
   */
  ip: string;

  /**
   * @generated from field: int32 port = 2;
   */
  port: number;
};

/**
 * Describes the message bridge.v1.Message.Address.
 * Use `create(Message_AddressSchema)` to create a new message.
 */
export declare const Message_AddressSchema: GenMessage<Message_Address>;

/**
 * @generated from enum bridge.v1.Message.Protocol
 */
export enum Message_Protocol {
  /**
   * @generated from enum value: PROTOCOL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PROTOCOL_TCP = 1;
   */
  TCP = 1,

  /**
   * @generated from enum value: PROTOCOL_UDP = 2;
   */
  UDP = 2,
}

/**
 * Describes the enum bridge.v1.Message.Protocol.
 */
export declare const Message_ProtocolSchema: GenEnum<Message_Protocol>;

