// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file bridge/v1/command.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Value } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file bridge/v1/command.proto.
 */
export declare const file_bridge_v1_command: GenFile;

/**
 * CommandResultOutcome wraps the outcome enum so values serialize as
 * "success" and "error" without a package prefix.
 *
 * @generated from message bridge.v1.CommandResultOutcome
 */
export declare type CommandResultOutcome = Message<"bridge.v1.CommandResultOutcome"> & {
};

/**
 * Describes the message bridge.v1.CommandResultOutcome.
 * Use `create(CommandResultOutcomeSchema)` to create a new message.
 */
export declare const CommandResultOutcomeSchema: GenMessage<CommandResultOutcome>;

/**
 * buf:lint:ignore ENUM_VALUE_PREFIX
 * buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
 * buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
 *
 * @generated from enum bridge.v1.CommandResultOutcome.Enum
 */
export enum CommandResultOutcome_Enum {
  /**
   * @generated from enum value: unspecified = 0;
   */
  unspecified = 0,

  /**
   * @generated from enum value: success = 1;
   */
  success = 1,

  /**
   * @generated from enum value: error = 2;
   */
  error = 2,
}

/**
 * Describes the enum bridge.v1.CommandResultOutcome.Enum.
 */
export declare const CommandResultOutcome_EnumSchema: GenEnum<CommandResultOutcome_Enum>;

/**
 * CommandResult is the envelope for all JSON-mode command output.
 * On success, response contains the command-specific payload.
 * On failure, error contains the error message.
 *
 * @generated from message bridge.v1.CommandResult
 */
export declare type CommandResult = Message<"bridge.v1.CommandResult"> & {
  /**
   * Whether the command succeeded or failed.
   *
   * @generated from field: bridge.v1.CommandResultOutcome.Enum outcome = 1;
   */
  outcome: CommandResultOutcome_Enum;

  /**
   * Error message. Absent on success.
   *
   * @generated from field: optional string error = 2;
   */
  error?: string | undefined;

  /**
   * Command-specific response payload. Absent on error.
   *
   * @generated from field: optional google.protobuf.Value response = 3;
   */
  response?: Value | undefined;
};

/**
 * Describes the message bridge.v1.CommandResult.
 * Use `create(CommandResultSchema)` to create a new message.
 */
export declare const CommandResultSchema: GenMessage<CommandResult>;

/**
 * CreateCommandPayload represents the flags for the "create" command.
 * Used both as the CEL evaluation context and as the flag values to apply.
 *
 * @generated from message bridge.v1.CreateCommandPayload
 */
export declare type CreateCommandPayload = Message<"bridge.v1.CreateCommandPayload"> & {
  /**
   * Positional argument: name of the target workload (defaults to a Deployment).
   *
   * @generated from field: string workload_name = 1 [json_name = "workload_name"];
   */
  workloadName: string;

  /**
   * --namespace / -n: target namespace of the source deployment.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * --server-facade: server facade specs (JSON string or file path). Repeated.
   *
   * @generated from field: repeated string server_facades = 3 [json_name = "server_facades"];
   */
  serverFacades: string[];

  /**
   * --source / -s: path to Kubernetes manifests (folder, glob, or YAML file).
   *
   * @generated from field: string source = 4;
   */
  source: string;

  /**
   * --listen / -l: port the app listens on.
   *
   * @generated from field: int32 listen = 5;
   */
  listen: number;

  /**
   * --connect / -c: start the devcontainer and exec into it after creation.
   *
   * @generated from field: bool connect = 6;
   */
  connect: boolean;

  /**
   * --devcontainer-config / -f: path to a base devcontainer.json to extend.
   *
   * @generated from field: string devcontainer_config = 7 [json_name = "devcontainer_config"];
   */
  devcontainerConfig: string;

  /**
   * --devcontainer-up-args: additional arguments passed to devcontainer up.
   *
   * @generated from field: string devcontainer_up_args = 8 [json_name = "devcontainer_up_args"];
   */
  devcontainerUpArgs: string;

  /**
   * --name: bridge name (defaults to workload_name).
   *
   * @generated from field: string name = 9;
   */
  name: string;
};

/**
 * Describes the message bridge.v1.CreateCommandPayload.
 * Use `create(CreateCommandPayloadSchema)` to create a new message.
 */
export declare const CreateCommandPayloadSchema: GenMessage<CreateCommandPayload>;

/**
 * CreateCommandResponse is the structured output emitted by the "create"
 * command when running in agent mode without --connect.
 *
 * @generated from message bridge.v1.CreateCommandResponse
 */
export declare type CreateCommandResponse = Message<"bridge.v1.CreateCommandResponse"> & {
  /**
   * The container port the application listens on.
   *
   * @generated from field: int32 app_port = 1 [json_name = "app_port"];
   */
  appPort: number;

  /**
   * The resolved host port mapped to the app port (may differ if the
   * requested port was already in use).
   *
   * @generated from field: int32 host_app_port = 6 [json_name = "host_app_port"];
   */
  hostAppPort: number;

  /**
   * Absolute path to the generated devcontainer.json.
   *
   * @generated from field: string devcontainer_config_path = 2 [json_name = "devcontainer_config_path"];
   */
  devcontainerConfigPath: string;

  /**
   * The bridge name.
   *
   * @generated from field: string bridge_name = 3 [json_name = "bridge_name"];
   */
  bridgeName: string;

  /**
   * The source deployment name.
   *
   * @generated from field: string source_deployment = 4 [json_name = "source_deployment"];
   */
  sourceDeployment: string;

  /**
   * Port mappings: key is the label (e.g. "app", "intercept"), value is the port number.
   *
   * @generated from field: map<string, int32> ports = 5;
   */
  ports: { [key: string]: number };
};

/**
 * Describes the message bridge.v1.CreateCommandResponse.
 * Use `create(CreateCommandResponseSchema)` to create a new message.
 */
export declare const CreateCommandResponseSchema: GenMessage<CreateCommandResponse>;

/**
 * GetCommandResponseBridge describes a single bridge in the get command output.
 *
 * @generated from message bridge.v1.GetCommandResponseBridge
 */
export declare type GetCommandResponseBridge = Message<"bridge.v1.GetCommandResponseBridge"> & {
  /**
   * The bridge name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The source deployment this bridge was cloned from.
   *
   * @generated from field: string source_deployment = 2 [json_name = "source_deployment"];
   */
  sourceDeployment: string;

  /**
   * The source namespace of the deployment.
   *
   * @generated from field: string source_namespace = 3 [json_name = "source_namespace"];
   */
  sourceNamespace: string;

  /**
   * The namespace where the bridge is running.
   *
   * @generated from field: string namespace = 4;
   */
  namespace: string;

  /**
   * When the bridge was created (RFC 3339).
   *
   * @generated from field: string created_at = 5 [json_name = "created_at"];
   */
  createdAt: string;

  /**
   * Current status of the bridge in the cluster (e.g. "running", "pending").
   *
   * @generated from field: string status = 6;
   */
  status: string;

  /**
   * The name of the bridge Deployment.
   *
   * @generated from field: string deployment_name = 7 [json_name = "deployment_name"];
   */
  deploymentName: string;

  /**
   * Status of the developer's local application as reported by the
   * interceptor's probe monitors. One of:
   *   - "stopped"      — no devcontainer is running for this bridge
   *   - "unreachable"  — devcontainer is up but the interceptor isn't responding
   *   - "starting"     — interceptor is still initializing, or probes are pending
   *   - "no probes"    — source deployment didn't declare liveness/readiness/startup
   *   - "healthy"      — every configured probe reports healthy
   *   - "unhealthy"    — at least one configured probe reports unhealthy
   *
   * @generated from field: string application_status = 8 [json_name = "application_status"];
   */
  applicationStatus: string;
};

/**
 * Describes the message bridge.v1.GetCommandResponseBridge.
 * Use `create(GetCommandResponseBridgeSchema)` to create a new message.
 */
export declare const GetCommandResponseBridgeSchema: GenMessage<GetCommandResponseBridge>;

/**
 * GetCommandResponse is the structured output emitted by the "get" command
 * when running in JSON output mode.
 *
 * @generated from message bridge.v1.GetCommandResponse
 */
export declare type GetCommandResponse = Message<"bridge.v1.GetCommandResponse"> & {
  /**
   * @generated from field: repeated bridge.v1.GetCommandResponseBridge bridges = 1;
   */
  bridges: GetCommandResponseBridge[];
};

/**
 * Describes the message bridge.v1.GetCommandResponse.
 * Use `create(GetCommandResponseSchema)` to create a new message.
 */
export declare const GetCommandResponseSchema: GenMessage<GetCommandResponse>;

/**
 * RemoveCommandResponse is the structured output emitted by the "remove"
 * command when running in JSON output mode.
 *
 * @generated from message bridge.v1.RemoveCommandResponse
 */
export declare type RemoveCommandResponse = Message<"bridge.v1.RemoveCommandResponse"> & {
  /**
   * Names of bridges that were successfully removed.
   *
   * @generated from field: repeated string removed = 1;
   */
  removed: string[];
};

/**
 * Describes the message bridge.v1.RemoveCommandResponse.
 * Use `create(RemoveCommandResponseSchema)` to create a new message.
 */
export declare const RemoveCommandResponseSchema: GenMessage<RemoveCommandResponse>;

/**
 * DevCommandReason describes why `bridge dev` returned.
 *
 * @generated from message bridge.v1.DevCommandReason
 */
export declare type DevCommandReason = Message<"bridge.v1.DevCommandReason"> & {
};

/**
 * Describes the message bridge.v1.DevCommandReason.
 * Use `create(DevCommandReasonSchema)` to create a new message.
 */
export declare const DevCommandReasonSchema: GenMessage<DevCommandReason>;

/**
 * buf:lint:ignore ENUM_VALUE_PREFIX
 * buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
 * buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
 *
 * @generated from enum bridge.v1.DevCommandReason.Enum
 */
export enum DevCommandReason_Enum {
  /**
   * @generated from enum value: unspecified = 0;
   */
  unspecified = 0,

  /**
   * All configured liveness/readiness probes reported healthy.
   *
   * @generated from enum value: healthy = 1;
   */
  healthy = 1,

  /**
   * The dev command exited before reaching a healthy state.
   *
   * @generated from enum value: exited = 2;
   */
  exited = 2,

  /**
   * --timeout elapsed before health or exit.
   *
   * @generated from enum value: timeout = 3;
   */
  timeout = 3,
}

/**
 * Describes the enum bridge.v1.DevCommandReason.Enum.
 */
export declare const DevCommandReason_EnumSchema: GenEnum<DevCommandReason_Enum>;

/**
 * DevCommandResponse is the structured output emitted by the "dev" command
 * when running in JSON output mode.
 *
 * @generated from message bridge.v1.DevCommandResponse
 */
export declare type DevCommandResponse = Message<"bridge.v1.DevCommandResponse"> & {
  /**
   * The bridge name the dev command was run against.
   *
   * @generated from field: string bridge_name = 1 [json_name = "bridge_name"];
   */
  bridgeName: string;

  /**
   * PID inside the devcontainer of the dev process. Always populated once
   * the command starts running, even if it later exits or times out.
   *
   * @generated from field: int32 pid = 2;
   */
  pid: number;

  /**
   * The exact command line that was launched (from devcontainer.json
   * `devCommand`).
   *
   * @generated from field: string command = 3;
   */
  command: string;

  /**
   * Why the call returned. See DevCommandReason.
   *
   * @generated from field: bridge.v1.DevCommandReason.Enum reason = 4;
   */
  reason: DevCommandReason_Enum;

  /**
   * Exit code of the dev process. Only populated when reason == exited.
   *
   * @generated from field: optional int32 exit_code = 5 [json_name = "exit_code"];
   */
  exitCode?: number | undefined;

  /**
   * Absolute path inside the devcontainer to the dev process's stdout/stderr
   * log file. Useful for debugging when the dev command exits unhealthy.
   *
   * @generated from field: string log_path = 6 [json_name = "log_path"];
   */
  logPath: string;
};

/**
 * Describes the message bridge.v1.DevCommandResponse.
 * Use `create(DevCommandResponseSchema)` to create a new message.
 */
export declare const DevCommandResponseSchema: GenMessage<DevCommandResponse>;

