// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file bridge/v1/filesystem.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bridge/v1/filesystem.proto.
 */
export declare const file_bridge_v1_filesystem: GenFile;

/**
 * FileAttr describes a single inode.
 *
 * @generated from message bridge.v1.FileAttr
 */
export declare type FileAttr = Message<"bridge.v1.FileAttr"> & {
  /**
   * POSIX mode (permission bits + type). Only the low 12 bits are meaningful
   * for permissions; the type is reported separately via the type field.
   *
   * @generated from field: uint32 mode = 1;
   */
  mode: number;

  /**
   * File size in bytes (0 for non-regular files).
   *
   * @generated from field: int64 size = 2;
   */
  size: bigint;

  /**
   * Modification time as Unix seconds.
   *
   * @generated from field: int64 mod_time = 3;
   */
  modTime: bigint;

  /**
   * File type.
   *
   * @generated from field: bridge.v1.FileType type = 4;
   */
  type: FileType;
};

/**
 * Describes the message bridge.v1.FileAttr.
 * Use `create(FileAttrSchema)` to create a new message.
 */
export declare const FileAttrSchema: GenMessage<FileAttr>;

/**
 * @generated from message bridge.v1.StatRequest
 */
export declare type StatRequest = Message<"bridge.v1.StatRequest"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;
};

/**
 * Describes the message bridge.v1.StatRequest.
 * Use `create(StatRequestSchema)` to create a new message.
 */
export declare const StatRequestSchema: GenMessage<StatRequest>;

/**
 * @generated from message bridge.v1.StatResponse
 */
export declare type StatResponse = Message<"bridge.v1.StatResponse"> & {
  /**
   * @generated from field: bridge.v1.FileAttr attr = 1;
   */
  attr?: FileAttr | undefined;
};

/**
 * Describes the message bridge.v1.StatResponse.
 * Use `create(StatResponseSchema)` to create a new message.
 */
export declare const StatResponseSchema: GenMessage<StatResponse>;

/**
 * @generated from message bridge.v1.ReadDirRequest
 */
export declare type ReadDirRequest = Message<"bridge.v1.ReadDirRequest"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;
};

/**
 * Describes the message bridge.v1.ReadDirRequest.
 * Use `create(ReadDirRequestSchema)` to create a new message.
 */
export declare const ReadDirRequestSchema: GenMessage<ReadDirRequest>;

/**
 * @generated from message bridge.v1.DirEntry
 */
export declare type DirEntry = Message<"bridge.v1.DirEntry"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: bridge.v1.FileType type = 2;
   */
  type: FileType;

  /**
   * @generated from field: uint32 mode = 3;
   */
  mode: number;
};

/**
 * Describes the message bridge.v1.DirEntry.
 * Use `create(DirEntrySchema)` to create a new message.
 */
export declare const DirEntrySchema: GenMessage<DirEntry>;

/**
 * @generated from message bridge.v1.ReadDirResponse
 */
export declare type ReadDirResponse = Message<"bridge.v1.ReadDirResponse"> & {
  /**
   * @generated from field: repeated bridge.v1.DirEntry entries = 1;
   */
  entries: DirEntry[];
};

/**
 * Describes the message bridge.v1.ReadDirResponse.
 * Use `create(ReadDirResponseSchema)` to create a new message.
 */
export declare const ReadDirResponseSchema: GenMessage<ReadDirResponse>;

/**
 * @generated from message bridge.v1.ReadFileRequest
 */
export declare type ReadFileRequest = Message<"bridge.v1.ReadFileRequest"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * Byte offset to start reading at.
   *
   * @generated from field: int64 offset = 2;
   */
  offset: bigint;

  /**
   * Maximum number of bytes to read. Server may return fewer at EOF.
   *
   * @generated from field: int64 size = 3;
   */
  size: bigint;
};

/**
 * Describes the message bridge.v1.ReadFileRequest.
 * Use `create(ReadFileRequestSchema)` to create a new message.
 */
export declare const ReadFileRequestSchema: GenMessage<ReadFileRequest>;

/**
 * @generated from message bridge.v1.ReadFileResponse
 */
export declare type ReadFileResponse = Message<"bridge.v1.ReadFileResponse"> & {
  /**
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;

  /**
   * True when offset+len(data) reaches the end of the file.
   *
   * @generated from field: bool eof = 2;
   */
  eof: boolean;
};

/**
 * Describes the message bridge.v1.ReadFileResponse.
 * Use `create(ReadFileResponseSchema)` to create a new message.
 */
export declare const ReadFileResponseSchema: GenMessage<ReadFileResponse>;

/**
 * @generated from message bridge.v1.ReadLinkRequest
 */
export declare type ReadLinkRequest = Message<"bridge.v1.ReadLinkRequest"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;
};

/**
 * Describes the message bridge.v1.ReadLinkRequest.
 * Use `create(ReadLinkRequestSchema)` to create a new message.
 */
export declare const ReadLinkRequestSchema: GenMessage<ReadLinkRequest>;

/**
 * @generated from message bridge.v1.ReadLinkResponse
 */
export declare type ReadLinkResponse = Message<"bridge.v1.ReadLinkResponse"> & {
  /**
   * @generated from field: string target = 1;
   */
  target: string;
};

/**
 * Describes the message bridge.v1.ReadLinkResponse.
 * Use `create(ReadLinkResponseSchema)` to create a new message.
 */
export declare const ReadLinkResponseSchema: GenMessage<ReadLinkResponse>;

/**
 * FileType matches POSIX file type bits.
 *
 * @generated from enum bridge.v1.FileType
 */
export enum FileType {
  /**
   * @generated from enum value: FILE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: FILE_TYPE_REGULAR = 1;
   */
  REGULAR = 1,

  /**
   * @generated from enum value: FILE_TYPE_DIR = 2;
   */
  DIR = 2,

  /**
   * @generated from enum value: FILE_TYPE_SYMLINK = 3;
   */
  SYMLINK = 3,
}

/**
 * Describes the enum bridge.v1.FileType.
 */
export declare const FileTypeSchema: GenEnum<FileType>;

/**
 * BridgeFileSystemService serves a read-only view of allowed paths on the
 * bridge proxy pod so the local devcontainer can FUSE-mount them. Operations
 * are stateless: each RPC takes an absolute path and the server enforces an
 * allowlist of mount roots configured at startup.
 *
 * @generated from service bridge.v1.BridgeFileSystemService
 */
export declare const BridgeFileSystemService: GenService<{
  /**
   * Stat returns metadata for a single path.
   *
   * @generated from rpc bridge.v1.BridgeFileSystemService.Stat
   */
  stat: {
    methodKind: "unary";
    input: typeof StatRequestSchema;
    output: typeof StatResponseSchema;
  },
  /**
   * ReadDir lists entries in a directory.
   *
   * @generated from rpc bridge.v1.BridgeFileSystemService.ReadDir
   */
  readDir: {
    methodKind: "unary";
    input: typeof ReadDirRequestSchema;
    output: typeof ReadDirResponseSchema;
  },
  /**
   * ReadFile reads a byte range of a regular file. Clients chunk large reads
   * by issuing multiple requests with successive offsets.
   *
   * @generated from rpc bridge.v1.BridgeFileSystemService.ReadFile
   */
  readFile: {
    methodKind: "unary";
    input: typeof ReadFileRequestSchema;
    output: typeof ReadFileResponseSchema;
  },
  /**
   * ReadLink returns the target of a symbolic link.
   *
   * @generated from rpc bridge.v1.BridgeFileSystemService.ReadLink
   */
  readLink: {
    methodKind: "unary";
    input: typeof ReadLinkRequestSchema;
    output: typeof ReadLinkResponseSchema;
  },
}>;

