// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file bridge/v1/filesystem.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bridge/v1/filesystem.proto.
 */
export const file_bridge_v1_filesystem = /*@__PURE__*/
  fileDesc("ChpicmlkZ2UvdjEvZmlsZXN5c3RlbS5wcm90bxIJYnJpZGdlLnYxIlsKCEZpbGVBdHRyEgwKBG1vZGUYASABKA0SDAoEc2l6ZRgCIAEoAxIQCghtb2RfdGltZRgDIAEoAxIhCgR0eXBlGAQgASgOMhMuYnJpZGdlLnYxLkZpbGVUeXBlIhsKC1N0YXRSZXF1ZXN0EgwKBHBhdGgYASABKAkiMQoMU3RhdFJlc3BvbnNlEiEKBGF0dHIYASABKAsyEy5icmlkZ2UudjEuRmlsZUF0dHIiHgoOUmVhZERpclJlcXVlc3QSDAoEcGF0aBgBIAEoCSJJCghEaXJFbnRyeRIMCgRuYW1lGAEgASgJEiEKBHR5cGUYAiABKA4yEy5icmlkZ2UudjEuRmlsZVR5cGUSDAoEbW9kZRgDIAEoDSI3Cg9SZWFkRGlyUmVzcG9uc2USJAoHZW50cmllcxgBIAMoCzITLmJyaWRnZS52MS5EaXJFbnRyeSI9Cg9SZWFkRmlsZVJlcXVlc3QSDAoEcGF0aBgBIAEoCRIOCgZvZmZzZXQYAiABKAMSDAoEc2l6ZRgDIAEoAyItChBSZWFkRmlsZVJlc3BvbnNlEgwKBGRhdGEYASABKAwSCwoDZW9mGAIgASgIIh8KD1JlYWRMaW5rUmVxdWVzdBIMCgRwYXRoGAEgASgJIiIKEFJlYWRMaW5rUmVzcG9uc2USDgoGdGFyZ2V0GAEgASgJKmYKCEZpbGVUeXBlEhkKFUZJTEVfVFlQRV9VTlNQRUNJRklFRBAAEhUKEUZJTEVfVFlQRV9SRUdVTEFSEAESEQoNRklMRV9UWVBFX0RJUhACEhUKEUZJTEVfVFlQRV9TWU1MSU5LEAMyngIKF0JyaWRnZUZpbGVTeXN0ZW1TZXJ2aWNlEjcKBFN0YXQSFi5icmlkZ2UudjEuU3RhdFJlcXVlc3QaFy5icmlkZ2UudjEuU3RhdFJlc3BvbnNlEkAKB1JlYWREaXISGS5icmlkZ2UudjEuUmVhZERpclJlcXVlc3QaGi5icmlkZ2UudjEuUmVhZERpclJlc3BvbnNlEkMKCFJlYWRGaWxlEhouYnJpZGdlLnYxLlJlYWRGaWxlUmVxdWVzdBobLmJyaWRnZS52MS5SZWFkRmlsZVJlc3BvbnNlEkMKCFJlYWRMaW5rEhouYnJpZGdlLnYxLlJlYWRMaW5rUmVxdWVzdBobLmJyaWRnZS52MS5SZWFkTGlua1Jlc3BvbnNlQpkBCg1jb20uYnJpZGdlLnYxQg9GaWxlc3lzdGVtUHJvdG9QAVoyZ2l0aHViLmNvbS92ZXJjZWwvYnJpZGdlL2FwaS9nby9icmlkZ2UvdjE7YnJpZGdldjGiAgNCWFiqAglCcmlkZ2UuVjHKAglCcmlkZ2VcVjHiAhVCcmlkZ2VcVjFcR1BCTWV0YWRhdGHqAgpCcmlkZ2U6OlYxYgZwcm90bzM");

/**
 * Describes the message bridge.v1.FileAttr.
 * Use `create(FileAttrSchema)` to create a new message.
 */
export const FileAttrSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_filesystem, 0);

/**
 * Describes the message bridge.v1.StatRequest.
 * Use `create(StatRequestSchema)` to create a new message.
 */
export const StatRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_filesystem, 1);

/**
 * Describes the message bridge.v1.StatResponse.
 * Use `create(StatResponseSchema)` to create a new message.
 */
export const StatResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_filesystem, 2);

/**
 * Describes the message bridge.v1.ReadDirRequest.
 * Use `create(ReadDirRequestSchema)` to create a new message.
 */
export const ReadDirRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_filesystem, 3);

/**
 * Describes the message bridge.v1.DirEntry.
 * Use `create(DirEntrySchema)` to create a new message.
 */
export const DirEntrySchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_filesystem, 4);

/**
 * Describes the message bridge.v1.ReadDirResponse.
 * Use `create(ReadDirResponseSchema)` to create a new message.
 */
export const ReadDirResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_filesystem, 5);

/**
 * Describes the message bridge.v1.ReadFileRequest.
 * Use `create(ReadFileRequestSchema)` to create a new message.
 */
export const ReadFileRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_filesystem, 6);

/**
 * Describes the message bridge.v1.ReadFileResponse.
 * Use `create(ReadFileResponseSchema)` to create a new message.
 */
export const ReadFileResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_filesystem, 7);

/**
 * Describes the message bridge.v1.ReadLinkRequest.
 * Use `create(ReadLinkRequestSchema)` to create a new message.
 */
export const ReadLinkRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_filesystem, 8);

/**
 * Describes the message bridge.v1.ReadLinkResponse.
 * Use `create(ReadLinkResponseSchema)` to create a new message.
 */
export const ReadLinkResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_filesystem, 9);

/**
 * Describes the enum bridge.v1.FileType.
 */
export const FileTypeSchema = /*@__PURE__*/
  enumDesc(file_bridge_v1_filesystem, 0);

/**
 * FileType matches POSIX file type bits.
 *
 * @generated from enum bridge.v1.FileType
 */
export const FileType = /*@__PURE__*/
  tsEnum(FileTypeSchema);

/**
 * BridgeFileSystemService serves a read-only view of allowed paths on the
 * bridge proxy pod so the local devcontainer can FUSE-mount them. Operations
 * are stateless: each RPC takes an absolute path and the server enforces an
 * allowlist of mount roots configured at startup.
 *
 * @generated from service bridge.v1.BridgeFileSystemService
 */
export const BridgeFileSystemService = /*@__PURE__*/
  serviceDesc(file_bridge_v1_filesystem, 0);

