// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file bridge/v1/interceptor.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bridge/v1/interceptor.proto.
 */
export declare const file_bridge_v1_interceptor: GenFile;

/**
 * @generated from message bridge.v1.GetStatusRequest
 */
export declare type GetStatusRequest = Message<"bridge.v1.GetStatusRequest"> & {
};

/**
 * Describes the message bridge.v1.GetStatusRequest.
 * Use `create(GetStatusRequestSchema)` to create a new message.
 */
export declare const GetStatusRequestSchema: GenMessage<GetStatusRequest>;

/**
 * @generated from message bridge.v1.GetStatusResponse
 */
export declare type GetStatusResponse = Message<"bridge.v1.GetStatusResponse"> & {
  /**
   * True once the intercept has finished setup (DNS, iptables, tunnel) and
   * is forwarding traffic. Independent of the app's own health.
   *
   * @generated from field: bool ready = 1;
   */
  ready: boolean;

  /**
   * Liveness probe result against the local app. Unset if no liveness
   * probe was configured on the source.
   *
   * @generated from field: bridge.v1.ProbeStatus liveness = 2;
   */
  liveness?: ProbeStatus | undefined;

  /**
   * Readiness probe result against the local app. Unset if no readiness
   * probe was configured on the source.
   *
   * @generated from field: bridge.v1.ProbeStatus readiness = 3;
   */
  readiness?: ProbeStatus | undefined;

  /**
   * Startup probe result against the local app. Unset if no startup
   * probe was configured on the source.
   *
   * @generated from field: bridge.v1.ProbeStatus startup = 4;
   */
  startup?: ProbeStatus | undefined;
};

/**
 * Describes the message bridge.v1.GetStatusResponse.
 * Use `create(GetStatusResponseSchema)` to create a new message.
 */
export declare const GetStatusResponseSchema: GenMessage<GetStatusResponse>;

/**
 * ProbeStatus reflects the current health view from a single configured
 * probe — what the source deployment's probe would have reported if it had
 * been run against the developer's local app.
 *
 * @generated from message bridge.v1.ProbeStatus
 */
export declare type ProbeStatus = Message<"bridge.v1.ProbeStatus"> & {
  /**
   * ProbeHealth summarises the latest result.
   *
   * @generated from field: bridge.v1.ProbeHealth health = 1;
   */
  health: ProbeHealth;

  /**
   * Human-readable last result (e.g. "HTTP 200", "connection refused",
   * "exit status 1"). Empty before the first check completes.
   *
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * Unix seconds of the most recent check. Zero before the first check.
   *
   * @generated from field: int64 last_check_unix_seconds = 3 [json_name = "last_check_unix_seconds"];
   */
  lastCheckUnixSeconds: bigint;

  /**
   * Consecutive successful checks since the last failure (or startup).
   *
   * @generated from field: int32 consecutive_successes = 4 [json_name = "consecutive_successes"];
   */
  consecutiveSuccesses: number;

  /**
   * Consecutive failed checks since the last success (or startup).
   *
   * @generated from field: int32 consecutive_failures = 5 [json_name = "consecutive_failures"];
   */
  consecutiveFailures: number;

  /**
   * Total checks executed since intercept startup.
   *
   * @generated from field: int64 total_checks = 6 [json_name = "total_checks"];
   */
  totalChecks: bigint;
};

/**
 * Describes the message bridge.v1.ProbeStatus.
 * Use `create(ProbeStatusSchema)` to create a new message.
 */
export declare const ProbeStatusSchema: GenMessage<ProbeStatus>;

/**
 * @generated from message bridge.v1.ProbeRequest
 */
export declare type ProbeRequest = Message<"bridge.v1.ProbeRequest"> & {
};

/**
 * Describes the message bridge.v1.ProbeRequest.
 * Use `create(ProbeRequestSchema)` to create a new message.
 */
export declare const ProbeRequestSchema: GenMessage<ProbeRequest>;

/**
 * ProbeResponse reports the outcome of a synchronous run of each
 * configured probe. Each field is unset when the corresponding probe is
 * not configured on the source deployment.
 *
 * @generated from message bridge.v1.ProbeResponse
 */
export declare type ProbeResponse = Message<"bridge.v1.ProbeResponse"> & {
  /**
   * @generated from field: bridge.v1.ProbeCheckResult liveness = 1;
   */
  liveness?: ProbeCheckResult | undefined;

  /**
   * @generated from field: bridge.v1.ProbeCheckResult readiness = 2;
   */
  readiness?: ProbeCheckResult | undefined;

  /**
   * @generated from field: bridge.v1.ProbeCheckResult startup = 3;
   */
  startup?: ProbeCheckResult | undefined;
};

/**
 * Describes the message bridge.v1.ProbeResponse.
 * Use `create(ProbeResponseSchema)` to create a new message.
 */
export declare const ProbeResponseSchema: GenMessage<ProbeResponse>;

/**
 * ProbeCheckResult is the outcome of one synchronous probe check.
 *
 * @generated from message bridge.v1.ProbeCheckResult
 */
export declare type ProbeCheckResult = Message<"bridge.v1.ProbeCheckResult"> & {
  /**
   * True if this single check passed (HTTP 2xx/3xx, TCP open, gRPC
   * SERVING, or Exec exit 0).
   *
   * @generated from field: bool passed = 1;
   */
  passed: boolean;

  /**
   * Error message when passed=false. Empty on success.
   *
   * @generated from field: string error = 2;
   */
  error: string;

  /**
   * Unix seconds when this check completed.
   *
   * @generated from field: int64 checked_at_unix_seconds = 3 [json_name = "checked_at_unix_seconds"];
   */
  checkedAtUnixSeconds: bigint;
};

/**
 * Describes the message bridge.v1.ProbeCheckResult.
 * Use `create(ProbeCheckResultSchema)` to create a new message.
 */
export declare const ProbeCheckResultSchema: GenMessage<ProbeCheckResult>;

/**
 * @generated from enum bridge.v1.ProbeHealth
 */
export enum ProbeHealth {
  /**
   * @generated from enum value: PROBE_HEALTH_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Probe has not yet run a check.
   *
   * @generated from enum value: PROBE_HEALTH_PENDING = 1;
   */
  PENDING = 1,

  /**
   * Last check passed and the configured success_threshold has been met.
   *
   * @generated from enum value: PROBE_HEALTH_HEALTHY = 2;
   */
  HEALTHY = 2,

  /**
   * Probe has been failing — failure_threshold consecutive failures.
   *
   * @generated from enum value: PROBE_HEALTH_UNHEALTHY = 3;
   */
  UNHEALTHY = 3,
}

/**
 * Describes the enum bridge.v1.ProbeHealth.
 */
export declare const ProbeHealthSchema: GenEnum<ProbeHealth>;

/**
 * InterceptorService runs inside the devcontainer and reports the current
 * state of the local intercept process — initialization, tunnel health, and
 * live results of the source deployment's probes against the developer's
 * local app.
 *
 * @generated from service bridge.v1.InterceptorService
 */
export declare const InterceptorService: GenService<{
  /**
   * GetStatus returns the current state of the intercept process. Safe to
   * call repeatedly; the response is built from cached probe results and
   * does not trigger fresh probe runs.
   *
   * @generated from rpc bridge.v1.InterceptorService.GetStatus
   */
  getStatus: {
    methodKind: "unary";
    input: typeof GetStatusRequestSchema;
    output: typeof GetStatusResponseSchema;
  },
  /**
   * Probe synchronously runs every configured probe (liveness, readiness,
   * startup) against the local app once and returns the result of those
   * single checks. Unlike GetStatus, the response is NOT subject to the
   * success/failure thresholds — each field tells you whether that single
   * immediate check passed. Useful as a "is the app healthy right now?"
   * primitive that ignores any stale state from a previous dev session.
   *
   * @generated from rpc bridge.v1.InterceptorService.Probe
   */
  probe: {
    methodKind: "unary";
    input: typeof ProbeRequestSchema;
    output: typeof ProbeResponseSchema;
  },
}>;

