// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file bridge/v1/interceptor.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bridge/v1/interceptor.proto.
 */
export const file_bridge_v1_interceptor = /*@__PURE__*/
  fileDesc("ChticmlkZ2UvdjEvaW50ZXJjZXB0b3IucHJvdG8SCWJyaWRnZS52MSISChBHZXRTdGF0dXNSZXF1ZXN0IqABChFHZXRTdGF0dXNSZXNwb25zZRINCgVyZWFkeRgBIAEoCBIoCghsaXZlbmVzcxgCIAEoCzIWLmJyaWRnZS52MS5Qcm9iZVN0YXR1cxIpCglyZWFkaW5lc3MYAyABKAsyFi5icmlkZ2UudjEuUHJvYmVTdGF0dXMSJwoHc3RhcnR1cBgEIAEoCzIWLmJyaWRnZS52MS5Qcm9iZVN0YXR1cyKOAgoLUHJvYmVTdGF0dXMSJgoGaGVhbHRoGAEgASgOMhYuYnJpZGdlLnYxLlByb2JlSGVhbHRoEg8KB21lc3NhZ2UYAiABKAkSOAoXbGFzdF9jaGVja191bml4X3NlY29uZHMYAyABKANSF2xhc3RfY2hlY2tfdW5peF9zZWNvbmRzEjQKFWNvbnNlY3V0aXZlX3N1Y2Nlc3NlcxgEIAEoBVIVY29uc2VjdXRpdmVfc3VjY2Vzc2VzEjIKFGNvbnNlY3V0aXZlX2ZhaWx1cmVzGAUgASgFUhRjb25zZWN1dGl2ZV9mYWlsdXJlcxIiCgx0b3RhbF9jaGVja3MYBiABKANSDHRvdGFsX2NoZWNrcyp7CgtQcm9iZUhlYWx0aBIcChhQUk9CRV9IRUFMVEhfVU5TUEVDSUZJRUQQABIYChRQUk9CRV9IRUFMVEhfUEVORElORxABEhgKFFBST0JFX0hFQUxUSF9IRUFMVEhZEAISGgoWUFJPQkVfSEVBTFRIX1VOSEVBTFRIWRADMlwKEkludGVyY2VwdG9yU2VydmljZRJGCglHZXRTdGF0dXMSGy5icmlkZ2UudjEuR2V0U3RhdHVzUmVxdWVzdBocLmJyaWRnZS52MS5HZXRTdGF0dXNSZXNwb25zZUKaAQoNY29tLmJyaWRnZS52MUIQSW50ZXJjZXB0b3JQcm90b1ABWjJnaXRodWIuY29tL3ZlcmNlbC9icmlkZ2UvYXBpL2dvL2JyaWRnZS92MTticmlkZ2V2MaICA0JYWKoCCUJyaWRnZS5WMcoCCUJyaWRnZVxWMeICFUJyaWRnZVxWMVxHUEJNZXRhZGF0YeoCCkJyaWRnZTo6VjFiBnByb3RvMw");

/**
 * Describes the message bridge.v1.GetStatusRequest.
 * Use `create(GetStatusRequestSchema)` to create a new message.
 */
export const GetStatusRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_interceptor, 0);

/**
 * Describes the message bridge.v1.GetStatusResponse.
 * Use `create(GetStatusResponseSchema)` to create a new message.
 */
export const GetStatusResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_interceptor, 1);

/**
 * Describes the message bridge.v1.ProbeStatus.
 * Use `create(ProbeStatusSchema)` to create a new message.
 */
export const ProbeStatusSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_interceptor, 2);

/**
 * Describes the enum bridge.v1.ProbeHealth.
 */
export const ProbeHealthSchema = /*@__PURE__*/
  enumDesc(file_bridge_v1_interceptor, 0);

/**
 * @generated from enum bridge.v1.ProbeHealth
 */
export const ProbeHealth = /*@__PURE__*/
  tsEnum(ProbeHealthSchema);

/**
 * InterceptorService runs inside the devcontainer and reports the current
 * state of the local intercept process — initialization, tunnel health, and
 * live results of the source deployment's probes against the developer's
 * local app.
 *
 * @generated from service bridge.v1.InterceptorService
 */
export const InterceptorService = /*@__PURE__*/
  serviceDesc(file_bridge_v1_interceptor, 0);

