// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/profile.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bridge/v1/profile.proto.
 */
export declare const file_bridge_v1_profile: GenFile;

/**
 * Profile is loaded from .bridge/bridge.json in the repository root.
 * It defines per-command rules that automatically set flags based on
 * CEL expressions evaluated against the command's arguments.
 *
 * @generated from message bridge.v1.Profile
 */
export declare type Profile = Message<"bridge.v1.Profile"> & {
  /**
   * Rules for the "create" command.
   *
   * @generated from field: repeated bridge.v1.CreateCommandProfile create = 1;
   */
  create: CreateCommandProfile[];
};

/**
 * Describes the message bridge.v1.Profile.
 * Use `create(ProfileSchema)` to create a new message.
 */
export declare const ProfileSchema: GenMessage<Profile>;

/**
 * CreateCommandProfile pairs a matcher with flag defaults for the
 * "create" command.
 *
 * @generated from message bridge.v1.CreateCommandProfile
 */
export declare type CreateCommandProfile = Message<"bridge.v1.CreateCommandProfile"> & {
  /**
   * CEL expression that must return true for the flags to apply.
   * The expression is evaluated with a `payload` variable of type
   * CreateCommandPayload. Access fields via `payload.<field>`:
   *
   *   payload.workload_name        (string) — the workload_name positional argument
   *   payload.namespace            (string) — the --namespace flag value
   *   payload.server_facades       (list<string>) — the --server-facade flag values
   *   payload.source               (string) — the --source flag value
   *   payload.listen               (int) — the --listen flag value
   *   payload.connect              (bool) — the --connect flag value
   *   payload.devcontainer_config  (string) — the --devcontainer-config flag value
   *   payload.devcontainer_up_args (string) — the --devcontainer-up-args flag value
   *
   * Examples:
   *   "payload.workload_name == 'api-feature-flags'"
   *   "payload.workload_name.startsWith('api-') && payload.namespace == 'production'"
   *   "payload.workload_name.contains('flags')"
   *
   * @generated from field: string match = 1;
   */
  match: string;

  /**
   * Flags to set or append when the matcher returns true.
   *
   * @generated from field: bridge.v1.CreateCommandPayload command = 2;
   */
  command?: CreateCommandPayload;
};

/**
 * Describes the message bridge.v1.CreateCommandProfile.
 * Use `create(CreateCommandProfileSchema)` to create a new message.
 */
export declare const CreateCommandProfileSchema: GenMessage<CreateCommandProfile>;

/**
 * CreateCommandPayload represents the flags for the "create" command.
 * Used both as the CEL evaluation context and as the flag values to apply.
 *
 * @generated from message bridge.v1.CreateCommandPayload
 */
export declare type CreateCommandPayload = Message<"bridge.v1.CreateCommandPayload"> & {
  /**
   * Positional argument: name of the target workload (defaults to a Deployment).
   *
   * @generated from field: string workload_name = 1 [json_name = "workload_name"];
   */
  workloadName: string;

  /**
   * --namespace / -n: target namespace of the source deployment.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * --server-facade: server facade specs (JSON string or file path). Repeated.
   *
   * @generated from field: repeated string server_facades = 3 [json_name = "server_facades"];
   */
  serverFacades: string[];

  /**
   * --source / -s: path to Kubernetes manifests (folder, glob, or YAML file).
   *
   * @generated from field: string source = 4;
   */
  source: string;

  /**
   * --listen / -l: port the app listens on.
   *
   * @generated from field: int32 listen = 5;
   */
  listen: number;

  /**
   * --connect / -c: start the devcontainer and exec into it after creation.
   *
   * @generated from field: bool connect = 6;
   */
  connect: boolean;

  /**
   * --devcontainer-config / -f: path to a base devcontainer.json to extend.
   *
   * @generated from field: string devcontainer_config = 7 [json_name = "devcontainer_config"];
   */
  devcontainerConfig: string;

  /**
   * --devcontainer-up-args: additional arguments passed to devcontainer up.
   *
   * @generated from field: string devcontainer_up_args = 8 [json_name = "devcontainer_up_args"];
   */
  devcontainerUpArgs: string;

  /**
   * --name: bridge name (defaults to workload_name).
   *
   * @generated from field: string name = 9;
   */
  name: string;
};

/**
 * Describes the message bridge.v1.CreateCommandPayload.
 * Use `create(CreateCommandPayloadSchema)` to create a new message.
 */
export declare const CreateCommandPayloadSchema: GenMessage<CreateCommandPayload>;

