// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/profile.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";

/**
 * Describes the file bridge/v1/profile.proto.
 */
export const file_bridge_v1_profile = /*@__PURE__*/
  fileDesc("ChdicmlkZ2UvdjEvcHJvZmlsZS5wcm90bxIJYnJpZGdlLnYxIjoKB1Byb2ZpbGUSLwoGY3JlYXRlGAEgAygLMh8uYnJpZGdlLnYxLkNyZWF0ZUNvbW1hbmRQcm9maWxlImsKFENyZWF0ZUNvbW1hbmRQcm9maWxlEhkKBW1hdGNoGAEgASgJQgq6SAfIAQFyAhABEjgKB2NvbW1hbmQYAiABKAsyHy5icmlkZ2UudjEuQ3JlYXRlQ29tbWFuZFBheWxvYWRCBrpIA8gBASKcAgoUQ3JlYXRlQ29tbWFuZFBheWxvYWQSJAoNd29ya2xvYWRfbmFtZRgBIAEoCVINd29ya2xvYWRfbmFtZRIRCgluYW1lc3BhY2UYAiABKAkSJgoOc2VydmVyX2ZhY2FkZXMYAyADKAlSDnNlcnZlcl9mYWNhZGVzEg4KBnNvdXJjZRgEIAEoCRIOCgZsaXN0ZW4YBSABKAUSDwoHY29ubmVjdBgGIAEoCBIwChNkZXZjb250YWluZXJfY29uZmlnGAcgASgJUhNkZXZjb250YWluZXJfY29uZmlnEjIKFGRldmNvbnRhaW5lcl91cF9hcmdzGAggASgJUhRkZXZjb250YWluZXJfdXBfYXJncxIMCgRuYW1lGAkgASgJQpYBCg1jb20uYnJpZGdlLnYxQgxQcm9maWxlUHJvdG9QAVoyZ2l0aHViLmNvbS92ZXJjZWwvYnJpZGdlL2FwaS9nby9icmlkZ2UvdjE7YnJpZGdldjGiAgNCWFiqAglCcmlkZ2UuVjHKAglCcmlkZ2VcVjHiAhVCcmlkZ2VcVjFcR1BCTWV0YWRhdGHqAgpCcmlkZ2U6OlYxYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * Describes the message bridge.v1.Profile.
 * Use `create(ProfileSchema)` to create a new message.
 */
export const ProfileSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_profile, 0);

/**
 * Describes the message bridge.v1.CreateCommandProfile.
 * Use `create(CreateCommandProfileSchema)` to create a new message.
 */
export const CreateCommandProfileSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_profile, 1);

/**
 * Describes the message bridge.v1.CreateCommandPayload.
 * Use `create(CreateCommandPayloadSchema)` to create a new message.
 */
export const CreateCommandPayloadSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_profile, 2);

