// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/profile.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { CreateCommandPayload } from "./command_pb";

/**
 * Describes the file bridge/v1/profile.proto.
 */
export declare const file_bridge_v1_profile: GenFile;

/**
 * Profile is loaded from .bridge/bridge.json in the repository root.
 * It defines per-command rules that automatically set flags based on
 * CEL expressions evaluated against the command's arguments.
 *
 * @generated from message bridge.v1.Profile
 */
export declare type Profile = Message<"bridge.v1.Profile"> & {
  /**
   * Rules for the "create" command.
   *
   * @generated from field: repeated bridge.v1.CreateCommandProfile create = 1;
   */
  create: CreateCommandProfile[];
};

/**
 * Describes the message bridge.v1.Profile.
 * Use `create(ProfileSchema)` to create a new message.
 */
export declare const ProfileSchema: GenMessage<Profile>;

/**
 * CreateCommandProfile pairs a matcher with flag defaults for the
 * "create" command.
 *
 * @generated from message bridge.v1.CreateCommandProfile
 */
export declare type CreateCommandProfile = Message<"bridge.v1.CreateCommandProfile"> & {
  /**
   * CEL expression that must return true for the flags to apply.
   * The expression is evaluated with a `payload` variable of type
   * CreateCommandPayload. Access fields via `payload.<field>`:
   *
   *   payload.workload_name        (string) — the workload_name positional argument
   *   payload.namespace            (string) — the --namespace flag value
   *   payload.server_facades       (list<string>) — the --server-facade flag values
   *   payload.source               (string) — the --source flag value
   *   payload.listen               (int) — the --listen flag value
   *   payload.connect              (bool) — the --connect flag value
   *   payload.devcontainer_config  (string) — the --devcontainer-config flag value
   *   payload.devcontainer_up_args (string) — the --devcontainer-up-args flag value
   *
   * Examples:
   *   "payload.workload_name == 'api-feature-flags'"
   *   "payload.workload_name.startsWith('api-') && payload.namespace == 'production'"
   *   "payload.workload_name.contains('flags')"
   *
   * @generated from field: string match = 1;
   */
  match: string;

  /**
   * Flags to set or append when the matcher returns true.
   *
   * @generated from field: bridge.v1.CreateCommandPayload command = 2;
   */
  command?: CreateCommandPayload;
};

/**
 * Describes the message bridge.v1.CreateCommandProfile.
 * Use `create(CreateCommandProfileSchema)` to create a new message.
 */
export declare const CreateCommandProfileSchema: GenMessage<CreateCommandProfile>;

