// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/profile.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_bridge_v1_command } from "./command_pb";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";

/**
 * Describes the file bridge/v1/profile.proto.
 */
export const file_bridge_v1_profile = /*@__PURE__*/
  fileDesc("ChdicmlkZ2UvdjEvcHJvZmlsZS5wcm90bxIJYnJpZGdlLnYxIjoKB1Byb2ZpbGUSLwoGY3JlYXRlGAEgAygLMh8uYnJpZGdlLnYxLkNyZWF0ZUNvbW1hbmRQcm9maWxlImsKFENyZWF0ZUNvbW1hbmRQcm9maWxlEhkKBW1hdGNoGAEgASgJQgq6SAfIAQFyAhABEjgKB2NvbW1hbmQYAiABKAsyHy5icmlkZ2UudjEuQ3JlYXRlQ29tbWFuZFBheWxvYWRCBrpIA8gBAUKWAQoNY29tLmJyaWRnZS52MUIMUHJvZmlsZVByb3RvUAFaMmdpdGh1Yi5jb20vdmVyY2VsL2JyaWRnZS9hcGkvZ28vYnJpZGdlL3YxO2JyaWRnZXYxogIDQlhYqgIJQnJpZGdlLlYxygIJQnJpZGdlXFYx4gIVQnJpZGdlXFYxXEdQQk1ldGFkYXRh6gIKQnJpZGdlOjpWMWIGcHJvdG8z", [file_bridge_v1_command, file_buf_validate_validate]);

/**
 * Describes the message bridge.v1.Profile.
 * Use `create(ProfileSchema)` to create a new message.
 */
export const ProfileSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_profile, 0);

/**
 * Describes the message bridge.v1.CreateCommandProfile.
 * Use `create(CreateCommandProfileSchema)` to create a new message.
 */
export const CreateCommandProfileSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_profile, 1);

