// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file bridge/v1/proxy.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bridge/v1/proxy.proto.
 */
export declare const file_bridge_v1_proxy: GenFile;

/**
 * @generated from message bridge.v1.ProxyResolveDNSRequest
 */
export declare type ProxyResolveDNSRequest = Message<"bridge.v1.ProxyResolveDNSRequest"> & {
  /**
   * @generated from field: string hostname = 1;
   */
  hostname: string;
};

/**
 * Describes the message bridge.v1.ProxyResolveDNSRequest.
 * Use `create(ProxyResolveDNSRequestSchema)` to create a new message.
 */
export declare const ProxyResolveDNSRequestSchema: GenMessage<ProxyResolveDNSRequest>;

/**
 * @generated from message bridge.v1.ProxyResolveDNSResponse
 */
export declare type ProxyResolveDNSResponse = Message<"bridge.v1.ProxyResolveDNSResponse"> & {
  /**
   * @generated from field: repeated string addresses = 1;
   */
  addresses: string[];

  /**
   * @generated from field: string error = 2;
   */
  error: string;
};

/**
 * Describes the message bridge.v1.ProxyResolveDNSResponse.
 * Use `create(ProxyResolveDNSResponseSchema)` to create a new message.
 */
export declare const ProxyResolveDNSResponseSchema: GenMessage<ProxyResolveDNSResponse>;

/**
 * @generated from message bridge.v1.TunnelAddress
 */
export declare type TunnelAddress = Message<"bridge.v1.TunnelAddress"> & {
  /**
   * @generated from field: string ip = 1;
   */
  ip: string;

  /**
   * @generated from field: int32 port = 2;
   */
  port: number;
};

/**
 * Describes the message bridge.v1.TunnelAddress.
 * Use `create(TunnelAddressSchema)` to create a new message.
 */
export declare const TunnelAddressSchema: GenMessage<TunnelAddress>;

/**
 * @generated from message bridge.v1.GetMetadataRequest
 */
export declare type GetMetadataRequest = Message<"bridge.v1.GetMetadataRequest"> & {
};

/**
 * Describes the message bridge.v1.GetMetadataRequest.
 * Use `create(GetMetadataRequestSchema)` to create a new message.
 */
export declare const GetMetadataRequestSchema: GenMessage<GetMetadataRequest>;

/**
 * @generated from message bridge.v1.GetMetadataResponse
 */
export declare type GetMetadataResponse = Message<"bridge.v1.GetMetadataResponse"> & {
  /**
   * @generated from field: map<string, string> env_vars = 1;
   */
  envVars: { [key: string]: string };

  /**
   * PEM-encoded CA certificate for TLS interception of mocked services.
   * Mounted into the bridge proxy pod from a Kubernetes Secret.
   *
   * @generated from field: bytes ca_cert = 2 [json_name = "ca_cert"];
   */
  caCert: Uint8Array;

  /**
   * PEM-encoded CA private key for minting per-host TLS certificates.
   * Mounted into the bridge proxy pod from a Kubernetes Secret.
   *
   * @generated from field: bytes ca_key = 3 [json_name = "ca_key"];
   */
  caKey: Uint8Array;

  /**
   * Absolute paths the BridgeFileSystemService is allowed to serve. The
   * devcontainer FUSE-mounts each one at the same path on the local side.
   *
   * @generated from field: repeated string mount_roots = 4 [json_name = "mount_roots"];
   */
  mountRoots: string[];

  /**
   * The source container's primary application port (the first non-grpc port
   * declared on the original deployment). The interceptor uses this to
   * remap probe targets: if a probe's port matches source_app_port, the
   * interceptor checks --app-port locally instead. Zero if the source had
   * no app ports.
   *
   * @generated from field: int32 source_app_port = 5 [json_name = "source_app_port"];
   */
  sourceAppPort: number;

  /**
   * Liveness probe from the source deployment's application container, or
   * unset if the source had none.
   *
   * @generated from field: bridge.v1.Probe liveness_probe = 6 [json_name = "liveness_probe"];
   */
  livenessProbe?: Probe | undefined;

  /**
   * Readiness probe from the source deployment's application container, or
   * unset if the source had none.
   *
   * @generated from field: bridge.v1.Probe readiness_probe = 7 [json_name = "readiness_probe"];
   */
  readinessProbe?: Probe | undefined;

  /**
   * Startup probe from the source deployment's application container, or
   * unset if the source had none.
   *
   * @generated from field: bridge.v1.Probe startup_probe = 8 [json_name = "startup_probe"];
   */
  startupProbe?: Probe | undefined;
};

/**
 * Describes the message bridge.v1.GetMetadataResponse.
 * Use `create(GetMetadataResponseSchema)` to create a new message.
 */
export declare const GetMetadataResponseSchema: GenMessage<GetMetadataResponse>;

/**
 * Probe mirrors a Kubernetes-style probe definition for a single check (HTTP
 * GET, TCP open, gRPC health, or shell exec). Exactly one handler is set.
 *
 * @generated from message bridge.v1.Probe
 */
export declare type Probe = Message<"bridge.v1.Probe"> & {
  /**
   * @generated from oneof bridge.v1.Probe.handler
   */
  handler: {
    /**
     * @generated from field: bridge.v1.HTTPGetAction http_get = 1 [json_name = "http_get"];
     */
    value: HTTPGetAction;
    case: "httpGet";
  } | {
    /**
     * @generated from field: bridge.v1.TCPSocketAction tcp_socket = 2 [json_name = "tcp_socket"];
     */
    value: TCPSocketAction;
    case: "tcpSocket";
  } | {
    /**
     * @generated from field: bridge.v1.GRPCAction grpc = 3;
     */
    value: GRPCAction;
    case: "grpc";
  } | {
    /**
     * @generated from field: bridge.v1.ExecAction exec = 4;
     */
    value: ExecAction;
    case: "exec";
  } | { case: undefined; value?: undefined };

  /**
   * Seconds to wait before the first check. Default 0.
   *
   * @generated from field: int32 initial_delay_seconds = 10 [json_name = "initial_delay_seconds"];
   */
  initialDelaySeconds: number;

  /**
   * How often (in seconds) to perform the probe. Default 10.
   *
   * @generated from field: int32 period_seconds = 11 [json_name = "period_seconds"];
   */
  periodSeconds: number;

  /**
   * Seconds after which a single check is considered failed. Default 1.
   *
   * @generated from field: int32 timeout_seconds = 12 [json_name = "timeout_seconds"];
   */
  timeoutSeconds: number;

  /**
   * Minimum consecutive successes for the probe to be considered healthy
   * after having been failing. Default 1.
   *
   * @generated from field: int32 success_threshold = 13 [json_name = "success_threshold"];
   */
  successThreshold: number;

  /**
   * After this many consecutive failures the probe is considered failing.
   * Default 3.
   *
   * @generated from field: int32 failure_threshold = 14 [json_name = "failure_threshold"];
   */
  failureThreshold: number;
};

/**
 * Describes the message bridge.v1.Probe.
 * Use `create(ProbeSchema)` to create a new message.
 */
export declare const ProbeSchema: GenMessage<Probe>;

/**
 * HTTPGetAction performs an HTTP GET against the local app.
 *
 * @generated from message bridge.v1.HTTPGetAction
 */
export declare type HTTPGetAction = Message<"bridge.v1.HTTPGetAction"> & {
  /**
   * Request path. Defaults to "/".
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * Target port. The interceptor remaps this to --app-port if it matches
   * source_app_port.
   *
   * @generated from field: int32 port = 2;
   */
  port: number;

  /**
   * "HTTP" or "HTTPS". Defaults to HTTP.
   *
   * @generated from field: string scheme = 3;
   */
  scheme: string;

  /**
   * Extra request headers.
   *
   * @generated from field: repeated bridge.v1.HTTPHeader http_headers = 4 [json_name = "http_headers"];
   */
  httpHeaders: HTTPHeader[];
};

/**
 * Describes the message bridge.v1.HTTPGetAction.
 * Use `create(HTTPGetActionSchema)` to create a new message.
 */
export declare const HTTPGetActionSchema: GenMessage<HTTPGetAction>;

/**
 * @generated from message bridge.v1.HTTPHeader
 */
export declare type HTTPHeader = Message<"bridge.v1.HTTPHeader"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message bridge.v1.HTTPHeader.
 * Use `create(HTTPHeaderSchema)` to create a new message.
 */
export declare const HTTPHeaderSchema: GenMessage<HTTPHeader>;

/**
 * TCPSocketAction opens a TCP connection.
 *
 * @generated from message bridge.v1.TCPSocketAction
 */
export declare type TCPSocketAction = Message<"bridge.v1.TCPSocketAction"> & {
  /**
   * Target port. The interceptor remaps this to --app-port if it matches
   * source_app_port.
   *
   * @generated from field: int32 port = 1;
   */
  port: number;
};

/**
 * Describes the message bridge.v1.TCPSocketAction.
 * Use `create(TCPSocketActionSchema)` to create a new message.
 */
export declare const TCPSocketActionSchema: GenMessage<TCPSocketAction>;

/**
 * GRPCAction calls the gRPC health service on the target.
 *
 * @generated from message bridge.v1.GRPCAction
 */
export declare type GRPCAction = Message<"bridge.v1.GRPCAction"> & {
  /**
   * Target port. The interceptor remaps this to --app-port if it matches
   * source_app_port.
   *
   * @generated from field: int32 port = 1;
   */
  port: number;

  /**
   * Optional service name to check (passed as `service` in the health
   * request). Empty checks the overall server health.
   *
   * @generated from field: string service = 2;
   */
  service: string;
};

/**
 * Describes the message bridge.v1.GRPCAction.
 * Use `create(GRPCActionSchema)` to create a new message.
 */
export declare const GRPCActionSchema: GenMessage<GRPCAction>;

/**
 * ExecAction runs a command inside the devcontainer; exit code 0 is healthy.
 *
 * @generated from message bridge.v1.ExecAction
 */
export declare type ExecAction = Message<"bridge.v1.ExecAction"> & {
  /**
   * Argv. The first element is the program; the rest are arguments.
   *
   * @generated from field: repeated string command = 1;
   */
  command: string[];
};

/**
 * Describes the message bridge.v1.ExecAction.
 * Use `create(ExecActionSchema)` to create a new message.
 */
export declare const ExecActionSchema: GenMessage<ExecAction>;

/**
 * @generated from message bridge.v1.TunnelNetworkMessage
 */
export declare type TunnelNetworkMessage = Message<"bridge.v1.TunnelNetworkMessage"> & {
  /**
   * The address that is sending the message.
   *
   * @generated from field: bridge.v1.TunnelAddress source = 1;
   */
  source?: TunnelAddress | undefined;

  /**
   * The intended target address on the destination.
   *
   * @generated from field: bridge.v1.TunnelAddress dest = 2;
   */
  dest?: TunnelAddress | undefined;

  /**
   * Connection ID for multiplexing multiple connections over one stream.
   *
   * @generated from field: string connection_id = 3 [json_name = "connection_id"];
   */
  connectionId: string;

  /**
   * The payload data being tunneled.
   *
   * @generated from field: bytes data = 4;
   */
  data: Uint8Array;

  /**
   * The protocol used for the connection (TCP or UDP).
   *
   * @generated from field: bridge.v1.TunnelProtocol protocol = 5;
   */
  protocol: TunnelProtocol;

  /**
   * Error message if something went wrong.
   *
   * @generated from field: string error = 6;
   */
  error: string;

  /**
   * The hostname associated with this connection, resolved by the intercept
   * DNS interceptor. Used by the server for mock matching and TLS cert minting.
   *
   * @generated from field: string hostname = 7;
   */
  hostname: string;
};

/**
 * Describes the message bridge.v1.TunnelNetworkMessage.
 * Use `create(TunnelNetworkMessageSchema)` to create a new message.
 */
export declare const TunnelNetworkMessageSchema: GenMessage<TunnelNetworkMessage>;

/**
 * @generated from enum bridge.v1.TunnelProtocol
 */
export enum TunnelProtocol {
  /**
   * @generated from enum value: TUNNEL_PROTOCOL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TUNNEL_PROTOCOL_TCP = 1;
   */
  TCP = 1,

  /**
   * @generated from enum value: TUNNEL_PROTOCOL_UDP = 2;
   */
  UDP = 2,
}

/**
 * Describes the enum bridge.v1.TunnelProtocol.
 */
export declare const TunnelProtocolSchema: GenEnum<TunnelProtocol>;

/**
 * BridgeProxyService runs in-cluster and provides DNS resolution and network
 * tunneling to the local bridge intercept client over gRPC.
 *
 * @generated from service bridge.v1.BridgeProxyService
 */
export declare const BridgeProxyService: GenService<{
  /**
   * ResolveDNSQuery resolves a hostname using the in-cluster DNS (CoreDNS).
   * buf:lint:ignore RPC_REQUEST_STANDARD_NAME
   * buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
   *
   * @generated from rpc bridge.v1.BridgeProxyService.ResolveDNSQuery
   */
  resolveDNSQuery: {
    methodKind: "unary";
    input: typeof ProxyResolveDNSRequestSchema;
    output: typeof ProxyResolveDNSResponseSchema;
  },
  /**
   * TunnelNetwork tunnels TCP/UDP traffic to an upstream service over a
   * bidirectional stream. Every message carries source/dest addresses and a
   * connection ID so both sides share the same addressing semantics as the
   * WebSocket Message in bridge.proto.
   * buf:lint:ignore RPC_REQUEST_STANDARD_NAME
   * buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
   * buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
   *
   * @generated from rpc bridge.v1.BridgeProxyService.TunnelNetwork
   */
  tunnelNetwork: {
    methodKind: "bidi_streaming";
    input: typeof TunnelNetworkMessageSchema;
    output: typeof TunnelNetworkMessageSchema;
  },
  /**
   * GetMetadata returns metadata about the bridge proxy, including environment
   * variables from the pod that can be forwarded to the devcontainer.
   *
   * @generated from rpc bridge.v1.BridgeProxyService.GetMetadata
   */
  getMetadata: {
    methodKind: "unary";
    input: typeof GetMetadataRequestSchema;
    output: typeof GetMetadataResponseSchema;
  },
}>;

