// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/proxy.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bridge/v1/proxy.proto.
 */
export const file_bridge_v1_proxy = /*@__PURE__*/
  fileDesc("ChVicmlkZ2UvdjEvcHJveHkucHJvdG8SCWJyaWRnZS52MSIqChZQcm94eVJlc29sdmVETlNSZXF1ZXN0EhAKCGhvc3RuYW1lGAEgASgJIjsKF1Byb3h5UmVzb2x2ZUROU1Jlc3BvbnNlEhEKCWFkZHJlc3NlcxgBIAMoCRINCgVlcnJvchgCIAEoCSIpCg1UdW5uZWxBZGRyZXNzEgoKAmlwGAEgASgJEgwKBHBvcnQYAiABKAUiFAoSR2V0TWV0YWRhdGFSZXF1ZXN0IrYBChNHZXRNZXRhZGF0YVJlc3BvbnNlEj0KCGVudl92YXJzGAEgAygLMisuYnJpZGdlLnYxLkdldE1ldGFkYXRhUmVzcG9uc2UuRW52VmFyc0VudHJ5EhgKB2NhX2NlcnQYAiABKAxSB2NhX2NlcnQSFgoGY2Ffa2V5GAMgASgMUgZjYV9rZXkaLgoMRW52VmFyc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiIQoQQ29weUZpbGVzUmVxdWVzdBINCgVwYXRocxgBIAMoCSI3ChFDb3B5RmlsZXNSZXNwb25zZRIiCgVmaWxlcxgBIAMoCzITLmJyaWRnZS52MS5GaWxlQ29weSJYCghGaWxlQ29weRIMCgRwYXRoGAEgASgJEg8KB2NvbnRlbnQYAiABKAwSDAoEbW9kZRgDIAEoDRIQCghtb2RfdGltZRgEIAEoAxINCgVlcnJvchgFIAEoCSLqAQoUVHVubmVsTmV0d29ya01lc3NhZ2USKAoGc291cmNlGAEgASgLMhguYnJpZGdlLnYxLlR1bm5lbEFkZHJlc3MSJgoEZGVzdBgCIAEoCzIYLmJyaWRnZS52MS5UdW5uZWxBZGRyZXNzEiQKDWNvbm5lY3Rpb25faWQYAyABKAlSDWNvbm5lY3Rpb25faWQSDAoEZGF0YRgEIAEoDBIrCghwcm90b2NvbBgFIAEoDjIZLmJyaWRnZS52MS5UdW5uZWxQcm90b2NvbBINCgVlcnJvchgGIAEoCRIQCghob3N0bmFtZRgHIAEoCSpjCg5UdW5uZWxQcm90b2NvbBIfChtUVU5ORUxfUFJPVE9DT0xfVU5TUEVDSUZJRUQQABIXChNUVU5ORUxfUFJPVE9DT0xfVENQEAESFwoTVFVOTkVMX1BST1RPQ09MX1VEUBACMtsCChJCcmlkZ2VQcm94eVNlcnZpY2USWAoPUmVzb2x2ZUROU1F1ZXJ5EiEuYnJpZGdlLnYxLlByb3h5UmVzb2x2ZUROU1JlcXVlc3QaIi5icmlkZ2UudjEuUHJveHlSZXNvbHZlRE5TUmVzcG9uc2USVQoNVHVubmVsTmV0d29yaxIfLmJyaWRnZS52MS5UdW5uZWxOZXR3b3JrTWVzc2FnZRofLmJyaWRnZS52MS5UdW5uZWxOZXR3b3JrTWVzc2FnZSgBMAESTAoLR2V0TWV0YWRhdGESHS5icmlkZ2UudjEuR2V0TWV0YWRhdGFSZXF1ZXN0Gh4uYnJpZGdlLnYxLkdldE1ldGFkYXRhUmVzcG9uc2USRgoJQ29weUZpbGVzEhsuYnJpZGdlLnYxLkNvcHlGaWxlc1JlcXVlc3QaHC5icmlkZ2UudjEuQ29weUZpbGVzUmVzcG9uc2VClAEKDWNvbS5icmlkZ2UudjFCClByb3h5UHJvdG9QAVoyZ2l0aHViLmNvbS92ZXJjZWwvYnJpZGdlL2FwaS9nby9icmlkZ2UvdjE7YnJpZGdldjGiAgNCWFiqAglCcmlkZ2UuVjHKAglCcmlkZ2VcVjHiAhVCcmlkZ2VcVjFcR1BCTWV0YWRhdGHqAgpCcmlkZ2U6OlYxYgZwcm90bzM");

/**
 * Describes the message bridge.v1.ProxyResolveDNSRequest.
 * Use `create(ProxyResolveDNSRequestSchema)` to create a new message.
 */
export const ProxyResolveDNSRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 0);

/**
 * Describes the message bridge.v1.ProxyResolveDNSResponse.
 * Use `create(ProxyResolveDNSResponseSchema)` to create a new message.
 */
export const ProxyResolveDNSResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 1);

/**
 * Describes the message bridge.v1.TunnelAddress.
 * Use `create(TunnelAddressSchema)` to create a new message.
 */
export const TunnelAddressSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 2);

/**
 * Describes the message bridge.v1.GetMetadataRequest.
 * Use `create(GetMetadataRequestSchema)` to create a new message.
 */
export const GetMetadataRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 3);

/**
 * Describes the message bridge.v1.GetMetadataResponse.
 * Use `create(GetMetadataResponseSchema)` to create a new message.
 */
export const GetMetadataResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 4);

/**
 * Describes the message bridge.v1.CopyFilesRequest.
 * Use `create(CopyFilesRequestSchema)` to create a new message.
 */
export const CopyFilesRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 5);

/**
 * Describes the message bridge.v1.CopyFilesResponse.
 * Use `create(CopyFilesResponseSchema)` to create a new message.
 */
export const CopyFilesResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 6);

/**
 * Describes the message bridge.v1.FileCopy.
 * Use `create(FileCopySchema)` to create a new message.
 */
export const FileCopySchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 7);

/**
 * Describes the message bridge.v1.TunnelNetworkMessage.
 * Use `create(TunnelNetworkMessageSchema)` to create a new message.
 */
export const TunnelNetworkMessageSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 8);

/**
 * Describes the enum bridge.v1.TunnelProtocol.
 */
export const TunnelProtocolSchema = /*@__PURE__*/
  enumDesc(file_bridge_v1_proxy, 0);

/**
 * @generated from enum bridge.v1.TunnelProtocol
 */
export const TunnelProtocol = /*@__PURE__*/
  tsEnum(TunnelProtocolSchema);

/**
 * BridgeProxyService runs in-cluster and provides DNS resolution and network
 * tunneling to the local bridge intercept client over gRPC.
 *
 * @generated from service bridge.v1.BridgeProxyService
 */
export const BridgeProxyService = /*@__PURE__*/
  serviceDesc(file_bridge_v1_proxy, 0);

