// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/reactor.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file bridge/v1/reactor.proto.
 */
export const file_bridge_v1_reactor = /*@__PURE__*/
  fileDesc("ChdicmlkZ2UvdjEvcmVhY3Rvci5wcm90bxIJYnJpZGdlLnYxIlYKB1JlYWN0b3ISGAoEaG9zdBgBIAEoCUIKukgHyAEBcgIQARIxCgZyb3V0ZXMYAiADKAsyFy5icmlkZ2UudjEuUmVhY3RvclJvdXRlQgi6SAWSAQIIASJ1CgxSZWFjdG9yUm91dGUSMwoFbWF0Y2gYASABKAsyHC5icmlkZ2UudjEuUmVhY3RvclJvdXRlTWF0Y2hCBrpIA8gBARIwCgZhY3Rpb24YAiABKAsyGC5icmlkZ2UudjEuUmVhY3RvckFjdGlvbkIGukgDyAEBIiwKEVJlYWN0b3JSb3V0ZU1hdGNoEhcKA2NlbBgBIAEoCUIKukgHyAEBcgIQASJdCg1SZWFjdG9yQWN0aW9uEkwKDWh0dHBfcmVzcG9uc2UYASABKAsyHi5icmlkZ2UudjEuUmVhY3Rvckh0dHBSZXNwb25zZUIGukgDyAEBUg1odHRwX3Jlc3BvbnNlIsUBChNSZWFjdG9ySHR0cFJlc3BvbnNlEhoKBnN0YXR1cxgBIAEoBUIKukgHGgUY1wQoZBIkCgRib2R5GAIgASgLMhYuZ29vZ2xlLnByb3RvYnVmLlZhbHVlEjwKB2hlYWRlcnMYAyADKAsyKy5icmlkZ2UudjEuUmVhY3Rvckh0dHBSZXNwb25zZS5IZWFkZXJzRW50cnkaLgoMSGVhZGVyc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiogIKElJlYWN0b3JIdHRwUmVxdWVzdBIOCgZtZXRob2QYASABKAkSDAoEaG9zdBgCIAEoCRIMCgRwYXRoGAMgASgJEjsKB2hlYWRlcnMYBCADKAsyKi5icmlkZ2UudjEuUmVhY3Rvckh0dHBSZXF1ZXN0LkhlYWRlcnNFbnRyeRI3CgVxdWVyeRgFIAMoCzIoLmJyaWRnZS52MS5SZWFjdG9ySHR0cFJlcXVlc3QuUXVlcnlFbnRyeRIMCgRib2R5GAYgASgJGi4KDEhlYWRlcnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBGiwKClF1ZXJ5RW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUKWAQoNY29tLmJyaWRnZS52MUIMUmVhY3RvclByb3RvUAFaMmdpdGh1Yi5jb20vdmVyY2VsL2JyaWRnZS9hcGkvZ28vYnJpZGdlL3YxO2JyaWRnZXYxogIDQlhYqgIJQnJpZGdlLlYxygIJQnJpZGdlXFYx4gIVQnJpZGdlXFYxXEdQQk1ldGFkYXRh6gIKQnJpZGdlOjpWMWIGcHJvdG8z", [file_buf_validate_validate, file_google_protobuf_struct]);

/**
 * Describes the message bridge.v1.Reactor.
 * Use `create(ReactorSchema)` to create a new message.
 */
export const ReactorSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_reactor, 0);

/**
 * Describes the message bridge.v1.ReactorRoute.
 * Use `create(ReactorRouteSchema)` to create a new message.
 */
export const ReactorRouteSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_reactor, 1);

/**
 * Describes the message bridge.v1.ReactorRouteMatch.
 * Use `create(ReactorRouteMatchSchema)` to create a new message.
 */
export const ReactorRouteMatchSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_reactor, 2);

/**
 * Describes the message bridge.v1.ReactorAction.
 * Use `create(ReactorActionSchema)` to create a new message.
 */
export const ReactorActionSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_reactor, 3);

/**
 * Describes the message bridge.v1.ReactorHttpResponse.
 * Use `create(ReactorHttpResponseSchema)` to create a new message.
 */
export const ReactorHttpResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_reactor, 4);

/**
 * Describes the message bridge.v1.ReactorHttpRequest.
 * Use `create(ReactorHttpRequestSchema)` to create a new message.
 */
export const ReactorHttpRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_reactor, 5);

