// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/reactor.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Value } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file bridge/v1/reactor.proto.
 */
export declare const file_bridge_v1_reactor: GenFile;

/**
 * Reactor intercepts HTTP requests matching a hostname and routes them
 * to actions based on CEL expressions.
 *
 * @generated from message bridge.v1.Reactor
 */
export declare type Reactor = Message<"bridge.v1.Reactor"> & {
  /**
   * Hostname glob pattern this reactor intercepts (e.g. "flags.vercel.com",
   * "*.google.com", "**.internal"). Used for routing and TLS cert minting.
   *
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * Ordered list of routes. First match wins.
   *
   * @generated from field: repeated bridge.v1.ReactorRoute routes = 2;
   */
  routes: ReactorRoute[];
};

/**
 * Describes the message bridge.v1.Reactor.
 * Use `create(ReactorSchema)` to create a new message.
 */
export declare const ReactorSchema: GenMessage<Reactor>;

/**
 * ReactorRoute pairs a route match with an action to take when matched.
 *
 * @generated from message bridge.v1.ReactorRoute
 */
export declare type ReactorRoute = Message<"bridge.v1.ReactorRoute"> & {
  /**
   * Determines whether this route matches an incoming request.
   *
   * @generated from field: bridge.v1.ReactorRouteMatch match = 1;
   */
  match?: ReactorRouteMatch;

  /**
   * What to do when matched.
   *
   * @generated from field: bridge.v1.ReactorAction action = 2;
   */
  action?: ReactorAction;
};

/**
 * Describes the message bridge.v1.ReactorRoute.
 * Use `create(ReactorRouteSchema)` to create a new message.
 */
export declare const ReactorRouteSchema: GenMessage<ReactorRoute>;

/**
 * ReactorRouteMatch evaluates incoming HTTP requests.
 *
 * @generated from message bridge.v1.ReactorRouteMatch
 */
export declare type ReactorRouteMatch = Message<"bridge.v1.ReactorRouteMatch"> & {
  /**
   * CEL expression evaluated against a ReactorHttpRequest.
   * Must return a boolean.
   *
   * @generated from field: string cel = 1;
   */
  cel: string;
};

/**
 * Describes the message bridge.v1.ReactorRouteMatch.
 * Use `create(ReactorRouteMatchSchema)` to create a new message.
 */
export declare const ReactorRouteMatchSchema: GenMessage<ReactorRouteMatch>;

/**
 * ReactorAction defines what response to produce for a matched route.
 *
 * @generated from message bridge.v1.ReactorAction
 */
export declare type ReactorAction = Message<"bridge.v1.ReactorAction"> & {
  /**
   * Static HTTP response.
   *
   * @generated from field: bridge.v1.ReactorHttpResponse http_response = 1 [json_name = "http_response"];
   */
  httpResponse?: ReactorHttpResponse;
};

/**
 * Describes the message bridge.v1.ReactorAction.
 * Use `create(ReactorActionSchema)` to create a new message.
 */
export declare const ReactorActionSchema: GenMessage<ReactorAction>;

/**
 * ReactorHttpResponse is a static HTTP response returned by a reactor route.
 *
 * @generated from message bridge.v1.ReactorHttpResponse
 */
export declare type ReactorHttpResponse = Message<"bridge.v1.ReactorHttpResponse"> & {
  /**
   * HTTP status code.
   *
   * @generated from field: int32 status = 1;
   */
  status: number;

  /**
   * Response body. Marshalled as JSON and sent as the response.
   *
   * @generated from field: google.protobuf.Value body = 2;
   */
  body?: Value;

  /**
   * Response headers.
   *
   * @generated from field: map<string, string> headers = 3;
   */
  headers: { [key: string]: string };
};

/**
 * Describes the message bridge.v1.ReactorHttpResponse.
 * Use `create(ReactorHttpResponseSchema)` to create a new message.
 */
export declare const ReactorHttpResponseSchema: GenMessage<ReactorHttpResponse>;

/**
 * ReactorHttpRequest is the request shape available in CEL expressions as `request`.
 *
 * @generated from message bridge.v1.ReactorHttpRequest
 */
export declare type ReactorHttpRequest = Message<"bridge.v1.ReactorHttpRequest"> & {
  /**
   * @generated from field: string method = 1;
   */
  method: string;

  /**
   * @generated from field: string host = 2;
   */
  host: string;

  /**
   * @generated from field: string path = 3;
   */
  path: string;

  /**
   * @generated from field: map<string, string> headers = 4;
   */
  headers: { [key: string]: string };

  /**
   * @generated from field: map<string, string> query = 5;
   */
  query: { [key: string]: string };

  /**
   * @generated from field: string body = 6;
   */
  body: string;
};

/**
 * Describes the message bridge.v1.ReactorHttpRequest.
 * Use `create(ReactorHttpRequestSchema)` to create a new message.
 */
export declare const ReactorHttpRequestSchema: GenMessage<ReactorHttpRequest>;

