// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/server_facade.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Value } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file bridge/v1/server_facade.proto.
 */
export declare const file_bridge_v1_server_facade: GenFile;

/**
 * ServerFacade intercepts HTTP requests matching a hostname and routes them
 * to actions based on CEL expressions.
 *
 * @generated from message bridge.v1.ServerFacade
 */
export declare type ServerFacade = Message<"bridge.v1.ServerFacade"> & {
  /**
   * Hostname glob pattern this facade intercepts (e.g. "flags.vercel.com",
   * "*.google.com", "**.internal"). Used for routing and TLS cert minting.
   *
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * Ordered list of routes. First match wins.
   *
   * @generated from field: repeated bridge.v1.ServerFacadeRoute routes = 2;
   */
  routes: ServerFacadeRoute[];
};

/**
 * Describes the message bridge.v1.ServerFacade.
 * Use `create(ServerFacadeSchema)` to create a new message.
 */
export declare const ServerFacadeSchema: GenMessage<ServerFacade>;

/**
 * ServerFacadeRoute pairs a route match with an action to take when matched.
 *
 * @generated from message bridge.v1.ServerFacadeRoute
 */
export declare type ServerFacadeRoute = Message<"bridge.v1.ServerFacadeRoute"> & {
  /**
   * Determines whether this route matches an incoming request.
   *
   * @generated from field: bridge.v1.ServerFacadeRouteMatch match = 1;
   */
  match?: ServerFacadeRouteMatch;

  /**
   * What to do when matched.
   *
   * @generated from field: bridge.v1.ServerFacadeAction action = 2;
   */
  action?: ServerFacadeAction;
};

/**
 * Describes the message bridge.v1.ServerFacadeRoute.
 * Use `create(ServerFacadeRouteSchema)` to create a new message.
 */
export declare const ServerFacadeRouteSchema: GenMessage<ServerFacadeRoute>;

/**
 * ServerFacadeRouteMatch evaluates incoming HTTP requests.
 *
 * @generated from message bridge.v1.ServerFacadeRouteMatch
 */
export declare type ServerFacadeRouteMatch = Message<"bridge.v1.ServerFacadeRouteMatch"> & {
  /**
   * CEL expression evaluated against a ServerFacadeHttpRequest.
   * Must return a boolean.
   *
   * @generated from field: string cel = 1;
   */
  cel: string;
};

/**
 * Describes the message bridge.v1.ServerFacadeRouteMatch.
 * Use `create(ServerFacadeRouteMatchSchema)` to create a new message.
 */
export declare const ServerFacadeRouteMatchSchema: GenMessage<ServerFacadeRouteMatch>;

/**
 * ServerFacadeAction defines what response to produce for a matched route.
 *
 * @generated from message bridge.v1.ServerFacadeAction
 */
export declare type ServerFacadeAction = Message<"bridge.v1.ServerFacadeAction"> & {
  /**
   * Static HTTP response.
   *
   * @generated from field: bridge.v1.ServerFacadeHttpResponse http_response = 1 [json_name = "http_response"];
   */
  httpResponse?: ServerFacadeHttpResponse;
};

/**
 * Describes the message bridge.v1.ServerFacadeAction.
 * Use `create(ServerFacadeActionSchema)` to create a new message.
 */
export declare const ServerFacadeActionSchema: GenMessage<ServerFacadeAction>;

/**
 * ServerFacadeHttpResponse is a static HTTP response returned by a facade route.
 *
 * @generated from message bridge.v1.ServerFacadeHttpResponse
 */
export declare type ServerFacadeHttpResponse = Message<"bridge.v1.ServerFacadeHttpResponse"> & {
  /**
   * HTTP status code.
   *
   * @generated from field: int32 status = 1;
   */
  status: number;

  /**
   * Response body. Marshalled as JSON and sent as the response.
   *
   * @generated from field: google.protobuf.Value body = 2;
   */
  body?: Value;

  /**
   * Response headers.
   *
   * @generated from field: map<string, string> headers = 3;
   */
  headers: { [key: string]: string };
};

/**
 * Describes the message bridge.v1.ServerFacadeHttpResponse.
 * Use `create(ServerFacadeHttpResponseSchema)` to create a new message.
 */
export declare const ServerFacadeHttpResponseSchema: GenMessage<ServerFacadeHttpResponse>;

/**
 * ServerFacadeHttpRequest is the request shape available in CEL expressions as `request`.
 *
 * @generated from message bridge.v1.ServerFacadeHttpRequest
 */
export declare type ServerFacadeHttpRequest = Message<"bridge.v1.ServerFacadeHttpRequest"> & {
  /**
   * @generated from field: string method = 1;
   */
  method: string;

  /**
   * @generated from field: string host = 2;
   */
  host: string;

  /**
   * @generated from field: string path = 3;
   */
  path: string;

  /**
   * @generated from field: map<string, string> headers = 4;
   */
  headers: { [key: string]: string };

  /**
   * @generated from field: map<string, string> query = 5;
   */
  query: { [key: string]: string };

  /**
   * @generated from field: string body = 6;
   */
  body: string;
};

/**
 * Describes the message bridge.v1.ServerFacadeHttpRequest.
 * Use `create(ServerFacadeHttpRequestSchema)` to create a new message.
 */
export declare const ServerFacadeHttpRequestSchema: GenMessage<ServerFacadeHttpRequest>;

