// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/server_facade.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file bridge/v1/server_facade.proto.
 */
export const file_bridge_v1_server_facade = /*@__PURE__*/
  fileDesc("Ch1icmlkZ2UvdjEvc2VydmVyX2ZhY2FkZS5wcm90bxIJYnJpZGdlLnYxImAKDFNlcnZlckZhY2FkZRIYCgRob3N0GAEgASgJQgq6SAfIAQFyAhABEjYKBnJvdXRlcxgCIAMoCzIcLmJyaWRnZS52MS5TZXJ2ZXJGYWNhZGVSb3V0ZUIIukgFkgECCAEihAEKEVNlcnZlckZhY2FkZVJvdXRlEjgKBW1hdGNoGAEgASgLMiEuYnJpZGdlLnYxLlNlcnZlckZhY2FkZVJvdXRlTWF0Y2hCBrpIA8gBARI1CgZhY3Rpb24YAiABKAsyHS5icmlkZ2UudjEuU2VydmVyRmFjYWRlQWN0aW9uQga6SAPIAQEiMQoWU2VydmVyRmFjYWRlUm91dGVNYXRjaBIXCgNjZWwYASABKAlCCrpIB8gBAXICEAEiZwoSU2VydmVyRmFjYWRlQWN0aW9uElEKDWh0dHBfcmVzcG9uc2UYASABKAsyIy5icmlkZ2UudjEuU2VydmVyRmFjYWRlSHR0cFJlc3BvbnNlQga6SAPIAQFSDWh0dHBfcmVzcG9uc2UizwEKGFNlcnZlckZhY2FkZUh0dHBSZXNwb25zZRIaCgZzdGF0dXMYASABKAVCCrpIBxoFGNcEKGQSJAoEYm9keRgCIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZRJBCgdoZWFkZXJzGAMgAygLMjAuYnJpZGdlLnYxLlNlcnZlckZhY2FkZUh0dHBSZXNwb25zZS5IZWFkZXJzRW50cnkaLgoMSGVhZGVyc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEisQIKF1NlcnZlckZhY2FkZUh0dHBSZXF1ZXN0Eg4KBm1ldGhvZBgBIAEoCRIMCgRob3N0GAIgASgJEgwKBHBhdGgYAyABKAkSQAoHaGVhZGVycxgEIAMoCzIvLmJyaWRnZS52MS5TZXJ2ZXJGYWNhZGVIdHRwUmVxdWVzdC5IZWFkZXJzRW50cnkSPAoFcXVlcnkYBSADKAsyLS5icmlkZ2UudjEuU2VydmVyRmFjYWRlSHR0cFJlcXVlc3QuUXVlcnlFbnRyeRIMCgRib2R5GAYgASgJGi4KDEhlYWRlcnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBGiwKClF1ZXJ5RW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUKbAQoNY29tLmJyaWRnZS52MUIRU2VydmVyRmFjYWRlUHJvdG9QAVoyZ2l0aHViLmNvbS92ZXJjZWwvYnJpZGdlL2FwaS9nby9icmlkZ2UvdjE7YnJpZGdldjGiAgNCWFiqAglCcmlkZ2UuVjHKAglCcmlkZ2VcVjHiAhVCcmlkZ2VcVjFcR1BCTWV0YWRhdGHqAgpCcmlkZ2U6OlYxYgZwcm90bzM", [file_buf_validate_validate, file_google_protobuf_struct]);

/**
 * Describes the message bridge.v1.ServerFacade.
 * Use `create(ServerFacadeSchema)` to create a new message.
 */
export const ServerFacadeSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_server_facade, 0);

/**
 * Describes the message bridge.v1.ServerFacadeRoute.
 * Use `create(ServerFacadeRouteSchema)` to create a new message.
 */
export const ServerFacadeRouteSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_server_facade, 1);

/**
 * Describes the message bridge.v1.ServerFacadeRouteMatch.
 * Use `create(ServerFacadeRouteMatchSchema)` to create a new message.
 */
export const ServerFacadeRouteMatchSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_server_facade, 2);

/**
 * Describes the message bridge.v1.ServerFacadeAction.
 * Use `create(ServerFacadeActionSchema)` to create a new message.
 */
export const ServerFacadeActionSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_server_facade, 3);

/**
 * Describes the message bridge.v1.ServerFacadeHttpResponse.
 * Use `create(ServerFacadeHttpResponseSchema)` to create a new message.
 */
export const ServerFacadeHttpResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_server_facade, 4);

/**
 * Describes the message bridge.v1.ServerFacadeHttpRequest.
 * Use `create(ServerFacadeHttpRequestSchema)` to create a new message.
 */
export const ServerFacadeHttpRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_server_facade, 5);

