// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/session.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file bridge/v1/session.proto.
 */
export declare const file_bridge_v1_session: GenFile;

/**
 * Session represents a local bridge session stored on the developer's machine.
 *
 * @generated from message bridge.v1.Session
 */
export declare type Session = Message<"bridge.v1.Session"> & {
  /**
   * The name of the bridge (e.g. "my-api-abc123").
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * When the session was created.
   *
   * @generated from field: google.protobuf.Timestamp time_created = 2 [json_name = "time_created"];
   */
  timeCreated?: Timestamp;

  /**
   * The absolute path to the generated devcontainer.json for this bridge.
   *
   * @generated from field: string devcontainer_config_path = 3 [json_name = "devcontainer_config_path"];
   */
  devcontainerConfigPath: string;
};

/**
 * Describes the message bridge.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export declare const SessionSchema: GenMessage<Session>;

