// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file bridge/v1/session.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file bridge/v1/session.proto.
 */
export const file_bridge_v1_session = /*@__PURE__*/
  fileDesc("ChdicmlkZ2UvdjEvc2Vzc2lvbi5wcm90bxIJYnJpZGdlLnYxIpMCCgdTZXNzaW9uEgwKBG5hbWUYASABKAkSPgoMdGltZV9jcmVhdGVkGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcFIMdGltZV9jcmVhdGVkEjoKGGRldmNvbnRhaW5lcl9jb25maWdfcGF0aBgDIAEoCVIYZGV2Y29udGFpbmVyX2NvbmZpZ19wYXRoEhgKB2Rldl9waWQYBCABKAVSB2Rldl9waWQSQgoOZGV2X3N0YXJ0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wUg5kZXZfc3RhcnRlZF9hdBIgCgtkZXZfY29tbWFuZBgGIAEoCVILZGV2X2NvbW1hbmRClgEKDWNvbS5icmlkZ2UudjFCDFNlc3Npb25Qcm90b1ABWjJnaXRodWIuY29tL3ZlcmNlbC9icmlkZ2UvYXBpL2dvL2JyaWRnZS92MTticmlkZ2V2MaICA0JYWKoCCUJyaWRnZS5WMcoCCUJyaWRnZVxWMeICFUJyaWRnZVxWMVxHUEJNZXRhZGF0YeoCCkJyaWRnZTo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Describes the message bridge.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export const SessionSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_session, 0);

