// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/session.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file bridge/v1/session.proto.
 */
export const file_bridge_v1_session = /*@__PURE__*/
  fileDesc("ChdicmlkZ2UvdjEvc2Vzc2lvbi5wcm90bxIJYnJpZGdlLnYxIpMBCgdTZXNzaW9uEgwKBG5hbWUYASABKAkSPgoMdGltZV9jcmVhdGVkGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcFIMdGltZV9jcmVhdGVkEjoKGGRldmNvbnRhaW5lcl9jb25maWdfcGF0aBgDIAEoCVIYZGV2Y29udGFpbmVyX2NvbmZpZ19wYXRoQpYBCg1jb20uYnJpZGdlLnYxQgxTZXNzaW9uUHJvdG9QAVoyZ2l0aHViLmNvbS92ZXJjZWwvYnJpZGdlL2FwaS9nby9icmlkZ2UvdjE7YnJpZGdldjGiAgNCWFiqAglCcmlkZ2UuVjHKAglCcmlkZ2VcVjHiAhVCcmlkZ2VcVjFcR1BCTWV0YWRhdGHqAgpCcmlkZ2U6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message bridge.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export const SessionSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_session, 0);

