// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file bridge/v1/session.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file bridge/v1/session.proto.
 */
export declare const file_bridge_v1_session: GenFile;

/**
 * Session represents a local bridge session stored on the developer's machine.
 *
 * @generated from message bridge.v1.Session
 */
export declare type Session = Message<"bridge.v1.Session"> & {
  /**
   * The name of the bridge (e.g. "my-api-abc123").
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * When the session was created.
   *
   * @generated from field: google.protobuf.Timestamp time_created = 2 [json_name = "time_created"];
   */
  timeCreated?: Timestamp | undefined;

  /**
   * The absolute path to the generated devcontainer.json for this bridge.
   *
   * @generated from field: string devcontainer_config_path = 3 [json_name = "devcontainer_config_path"];
   */
  devcontainerConfigPath: string;

  /**
   * PID inside the devcontainer of the most recent `bridge dev` command.
   * Zero if no dev command has been started for this bridge, or if the last
   * one is known to have exited. Used by `bridge dev` to detect and kill a
   * pre-existing dev process before starting a new one.
   *
   * @generated from field: int32 dev_pid = 4 [json_name = "dev_pid"];
   */
  devPid: number;

  /**
   * When the current dev_pid was started. Absent if dev_pid is zero.
   *
   * @generated from field: google.protobuf.Timestamp dev_started_at = 5 [json_name = "dev_started_at"];
   */
  devStartedAt?: Timestamp | undefined;

  /**
   * The command that was started by the most recent `bridge dev` run.
   * Stored for diagnostics and for the `bridge dev` JSON response.
   *
   * @generated from field: string dev_command = 6 [json_name = "dev_command"];
   */
  devCommand: string;
};

/**
 * Describes the message bridge.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export declare const SessionSchema: GenMessage<Session>;

