// deref-jsonschema reads the bundled JSON Schema files generated by
// buf and produces simplified, fully-dereferenced schemas with clean
// filenames (e.g. MockSpec.schema.json).
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatal("usage: deref-jsonschema <dir>")
	}
	dir := os.Args[1]

	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Fatalf("reading dir: %v", err)
	}

	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".schema.bundle.json") {
			continue
		}

		path := filepath.Join(dir, e.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			log.Fatalf("reading %s: %v", path, err)
		}

		var bundle map[string]any
		if err := json.Unmarshal(data, &bundle); err != nil {
			log.Fatalf("parsing %s: %v", path, err)
		}

		defs, _ := bundle["$defs"].(map[string]any)
		resolved := deref(bundle, defs)

		// Remove the $defs and $ref keys from the top level since
		// everything is now inlined.
		resolvedMap, ok := resolved.(map[string]any)
		if !ok {
			log.Fatalf("expected map at top level of %s", path)
		}
		delete(resolvedMap, "$defs")
		delete(resolvedMap, "$id")
		stripNestedSchema(resolvedMap)
		simplifyEnums(resolvedMap)

		out, err := json.MarshalIndent(resolvedMap, "", "  ")
		if err != nil {
			log.Fatalf("marshalling: %v", err)
		}

		// Simplify filename: bridge.v1.MockSpec.schema.bundle.json -> MockSpec.schema.json
		outName := simplifyName(e.Name())
		outPath := filepath.Join(dir, outName)

		if err := os.WriteFile(outPath, out, 0644); err != nil {
			log.Fatalf("writing %s: %v", outPath, err)
		}
		fmt.Printf("%s -> %s\n", e.Name(), outName)
	}

	// Clean up original bundle and non-bundle files.
	entries, _ = os.ReadDir(dir)
	for _, e := range entries {
		name := e.Name()
		if strings.Contains(name, ".") && strings.Count(name, ".") > 2 {
			// Has package prefix (e.g. bridge.v1. or google.protobuf.) — remove it.
			os.Remove(filepath.Join(dir, name))
		}
	}
}

// deref recursively resolves all $ref pointers in a JSON Schema node.
func deref(node any, defs map[string]any) any {
	switch v := node.(type) {
	case map[string]any:
		// If this node is a $ref, resolve it.
		if ref, ok := v["$ref"].(string); ok {
			if resolved := resolveRef(ref, defs); resolved != nil {
				// Merge any sibling keys (like "description") with the resolved ref.
				merged := deref(resolved, defs).(map[string]any)
				result := make(map[string]any)
				for k, val := range merged {
					result[k] = val
				}
				for k, val := range v {
					if k == "$ref" {
						continue
					}
					result[k] = deref(val, defs)
				}
				return result
			}
		}
		result := make(map[string]any)
		for k, val := range v {
			if k == "$defs" {
				continue
			}
			result[k] = deref(val, defs)
		}
		return result
	case []any:
		result := make([]any, len(v))
		for i, val := range v {
			result[i] = deref(val, defs)
		}
		return result
	default:
		return node
	}
}

// resolveRef looks up a $ref like "#/$defs/bridge.v1.MockRule.schema.json".
func resolveRef(ref string, defs map[string]any) map[string]any {
	const prefix = "#/$defs/"
	if !strings.HasPrefix(ref, prefix) {
		return nil
	}
	key := strings.TrimPrefix(ref, prefix)
	if def, ok := defs[key]; ok {
		if m, ok := def.(map[string]any); ok {
			// Deep copy to avoid mutating the original defs.
			cp := make(map[string]any)
			for k, v := range m {
				cp[k] = v
			}
			return cp
		}
	}
	return nil
}

// stripNestedSchema removes "$schema" from all nested objects, preserving
// only the root-level "$schema".
func stripNestedSchema(root map[string]any) {
	for k, v := range root {
		if k == "$schema" {
			continue // keep root $schema
		}
		stripSchemaRecursive(v)
	}
}

func stripSchemaRecursive(node any) {
	switch v := node.(type) {
	case map[string]any:
		delete(v, "$schema")
		for _, val := range v {
			stripSchemaRecursive(val)
		}
	case []any:
		for _, val := range v {
			stripSchemaRecursive(val)
		}
	}
}

// simplifyEnums rewrites anyOf enum fields that contain both string and integer
// variants (as generated by the protoschema plugin for proto enums) into a
// plain string enum. Only applies when at least one alternative has an "enum"
// keyword with string values — this distinguishes proto enums from proto int32
// fields which use a pattern like "^-?[0-9]+$" instead.
func simplifyEnums(node any) {
	switch v := node.(type) {
	case map[string]any:
		if anyOf, ok := v["anyOf"].([]any); ok {
			var stringValues []any
			hasInt := false
			hasEnum := false
			for _, alt := range anyOf {
				m, ok := alt.(map[string]any)
				if !ok {
					continue
				}
				if m["type"] == "integer" {
					hasInt = true
					continue
				}
				if m["type"] == "string" {
					if vals, ok := m["enum"].([]any); ok {
						hasEnum = true
						stringValues = append(stringValues, vals...)
					} else if pat, ok := m["pattern"].(string); ok {
						pat = strings.TrimPrefix(pat, "^")
						pat = strings.TrimSuffix(pat, "$")
						stringValues = append(stringValues, pat)
					}
				}
			}
			if hasInt && hasEnum && len(stringValues) > 0 {
				delete(v, "anyOf")
				delete(v, "default")
				v["type"] = "string"
				v["enum"] = stringValues
			}
		}
		for _, val := range v {
			simplifyEnums(val)
		}
	case []any:
		for _, val := range v {
			simplifyEnums(val)
		}
	}
}

// simplifyName converts "bridge.v1.MockSpec.schema.bundle.json" to "MockSpec.schema.json"
// and "google.protobuf.Value.schema.bundle.json" to "Value.schema.json".
func simplifyName(name string) string {
	// Remove .bundle from the name.
	name = strings.Replace(name, ".bundle", "", 1)
	// Remove package prefix: everything before the last capitalized segment.
	parts := strings.Split(name, ".")
	for i, p := range parts {
		if len(p) > 0 && p[0] >= 'A' && p[0] <= 'Z' {
			return strings.Join(parts[i:], ".")
		}
	}
	return name
}
