// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: bridge/v1/administrator.proto

package bridgev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/vercel/bridge/api/go/bridge/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdministratorServiceName is the fully-qualified name of the AdministratorService service.
	AdministratorServiceName = "bridge.v1.AdministratorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdministratorServiceCreateBridgeProcedure is the fully-qualified name of the
	// AdministratorService's CreateBridge RPC.
	AdministratorServiceCreateBridgeProcedure = "/bridge.v1.AdministratorService/CreateBridge"
	// AdministratorServiceListBridgesProcedure is the fully-qualified name of the
	// AdministratorService's ListBridges RPC.
	AdministratorServiceListBridgesProcedure = "/bridge.v1.AdministratorService/ListBridges"
	// AdministratorServiceDeleteBridgeProcedure is the fully-qualified name of the
	// AdministratorService's DeleteBridge RPC.
	AdministratorServiceDeleteBridgeProcedure = "/bridge.v1.AdministratorService/DeleteBridge"
)

// AdministratorServiceClient is a client for the bridge.v1.AdministratorService service.
type AdministratorServiceClient interface {
	// CreateBridge provisions a new bridge in the source deployment's namespace,
	// swapping the application container for the bridge proxy.
	CreateBridge(context.Context, *connect.Request[v1.CreateBridgeRequest]) (*connect.Response[v1.CreateBridgeResponse], error)
	// ListBridges returns all active bridges for a device across all namespaces.
	ListBridges(context.Context, *connect.Request[v1.ListBridgesRequest]) (*connect.Response[v1.ListBridgesResponse], error)
	// DeleteBridge tears down a specific bridge and its associated resources.
	DeleteBridge(context.Context, *connect.Request[v1.DeleteBridgeRequest]) (*connect.Response[v1.DeleteBridgeResponse], error)
}

// NewAdministratorServiceClient constructs a client for the bridge.v1.AdministratorService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdministratorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdministratorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	administratorServiceMethods := v1.File_bridge_v1_administrator_proto.Services().ByName("AdministratorService").Methods()
	return &administratorServiceClient{
		createBridge: connect.NewClient[v1.CreateBridgeRequest, v1.CreateBridgeResponse](
			httpClient,
			baseURL+AdministratorServiceCreateBridgeProcedure,
			connect.WithSchema(administratorServiceMethods.ByName("CreateBridge")),
			connect.WithClientOptions(opts...),
		),
		listBridges: connect.NewClient[v1.ListBridgesRequest, v1.ListBridgesResponse](
			httpClient,
			baseURL+AdministratorServiceListBridgesProcedure,
			connect.WithSchema(administratorServiceMethods.ByName("ListBridges")),
			connect.WithClientOptions(opts...),
		),
		deleteBridge: connect.NewClient[v1.DeleteBridgeRequest, v1.DeleteBridgeResponse](
			httpClient,
			baseURL+AdministratorServiceDeleteBridgeProcedure,
			connect.WithSchema(administratorServiceMethods.ByName("DeleteBridge")),
			connect.WithClientOptions(opts...),
		),
	}
}

// administratorServiceClient implements AdministratorServiceClient.
type administratorServiceClient struct {
	createBridge *connect.Client[v1.CreateBridgeRequest, v1.CreateBridgeResponse]
	listBridges  *connect.Client[v1.ListBridgesRequest, v1.ListBridgesResponse]
	deleteBridge *connect.Client[v1.DeleteBridgeRequest, v1.DeleteBridgeResponse]
}

// CreateBridge calls bridge.v1.AdministratorService.CreateBridge.
func (c *administratorServiceClient) CreateBridge(ctx context.Context, req *connect.Request[v1.CreateBridgeRequest]) (*connect.Response[v1.CreateBridgeResponse], error) {
	return c.createBridge.CallUnary(ctx, req)
}

// ListBridges calls bridge.v1.AdministratorService.ListBridges.
func (c *administratorServiceClient) ListBridges(ctx context.Context, req *connect.Request[v1.ListBridgesRequest]) (*connect.Response[v1.ListBridgesResponse], error) {
	return c.listBridges.CallUnary(ctx, req)
}

// DeleteBridge calls bridge.v1.AdministratorService.DeleteBridge.
func (c *administratorServiceClient) DeleteBridge(ctx context.Context, req *connect.Request[v1.DeleteBridgeRequest]) (*connect.Response[v1.DeleteBridgeResponse], error) {
	return c.deleteBridge.CallUnary(ctx, req)
}

// AdministratorServiceHandler is an implementation of the bridge.v1.AdministratorService service.
type AdministratorServiceHandler interface {
	// CreateBridge provisions a new bridge in the source deployment's namespace,
	// swapping the application container for the bridge proxy.
	CreateBridge(context.Context, *connect.Request[v1.CreateBridgeRequest]) (*connect.Response[v1.CreateBridgeResponse], error)
	// ListBridges returns all active bridges for a device across all namespaces.
	ListBridges(context.Context, *connect.Request[v1.ListBridgesRequest]) (*connect.Response[v1.ListBridgesResponse], error)
	// DeleteBridge tears down a specific bridge and its associated resources.
	DeleteBridge(context.Context, *connect.Request[v1.DeleteBridgeRequest]) (*connect.Response[v1.DeleteBridgeResponse], error)
}

// NewAdministratorServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdministratorServiceHandler(svc AdministratorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	administratorServiceMethods := v1.File_bridge_v1_administrator_proto.Services().ByName("AdministratorService").Methods()
	administratorServiceCreateBridgeHandler := connect.NewUnaryHandler(
		AdministratorServiceCreateBridgeProcedure,
		svc.CreateBridge,
		connect.WithSchema(administratorServiceMethods.ByName("CreateBridge")),
		connect.WithHandlerOptions(opts...),
	)
	administratorServiceListBridgesHandler := connect.NewUnaryHandler(
		AdministratorServiceListBridgesProcedure,
		svc.ListBridges,
		connect.WithSchema(administratorServiceMethods.ByName("ListBridges")),
		connect.WithHandlerOptions(opts...),
	)
	administratorServiceDeleteBridgeHandler := connect.NewUnaryHandler(
		AdministratorServiceDeleteBridgeProcedure,
		svc.DeleteBridge,
		connect.WithSchema(administratorServiceMethods.ByName("DeleteBridge")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bridge.v1.AdministratorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdministratorServiceCreateBridgeProcedure:
			administratorServiceCreateBridgeHandler.ServeHTTP(w, r)
		case AdministratorServiceListBridgesProcedure:
			administratorServiceListBridgesHandler.ServeHTTP(w, r)
		case AdministratorServiceDeleteBridgeProcedure:
			administratorServiceDeleteBridgeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdministratorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdministratorServiceHandler struct{}

func (UnimplementedAdministratorServiceHandler) CreateBridge(context.Context, *connect.Request[v1.CreateBridgeRequest]) (*connect.Response[v1.CreateBridgeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bridge.v1.AdministratorService.CreateBridge is not implemented"))
}

func (UnimplementedAdministratorServiceHandler) ListBridges(context.Context, *connect.Request[v1.ListBridgesRequest]) (*connect.Response[v1.ListBridgesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bridge.v1.AdministratorService.ListBridges is not implemented"))
}

func (UnimplementedAdministratorServiceHandler) DeleteBridge(context.Context, *connect.Request[v1.DeleteBridgeRequest]) (*connect.Response[v1.DeleteBridgeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bridge.v1.AdministratorService.DeleteBridge is not implemented"))
}
