// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: bridge/v1/proxy.proto

package bridgev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/vercel/bridge/api/go/bridge/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BridgeProxyServiceName is the fully-qualified name of the BridgeProxyService service.
	BridgeProxyServiceName = "bridge.v1.BridgeProxyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BridgeProxyServiceResolveDNSQueryProcedure is the fully-qualified name of the
	// BridgeProxyService's ResolveDNSQuery RPC.
	BridgeProxyServiceResolveDNSQueryProcedure = "/bridge.v1.BridgeProxyService/ResolveDNSQuery"
	// BridgeProxyServiceTunnelNetworkProcedure is the fully-qualified name of the BridgeProxyService's
	// TunnelNetwork RPC.
	BridgeProxyServiceTunnelNetworkProcedure = "/bridge.v1.BridgeProxyService/TunnelNetwork"
	// BridgeProxyServiceGetMetadataProcedure is the fully-qualified name of the BridgeProxyService's
	// GetMetadata RPC.
	BridgeProxyServiceGetMetadataProcedure = "/bridge.v1.BridgeProxyService/GetMetadata"
	// BridgeProxyServiceCopyFilesProcedure is the fully-qualified name of the BridgeProxyService's
	// CopyFiles RPC.
	BridgeProxyServiceCopyFilesProcedure = "/bridge.v1.BridgeProxyService/CopyFiles"
)

// BridgeProxyServiceClient is a client for the bridge.v1.BridgeProxyService service.
type BridgeProxyServiceClient interface {
	// ResolveDNSQuery resolves a hostname using the in-cluster DNS (CoreDNS).
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ResolveDNSQuery(context.Context, *connect.Request[v1.ProxyResolveDNSRequest]) (*connect.Response[v1.ProxyResolveDNSResponse], error)
	// TunnelNetwork tunnels TCP/UDP traffic to an upstream service over a
	// bidirectional stream. Every message carries source/dest addresses and a
	// connection ID so both sides share the same addressing semantics as the
	// WebSocket Message in bridge.proto.
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	TunnelNetwork(context.Context) *connect.BidiStreamForClient[v1.TunnelNetworkMessage, v1.TunnelNetworkMessage]
	// GetMetadata returns metadata about the bridge proxy, including environment
	// variables from the pod that can be forwarded to the devcontainer.
	GetMetadata(context.Context, *connect.Request[v1.GetMetadataRequest]) (*connect.Response[v1.GetMetadataResponse], error)
	// CopyFiles reads files from the bridge proxy pod and returns their contents
	// along with metadata (timestamps, permissions).
	CopyFiles(context.Context, *connect.Request[v1.CopyFilesRequest]) (*connect.Response[v1.CopyFilesResponse], error)
}

// NewBridgeProxyServiceClient constructs a client for the bridge.v1.BridgeProxyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBridgeProxyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BridgeProxyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bridgeProxyServiceMethods := v1.File_bridge_v1_proxy_proto.Services().ByName("BridgeProxyService").Methods()
	return &bridgeProxyServiceClient{
		resolveDNSQuery: connect.NewClient[v1.ProxyResolveDNSRequest, v1.ProxyResolveDNSResponse](
			httpClient,
			baseURL+BridgeProxyServiceResolveDNSQueryProcedure,
			connect.WithSchema(bridgeProxyServiceMethods.ByName("ResolveDNSQuery")),
			connect.WithClientOptions(opts...),
		),
		tunnelNetwork: connect.NewClient[v1.TunnelNetworkMessage, v1.TunnelNetworkMessage](
			httpClient,
			baseURL+BridgeProxyServiceTunnelNetworkProcedure,
			connect.WithSchema(bridgeProxyServiceMethods.ByName("TunnelNetwork")),
			connect.WithClientOptions(opts...),
		),
		getMetadata: connect.NewClient[v1.GetMetadataRequest, v1.GetMetadataResponse](
			httpClient,
			baseURL+BridgeProxyServiceGetMetadataProcedure,
			connect.WithSchema(bridgeProxyServiceMethods.ByName("GetMetadata")),
			connect.WithClientOptions(opts...),
		),
		copyFiles: connect.NewClient[v1.CopyFilesRequest, v1.CopyFilesResponse](
			httpClient,
			baseURL+BridgeProxyServiceCopyFilesProcedure,
			connect.WithSchema(bridgeProxyServiceMethods.ByName("CopyFiles")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bridgeProxyServiceClient implements BridgeProxyServiceClient.
type bridgeProxyServiceClient struct {
	resolveDNSQuery *connect.Client[v1.ProxyResolveDNSRequest, v1.ProxyResolveDNSResponse]
	tunnelNetwork   *connect.Client[v1.TunnelNetworkMessage, v1.TunnelNetworkMessage]
	getMetadata     *connect.Client[v1.GetMetadataRequest, v1.GetMetadataResponse]
	copyFiles       *connect.Client[v1.CopyFilesRequest, v1.CopyFilesResponse]
}

// ResolveDNSQuery calls bridge.v1.BridgeProxyService.ResolveDNSQuery.
func (c *bridgeProxyServiceClient) ResolveDNSQuery(ctx context.Context, req *connect.Request[v1.ProxyResolveDNSRequest]) (*connect.Response[v1.ProxyResolveDNSResponse], error) {
	return c.resolveDNSQuery.CallUnary(ctx, req)
}

// TunnelNetwork calls bridge.v1.BridgeProxyService.TunnelNetwork.
func (c *bridgeProxyServiceClient) TunnelNetwork(ctx context.Context) *connect.BidiStreamForClient[v1.TunnelNetworkMessage, v1.TunnelNetworkMessage] {
	return c.tunnelNetwork.CallBidiStream(ctx)
}

// GetMetadata calls bridge.v1.BridgeProxyService.GetMetadata.
func (c *bridgeProxyServiceClient) GetMetadata(ctx context.Context, req *connect.Request[v1.GetMetadataRequest]) (*connect.Response[v1.GetMetadataResponse], error) {
	return c.getMetadata.CallUnary(ctx, req)
}

// CopyFiles calls bridge.v1.BridgeProxyService.CopyFiles.
func (c *bridgeProxyServiceClient) CopyFiles(ctx context.Context, req *connect.Request[v1.CopyFilesRequest]) (*connect.Response[v1.CopyFilesResponse], error) {
	return c.copyFiles.CallUnary(ctx, req)
}

// BridgeProxyServiceHandler is an implementation of the bridge.v1.BridgeProxyService service.
type BridgeProxyServiceHandler interface {
	// ResolveDNSQuery resolves a hostname using the in-cluster DNS (CoreDNS).
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ResolveDNSQuery(context.Context, *connect.Request[v1.ProxyResolveDNSRequest]) (*connect.Response[v1.ProxyResolveDNSResponse], error)
	// TunnelNetwork tunnels TCP/UDP traffic to an upstream service over a
	// bidirectional stream. Every message carries source/dest addresses and a
	// connection ID so both sides share the same addressing semantics as the
	// WebSocket Message in bridge.proto.
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	TunnelNetwork(context.Context, *connect.BidiStream[v1.TunnelNetworkMessage, v1.TunnelNetworkMessage]) error
	// GetMetadata returns metadata about the bridge proxy, including environment
	// variables from the pod that can be forwarded to the devcontainer.
	GetMetadata(context.Context, *connect.Request[v1.GetMetadataRequest]) (*connect.Response[v1.GetMetadataResponse], error)
	// CopyFiles reads files from the bridge proxy pod and returns their contents
	// along with metadata (timestamps, permissions).
	CopyFiles(context.Context, *connect.Request[v1.CopyFilesRequest]) (*connect.Response[v1.CopyFilesResponse], error)
}

// NewBridgeProxyServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBridgeProxyServiceHandler(svc BridgeProxyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bridgeProxyServiceMethods := v1.File_bridge_v1_proxy_proto.Services().ByName("BridgeProxyService").Methods()
	bridgeProxyServiceResolveDNSQueryHandler := connect.NewUnaryHandler(
		BridgeProxyServiceResolveDNSQueryProcedure,
		svc.ResolveDNSQuery,
		connect.WithSchema(bridgeProxyServiceMethods.ByName("ResolveDNSQuery")),
		connect.WithHandlerOptions(opts...),
	)
	bridgeProxyServiceTunnelNetworkHandler := connect.NewBidiStreamHandler(
		BridgeProxyServiceTunnelNetworkProcedure,
		svc.TunnelNetwork,
		connect.WithSchema(bridgeProxyServiceMethods.ByName("TunnelNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	bridgeProxyServiceGetMetadataHandler := connect.NewUnaryHandler(
		BridgeProxyServiceGetMetadataProcedure,
		svc.GetMetadata,
		connect.WithSchema(bridgeProxyServiceMethods.ByName("GetMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	bridgeProxyServiceCopyFilesHandler := connect.NewUnaryHandler(
		BridgeProxyServiceCopyFilesProcedure,
		svc.CopyFiles,
		connect.WithSchema(bridgeProxyServiceMethods.ByName("CopyFiles")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bridge.v1.BridgeProxyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BridgeProxyServiceResolveDNSQueryProcedure:
			bridgeProxyServiceResolveDNSQueryHandler.ServeHTTP(w, r)
		case BridgeProxyServiceTunnelNetworkProcedure:
			bridgeProxyServiceTunnelNetworkHandler.ServeHTTP(w, r)
		case BridgeProxyServiceGetMetadataProcedure:
			bridgeProxyServiceGetMetadataHandler.ServeHTTP(w, r)
		case BridgeProxyServiceCopyFilesProcedure:
			bridgeProxyServiceCopyFilesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBridgeProxyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBridgeProxyServiceHandler struct{}

func (UnimplementedBridgeProxyServiceHandler) ResolveDNSQuery(context.Context, *connect.Request[v1.ProxyResolveDNSRequest]) (*connect.Response[v1.ProxyResolveDNSResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bridge.v1.BridgeProxyService.ResolveDNSQuery is not implemented"))
}

func (UnimplementedBridgeProxyServiceHandler) TunnelNetwork(context.Context, *connect.BidiStream[v1.TunnelNetworkMessage, v1.TunnelNetworkMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("bridge.v1.BridgeProxyService.TunnelNetwork is not implemented"))
}

func (UnimplementedBridgeProxyServiceHandler) GetMetadata(context.Context, *connect.Request[v1.GetMetadataRequest]) (*connect.Response[v1.GetMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bridge.v1.BridgeProxyService.GetMetadata is not implemented"))
}

func (UnimplementedBridgeProxyServiceHandler) CopyFiles(context.Context, *connect.Request[v1.CopyFilesRequest]) (*connect.Response[v1.CopyFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bridge.v1.BridgeProxyService.CopyFiles is not implemented"))
}
