package commands

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestRewriteResolvConf_ReplacesNameservers verifies the rewrite is destructive
// for nameserver lines — only the bridge DNS remains so the resolver can't
// fall through to the system nameserver on a transient bridge DNS failure.
func TestRewriteResolvConf_ReplacesNameservers(t *testing.T) {
	original := []byte("nameserver 127.0.0.11\nnameserver 1.1.1.1\nsearch default.svc.cluster.local svc.cluster.local cluster.local\noptions ndots:5\n")
	got := string(rewriteResolvConf(original, "127.0.0.1"))

	nameserverLines := 0
	for _, line := range strings.Split(got, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "nameserver") {
			nameserverLines++
		}
	}
	assert.Equal(t, 1, nameserverLines, "exactly one nameserver line must remain")
	assert.Contains(t, got, "nameserver 127.0.0.1\n", "bridge nameserver must be present")
	assert.NotContains(t, got, "127.0.0.11", "original nameserver must be dropped")
	assert.NotContains(t, got, "1.1.1.1", "secondary nameserver must be dropped")
}

func TestRewriteResolvConf_PreservesSearchAndOptions(t *testing.T) {
	original := []byte("nameserver 10.96.0.10\nsearch foo.svc bar.svc\noptions ndots:5 timeout:1\n")
	got := string(rewriteResolvConf(original, "127.0.0.1"))

	assert.Contains(t, got, "search foo.svc bar.svc")
	assert.Contains(t, got, "options ndots:5 timeout:1")
}

func TestRewriteResolvConf_BridgeNameserverComesFirst(t *testing.T) {
	original := []byte("nameserver 8.8.8.8\nsearch x.y\n")
	got := string(rewriteResolvConf(original, "127.0.0.1"))

	lines := strings.Split(strings.TrimSuffix(got, "\n"), "\n")
	require := assert.New(t)
	require.True(len(lines) >= 1, "expected at least one line")
	require.Equal("nameserver 127.0.0.1", lines[0], "bridge nameserver must be the first line")
}

func TestRewriteResolvConf_EmptyOriginal(t *testing.T) {
	got := string(rewriteResolvConf(nil, "127.0.0.1"))
	assert.Equal(t, "nameserver 127.0.0.1\n", got)
}

func TestRewriteResolvConf_DropsBlankLines(t *testing.T) {
	original := []byte("nameserver 8.8.8.8\n\nsearch x\n\noptions ndots:5\n")
	got := string(rewriteResolvConf(original, "127.0.0.1"))
	for _, line := range strings.Split(strings.TrimSuffix(got, "\n"), "\n") {
		assert.NotEmpty(t, line, "rewritten resolv.conf should have no blank lines, got %q", got)
	}
}

func TestRewriteResolvConf_CommentsPreserved(t *testing.T) {
	// Some distros write comments at the top of /etc/resolv.conf describing
	// who manages the file (systemd-resolved, NetworkManager, etc.). They're
	// not directives we touch, so they should survive the rewrite.
	original := []byte("# Generated by NetworkManager\nnameserver 8.8.8.8\n")
	got := string(rewriteResolvConf(original, "127.0.0.1"))
	assert.Contains(t, got, "# Generated by NetworkManager")
}
